package com.thesift.client.gui;

import com.thesift.TheSift;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import net.minecraft.ChatFormatting;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.Font;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.LerpingBossEvent;
import net.minecraft.client.renderer.RenderPipelines;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.contents.TranslatableContents;
import net.minecraft.resources.Identifier;
import net.minecraft.util.Mth;
import net.neoforged.neoforge.client.event.CustomizeGuiOverlayEvent;
import org.jspecify.annotations.Nullable;

/**
 * Ornate pixel-art health bars for the Sift's bosses and for the vanilla Ender Dragon, Wither and raids: a themed frame with
 * end-caps (cannons, spider legs, batons, wings, vertebrae, crossbows), the boss's face as a central emblem whose eyes glow and
 * flare when it is hurt, the name in a chunky outlined font split around the emblem, and a glossy segmented fill that shimmers,
 * changes colour at each phase, flashes white on a hit and leaves a pale "recent damage" ghost that drains after it.
 *
 * <p>Textures are generated by tools/ui_art.py (layout documented there).
 */
public final class SiftBossBars {
    private static final int W = 256;
    private static final int TRACK_X = 37;
    private static final int TRACK_Y = 15;
    private static final int TRACK_W = 182;

    /** A bar's look: its texture, the fill colour of each phase (highest health first), and where the phases change. */
    private record Style(Identifier texture, int[] phases, float[] marks) {
        int colourAt(float hp) {
            for (int i = 0; i < this.marks.length; i++) {
                if (hp > this.marks[i]) {
                    return this.phases[i];
                }
            }
            return this.phases[Math.min(this.marks.length, this.phases.length - 1)];
        }
    }

    private static Style style(String tex, int[] phases, float... marks) {
        return new Style(TheSift.id("textures/gui/bossbar/" + tex + ".png"), phases, marks);
    }

    private static final Style RAID = style("raid", new int[]{0xFFE62E2E});
    private static final Map<String, Style> STYLES = Map.of(
            "entity." + TheSift.MODID + ".dictator", style("dictator", new int[]{0xFF2EF2E2, 0xFFE8C860, 0xFFFF4A6A}, 0.6F, 0.25F),
            "entity." + TheSift.MODID + ".thumper", style("thumper", new int[]{0xFFFF9F3A, 0xFFFF6A2A, 0xFF29DFEB}, 0.66F, 0.33F),
            "entity." + TheSift.MODID + ".strummer", style("strummer", new int[]{0xFFC46CFF, 0xFFE070D0, 0xFF7FF7FF}, 0.66F, 0.33F),
            "entity.minecraft.ender_dragon", style("ender_dragon", new int[]{0xFFE070FF, 0xFFFF5AC8}, 0.3F),
            "entity.minecraft.wither", style("wither", new int[]{0xFFA49AE8, 0xFF6E6AB8}, 0.5F));

    /** Per-bar memory for the hit flash and the damage ghost. */
    private static final class Track {
        float last;
        float ghost;
        long flashUntil;
        long ghostHoldUntil;
        long lastSeen;

        Track(float hp) {
            this.last = hp;
            this.ghost = hp;
        }
    }

    private static final Map<UUID, Track> TRACKS = new HashMap<>();

    private SiftBossBars() {
    }

    private static @Nullable Style styleFor(Component name) {
        if (!(name.getContents() instanceof TranslatableContents t)) {
            return null;
        }
        String key = t.getKey();
        if (key.startsWith("event.minecraft.raid")) {
            return RAID;
        }
        return STYLES.get(key);
    }

    /** Draws the bar if it is one of ours and cancels the vanilla one; returns whether it did. */
    public static boolean render(CustomizeGuiOverlayEvent.BossEventProgress event) {
        LerpingBossEvent boss = event.getBossEvent();
        Style s = styleFor(boss.getName());
        if (s == null) {
            return false;
        }
        event.setCanceled(true);
        GuiGraphicsExtractor g = event.getGuiGraphics();
        Minecraft mc = Minecraft.getInstance();
        Font font = mc.font;
        long now = System.currentTimeMillis();
        int cx = event.getX() + 91;
        int x = cx - W / 2;
        int y = event.getY() - 6;
        float hp = Mth.clamp(boss.getProgress(), 0.0F, 1.0F);

        // ---- hit memory
        if (TRACKS.size() > 24) {
            TRACKS.values().removeIf(tr -> now - tr.lastSeen > 10_000L);
        }
        Track tr = TRACKS.computeIfAbsent(boss.getId(), id -> new Track(hp));
        long dt = tr.lastSeen == 0 ? 0 : Math.min(200L, now - tr.lastSeen);
        tr.lastSeen = now;
        if (hp < tr.last - 0.0005F) {
            tr.flashUntil = now + 240L;
            tr.ghostHoldUntil = now + 500L;
        }
        tr.last = hp;
        if (hp >= tr.ghost) {
            tr.ghost = hp;
        } else if (now > tr.ghostHoldUntil) {
            tr.ghost = Math.max(hp, tr.ghost - dt * 0.0006F);
        }
        float flash = tr.flashUntil > now ? (tr.flashUntil - now) / 240.0F : 0.0F;
        Identifier tex = s.texture();

        // ---- frame and empty track
        int shake = flash > 0.5F ? (int) ((now / 30L) % 3L) - 1 : 0;
        g.blit(RenderPipelines.GUI_TEXTURED, tex, x, y, 0, 0, W, 32, 256, 64);
        g.blit(RenderPipelines.GUI_TEXTURED, tex, x + TRACK_X, y + TRACK_Y, 0, 38, TRACK_W, 6, 256, 64);

        // ---- the damage ghost, then the fill in its phase colour (flashing white on a hit)
        int w = Math.round(TRACK_W * hp);
        int gw = Math.round(TRACK_W * tr.ghost);
        if (gw > w) {
            g.blit(RenderPipelines.GUI_TEXTURED, tex, x + TRACK_X + w, y + TRACK_Y, w, 32, gw - w, 6, gw - w, 6, 256, 64, 0xC0FFF4E0);
        }
        int colour = s.colourAt(hp);
        if (flash > 0.0F) {
            colour = lerpColour(colour, 0xFFFFFFFF, flash * 0.8F);
        }
        if (w > 0) {
            g.blit(RenderPipelines.GUI_TEXTURED, tex, x + TRACK_X, y + TRACK_Y, 0, 32, w, 6, w, 6, 256, 64, colour);
            // a glint sweeping along the fill, faster as the boss weakens
            int period = 2600 - (int) ((1.0F - hp) * 1400.0F);
            int sweep = (int) ((now % period) * (TRACK_W + 30) / period) - 15;
            for (int i = 0; i < 3; i++) {
                int sx = sweep - i * 2;
                if (sx >= 0 && sx < w) {
                    g.fill(x + TRACK_X + sx, y + TRACK_Y + 1, x + TRACK_X + sx + 1, y + TRACK_Y + 4, (0x90 - i * 0x28) << 24 | 0xFFFFFF);
                }
            }
            // the leading edge flickers
            if ((now / 120L) % 2L == 0L) {
                g.fill(x + TRACK_X + w - 1, y + TRACK_Y, x + TRACK_X + w, y + TRACK_Y + 6, 0xD0FFFFFF);
            }
        }
        // phase marks
        for (float m : s.marks()) {
            int mx = x + TRACK_X + Math.round(TRACK_W * m);
            g.fill(mx, y + TRACK_Y - 1, mx + 1, y + TRACK_Y + 7, 0xFFF0E6C8);
            g.fill(mx + 1, y + TRACK_Y, mx + 2, y + TRACK_Y + 6, 0x90000000);
        }

        // ---- emblem and its glowing eyes (they pulse quicker as health drops, and flare on a hit)
        int ex = x + W / 2 - 16 + shake;
        g.blit(RenderPipelines.GUI_TEXTURED, tex, ex, y, 192, 32, 32, 32, 256, 64);
        float speed = 0.0035F + (1.0F - hp) * 0.006F;
        float pulse = 0.35F + 0.65F * (0.5F + 0.5F * Mth.sin((now % 3_600_000L) * speed));
        int glowA = (int) (255.0F * Mth.clamp(Math.max(pulse, flash), 0.0F, 1.0F));
        g.blit(RenderPipelines.GUI_TEXTURED, tex, ex, y, 224, 32, 32, 32, 32, 32, 256, 64, glowA << 24 | 0xFFFFFF);

        // ---- the name, split around the emblem
        String full = boss.getName().getString();
        int nameColour = lerpColour(s.phases()[0], 0xFFFFFFFF, 0.25F);
        int split = splitPoint(full);
        if (split > 0) {
            Component left = Component.literal(full.substring(0, split)).withStyle(ChatFormatting.BOLD);
            Component right = Component.literal(full.substring(split + 1)).withStyle(ChatFormatting.BOLD);
            outlined(g, font, left, cx - 19 - font.width(left), y + 3, nameColour);
            outlined(g, font, right, cx + 20, y + 3, nameColour);
            event.setIncrement(36);
        } else {
            Component one = Component.literal(full).withStyle(ChatFormatting.BOLD);
            outlined(g, font, one, cx - font.width(one) / 2, y + 32, nameColour);
            event.setIncrement(46);
        }
        return true;
    }

    /** The space nearest the middle of the name, or -1 for a single word. */
    private static int splitPoint(String s) {
        int best = -1;
        int mid = s.length() / 2;
        for (int i = 0; i < s.length(); i++) {
            if (s.charAt(i) == ' ' && (best < 0 || Math.abs(i - mid) < Math.abs(best - mid))) {
                best = i;
            }
        }
        return best;
    }

    /** Chunky pixel lettering: a dark one-pixel outline all round, the colour, and a lighter top half for gloss. */
    private static void outlined(GuiGraphicsExtractor g, Font font, Component text, int x, int y, int colour) {
        int dark = 0xFF000000 | (colour >> 3 & 0x1F1F1F);
        for (int dx = -1; dx <= 1; dx++) {
            for (int dy = -1; dy <= 1; dy++) {
                if (dx != 0 || dy != 0) {
                    g.text(font, text, x + dx, y + dy, dark, false);
                }
            }
        }
        g.text(font, text, x, y + 1, lerpColour(colour, 0xFF000000, 0.35F), false);
        g.text(font, text, x, y, colour, false);
        g.enableScissor(x - 1, y, x + font.width(text) + 1, y + 3);
        g.text(font, text, x, y, lerpColour(colour, 0xFFFFFFFF, 0.45F), false);
        g.disableScissor();
    }

    private static int lerpColour(int a, int b, float t) {
        int r = (int) Mth.lerp(t, a >> 16 & 0xFF, b >> 16 & 0xFF);
        int gg = (int) Mth.lerp(t, a >> 8 & 0xFF, b >> 8 & 0xFF);
        int bb = (int) Mth.lerp(t, a & 0xFF, b & 0xFF);
        return 0xFF000000 | r << 16 | gg << 8 | bb;
    }
}
