// GENERATED by tools/gen_models.py from tools/mobs.py - do not edit by hand.
package com.thesift.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

public final class ModelGeometry {
    private ModelGeometry() {
    }

    public static LayerDefinition bulb() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-6F, -13F, -6F, 12F, 10F, 12F), PartPose.offsetAndRotation(0F, 24F, 0F, 0F, 0F, 0F));
        PartDefinition p1 = p0.addOrReplaceChild("left_ear", CubeListBuilder.create().texOffs(36, 22).addBox(-1.5F, -4F, -1F, 3F, 4F, 2F), PartPose.offsetAndRotation(3F, -13F, 1.5F, 0F, 0F, 0F));
        p1.addOrReplaceChild("left_ear_tip", CubeListBuilder.create().texOffs(0, 28).addBox(-1.5F, -3F, -1F, 3F, 3F, 2F), PartPose.offsetAndRotation(0F, -4F, 0F, 0F, 0F, 0F));
        PartDefinition p3 = p0.addOrReplaceChild("right_ear", CubeListBuilder.create().texOffs(46, 22).addBox(-1.5F, -4F, -1F, 3F, 4F, 2F), PartPose.offsetAndRotation(-3F, -13F, 1.5F, 0F, 0F, 0F));
        p3.addOrReplaceChild("right_ear_tip", CubeListBuilder.create().texOffs(10, 28).addBox(-1.5F, -3F, -1F, 3F, 3F, 2F), PartPose.offsetAndRotation(0F, -4F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("front_left_leg", CubeListBuilder.create().texOffs(48, 0).addBox(-1.5F, 0F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(3.5F, -3F, -3.5F, 0F, 0F, 0F));
        p0.addOrReplaceChild("front_right_leg", CubeListBuilder.create().texOffs(0, 22).addBox(-1.5F, 0F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(-3.5F, -3F, -3.5F, 0F, 0F, 0F));
        p0.addOrReplaceChild("back_left_leg", CubeListBuilder.create().texOffs(12, 22).addBox(-1.5F, 0F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(3.5F, -3F, 3.5F, 0F, 0F, 0F));
        p0.addOrReplaceChild("back_right_leg", CubeListBuilder.create().texOffs(24, 22).addBox(-1.5F, 0F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(-3.5F, -3F, 3.5F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition slumbler() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-8F, -5F, -11F, 16F, 9F, 22F), PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("crest", CubeListBuilder.create().texOffs(76, 0).addBox(0F, -4F, -9F, 0F, 4F, 18F), PartPose.offsetAndRotation(0F, -5F, 0F, 0F, 0F, 0F));
        PartDefinition p2 = p0.addOrReplaceChild("head", CubeListBuilder.create().texOffs(60, 31).addBox(-9F, -4F, -10F, 18F, 5F, 10F), PartPose.offsetAndRotation(0F, -1F, -11F, 0F, 0F, 0F));
        p2.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(34, 51).addBox(-9F, 0F, -10F, 18F, 3F, 10F), PartPose.offsetAndRotation(0F, 1F, 0F, 0F, 0F, 0F));
        PartDefinition p4 = p2.addOrReplaceChild("left_eye", CubeListBuilder.create().texOffs(116, 51).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(5.5F, -4F, -6F, 0F, 0F, 0F));
        p4.addOrReplaceChild("left_eyelid", CubeListBuilder.create().texOffs(18, 77).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F, new CubeDeformation(0.12F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        p2.addOrReplaceChild("left_gills", CubeListBuilder.create().texOffs(112, 0).addBox(0F, -5F, 0F, 5F, 8F, 0F), PartPose.offsetAndRotation(9F, -3F, -3F, 0F, -0.35F, 0F));
        PartDefinition p7 = p2.addOrReplaceChild("right_eye", CubeListBuilder.create().texOffs(30, 77).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(-5.5F, -4F, -6F, 0F, 0F, 0F));
        p7.addOrReplaceChild("right_eyelid", CubeListBuilder.create().texOffs(42, 77).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F, new CubeDeformation(0.12F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        p2.addOrReplaceChild("right_gills", CubeListBuilder.create().texOffs(116, 31).addBox(-5F, -5F, 0F, 5F, 8F, 0F), PartPose.offsetAndRotation(-9F, -3F, -3F, 0F, 0.35F, 0F));
        PartDefinition p10 = p0.addOrReplaceChild("left_front_leg", CubeListBuilder.create().texOffs(72, 65).addBox(0F, -1.5F, -2F, 5F, 3F, 4F), PartPose.offsetAndRotation(7.5F, 2.5F, -7F, 0F, 0F, 0F));
        p10.addOrReplaceChild("left_front_foot", CubeListBuilder.create().texOffs(0, 65).addBox(-2F, 0F, -2.5F, 4F, 7F, 5F), PartPose.offsetAndRotation(4.5F, 0.5F, 0F, 0F, 0F, 0F));
        PartDefinition p12 = p0.addOrReplaceChild("left_hind_leg", CubeListBuilder.create().texOffs(90, 65).addBox(0F, -1.5F, -2F, 5F, 3F, 4F), PartPose.offsetAndRotation(7.5F, 2.5F, 7F, 0F, 0F, 0F));
        p12.addOrReplaceChild("left_hind_foot", CubeListBuilder.create().texOffs(18, 65).addBox(-2F, 0F, -2.5F, 4F, 7F, 5F), PartPose.offsetAndRotation(4.5F, 0.5F, 0F, 0F, 0F, 0F));
        PartDefinition p14 = p0.addOrReplaceChild("right_front_leg", CubeListBuilder.create().texOffs(108, 65).addBox(-5F, -1.5F, -2F, 5F, 3F, 4F), PartPose.offsetAndRotation(-7.5F, 2.5F, -7F, 0F, 0F, 0F));
        p14.addOrReplaceChild("right_front_foot", CubeListBuilder.create().texOffs(36, 65).addBox(-2F, 0F, -2.5F, 4F, 7F, 5F), PartPose.offsetAndRotation(-4.5F, 0.5F, 0F, 0F, 0F, 0F));
        PartDefinition p16 = p0.addOrReplaceChild("right_hind_leg", CubeListBuilder.create().texOffs(0, 77).addBox(-5F, -1.5F, -2F, 5F, 3F, 4F), PartPose.offsetAndRotation(-7.5F, 2.5F, 7F, 0F, 0F, 0F));
        p16.addOrReplaceChild("right_hind_foot", CubeListBuilder.create().texOffs(54, 65).addBox(-2F, 0F, -2.5F, 4F, 7F, 5F), PartPose.offsetAndRotation(-4.5F, 0.5F, 0F, 0F, 0F, 0F));
        PartDefinition p18 = p0.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(20, 31).addBox(-5F, -3F, 0F, 10F, 6F, 10F), PartPose.offsetAndRotation(0F, -1F, 11F, 0F, 0F, 0F));
        PartDefinition p19 = p18.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(0, 51).addBox(-3.5F, -2F, 0F, 7F, 4F, 10F), PartPose.offsetAndRotation(0F, 0F, 10F, 0F, 0F, 0F));
        p19.addOrReplaceChild("tail3", CubeListBuilder.create().texOffs(90, 51).addBox(-2F, -1.5F, 0F, 4F, 3F, 9F).texOffs(0, 31).addBox(0F, -5F, 0F, 0F, 10F, 10F), PartPose.offsetAndRotation(0F, 0F, 10F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    public static LayerDefinition sifter() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(32, 33).addBox(-3.5F, -14F, -2.5F, 7F, 4F, 5F), PartPose.offsetAndRotation(0F, 24F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(0, 33).addBox(-1.75F, 0F, -2F, 3.5F, 10F, 4F), PartPose.offsetAndRotation(1.75F, -10F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("left_fin", CubeListBuilder.create().texOffs(56, 0).addBox(0F, 0F, -1.5F, 1F, 5F, 3F), PartPose.offsetAndRotation(3.5F, -13.5F, 0F, 0F, 0F, -0.35F));
        p0.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(16, 33).addBox(-1.75F, 0F, -2F, 3.5F, 10F, 4F), PartPose.offsetAndRotation(-1.75F, -10F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("right_fin", CubeListBuilder.create().texOffs(56, 17).addBox(-1F, 0F, -1.5F, 1F, 5F, 3F), PartPose.offsetAndRotation(-3.5F, -13.5F, 0F, 0F, 0F, 0.35F));
        PartDefinition p5 = p0.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 17).addBox(-7F, -2F, -7.5F, 14F, 2F, 14F), PartPose.offsetAndRotation(0F, -14F, 0F, 0F, 0F, 0F));
        p5.addOrReplaceChild("lower_tooth_0", CubeListBuilder.create().texOffs(0, 47).addBox(0F, -1F, 0F, 1F, 1F, 1F), PartPose.offsetAndRotation(-4.5F, -2F, -7F, 0F, 0F, 0F));
        p5.addOrReplaceChild("lower_tooth_1", CubeListBuilder.create().texOffs(4, 47).addBox(0F, -1F, 0F, 1F, 1F, 1F), PartPose.offsetAndRotation(-0.5F, -2F, -7F, 0F, 0F, 0F));
        p5.addOrReplaceChild("lower_tooth_2", CubeListBuilder.create().texOffs(8, 47).addBox(0F, -1F, 0F, 1F, 1F, 1F), PartPose.offsetAndRotation(3.5F, -2F, -7F, 0F, 0F, 0F));
        PartDefinition p9 = p5.addOrReplaceChild("lid", CubeListBuilder.create().texOffs(0, 0).addBox(-7F, -3F, -14F, 14F, 3F, 14F), PartPose.offsetAndRotation(0F, -2F, 6.5F, 0F, 0F, 0F));
        p9.addOrReplaceChild("upper_tooth_0", CubeListBuilder.create().texOffs(56, 33).addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offsetAndRotation(-6F, 0F, -13.5F, 0F, 0F, 0F));
        p9.addOrReplaceChild("upper_tooth_1", CubeListBuilder.create().texOffs(12, 47).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offsetAndRotation(-3.5F, 0F, -13.5F, 0F, 0F, 0F));
        p9.addOrReplaceChild("upper_tooth_2", CubeListBuilder.create().texOffs(16, 47).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offsetAndRotation(2.5F, 0F, -13.5F, 0F, 0F, 0F));
        p9.addOrReplaceChild("upper_tooth_3", CubeListBuilder.create().texOffs(60, 33).addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offsetAndRotation(5F, 0F, -13.5F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition enchoer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(104, 24).addBox(-2.5F, -1F, -2.5F, 5F, 5F, 5F).texOffs(34, 38).addBox(-3F, 4F, -3.5F, 6F, 2F, 6F), PartPose.offsetAndRotation(3.5F, 18F, 0.5F, 0F, 0F, 0F));
        root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(0, 38).addBox(-2.5F, -1F, -2.5F, 5F, 5F, 5F).texOffs(58, 38).addBox(-3F, 4F, -3.5F, 6F, 2F, 6F), PartPose.offsetAndRotation(-3.5F, 18F, 0.5F, 0F, 0F, 0F));
        PartDefinition p2 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-6.5F, -13F, -5F, 13F, 14F, 10F).texOffs(46, 0).addBox(-5.5F, -21F, -4.5F, 11F, 9F, 9F).texOffs(72, 24).addBox(-4.5F, -23F, -2F, 9F, 3F, 7F), PartPose.offsetAndRotation(0F, 18F, 0F, 0F, 0F, 0F));
        PartDefinition p3 = p2.addOrReplaceChild("head", CubeListBuilder.create().texOffs(86, 0).addBox(-4.5F, -9F, -4.5F, 9F, 10F, 8F).texOffs(20, 38).addBox(-3F, -7F, -5.5F, 6F, 8F, 1F).texOffs(120, 0).addBox(-1F, -3F, -6.5F, 2F, 2F, 1F), PartPose.offsetAndRotation(0F, -19F, -4F, 0F, 0F, 0F));
        p3.addOrReplaceChild("left_antler", CubeListBuilder.create().texOffs(118, 38).addBox(0F, -1.5F, -1F, 3F, 2F, 2F).texOffs(0, 48).addBox(2F, -3.5F, -1.5F, 7F, 3F, 3F).texOffs(74, 48).addBox(3F, -4.5F, -1F, 1F, 1F, 1F).texOffs(124, 24).addBox(5F, -5.5F, -1F, 1F, 2F, 1F).texOffs(78, 48).addBox(7F, -4.5F, -1F, 1F, 1F, 1F).texOffs(62, 48).addBox(8F, -5.5F, -1F, 1F, 2F, 1F).texOffs(50, 48).addBox(9F, -2.5F, -1F, 1F, 1F, 2F), PartPose.offsetAndRotation(4F, -7.5F, -0.5F, 0F, 0F, -0.32F));
        p3.addOrReplaceChild("right_antler", CubeListBuilder.create().texOffs(40, 48).addBox(-3F, -1.5F, -1F, 3F, 2F, 2F).texOffs(20, 48).addBox(-9F, -3.5F, -1.5F, 7F, 3F, 3F).texOffs(82, 48).addBox(-4F, -4.5F, -1F, 1F, 1F, 1F).texOffs(66, 48).addBox(-6F, -5.5F, -1F, 1F, 2F, 1F).texOffs(86, 48).addBox(-8F, -4.5F, -1F, 1F, 1F, 1F).texOffs(70, 48).addBox(-9F, -5.5F, -1F, 1F, 2F, 1F).texOffs(56, 48).addBox(-10F, -2.5F, -1F, 1F, 1F, 2F), PartPose.offsetAndRotation(-4F, -7.5F, -0.5F, 0F, 0F, 0.32F));
        PartDefinition p6 = p2.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(0, 24).addBox(-1.5F, -1F, -2.5F, 4F, 9F, 5F), PartPose.offsetAndRotation(7F, -18.5F, -1F, 0F, 0F, -0.08F));
        p6.addOrReplaceChild("left_forearm", CubeListBuilder.create().texOffs(36, 24).addBox(-2F, -1F, -2.5F, 4F, 7F, 5F).texOffs(82, 38).addBox(-2F, 5F, -2.5F, 4F, 3F, 5F), PartPose.offsetAndRotation(0.5F, 8F, 0F, 0F, 0F, 0F));
        PartDefinition p8 = p2.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(18, 24).addBox(-2.5F, -1F, -2.5F, 4F, 9F, 5F), PartPose.offsetAndRotation(-7F, -18.5F, -1F, 0F, 0F, 0.08F));
        p8.addOrReplaceChild("right_forearm", CubeListBuilder.create().texOffs(54, 24).addBox(-2F, -1F, -2.5F, 4F, 7F, 5F).texOffs(100, 38).addBox(-2F, 5F, -2.5F, 4F, 3F, 5F), PartPose.offsetAndRotation(-0.5F, 8F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    public static LayerDefinition riveter() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(46, 27).addBox(-2.5F, -13F, -1.5F, 5F, 2F, 3F), PartPose.offsetAndRotation(0F, 24F, 0F, 0F, 0F, 0F));
        PartDefinition p1 = p0.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(40, 17).addBox(-1F, 0F, -1F, 2F, 6F, 2F), PartPose.offsetAndRotation(1.6F, -12F, 0F, -0.12F, 0F, 0F));
        p1.addOrReplaceChild("left_shin", CubeListBuilder.create().texOffs(56, 17).addBox(-1F, 0F, -1F, 2F, 5F, 2F).texOffs(24, 35).addBox(-1.5F, 5F, -2.5F, 3F, 1F, 3F), PartPose.offsetAndRotation(0F, 6F, 0F, 0.24F, 0F, 0F));
        PartDefinition p3 = p0.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(48, 17).addBox(-1F, 0F, -1F, 2F, 6F, 2F), PartPose.offsetAndRotation(-1.6F, -12F, 0F, -0.12F, 0F, 0F));
        p3.addOrReplaceChild("right_shin", CubeListBuilder.create().texOffs(28, 27).addBox(-1F, 0F, -1F, 2F, 5F, 2F).texOffs(36, 35).addBox(-1.5F, 5F, -2.5F, 3F, 1F, 3F), PartPose.offsetAndRotation(0F, 6F, 0F, 0.24F, 0F, 0F));
        PartDefinition p5 = p0.addOrReplaceChild("torso", CubeListBuilder.create().texOffs(36, 27).addBox(-1.5F, -4F, -1F, 3F, 4F, 2F).texOffs(28, 0).addBox(-3.5F, -10F, -2F, 7F, 6F, 4F).texOffs(0, 27).addBox(-4.5F, -12.5F, -2.5F, 9F, 3F, 5F).texOffs(52, 35).addBox(-0.5F, -14.5F, 0.5F, 1F, 2F, 1F).texOffs(48, 35).addBox(-0.5F, -15.5F, 2F, 1F, 3F, 1F), PartPose.offsetAndRotation(0F, -13F, 0F, 0.22F, 0F, 0F));
        PartDefinition p6 = p5.addOrReplaceChild("head", CubeListBuilder.create().texOffs(4, 17).addBox(-2.5F, -4F, -4.5F, 5F, 4F, 5F), PartPose.offsetAndRotation(0F, -11.5F, -2.5F, 0.08F, 0F, 0F));
        p6.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(0, 35).addBox(-2F, 0F, -4.5F, 4F, 1F, 4F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        p6.addOrReplaceChild("left_horn", CubeListBuilder.create().texOffs(16, 35).addBox(-0.5F, -4F, -0.5F, 1F, 4F, 1F), PartPose.offsetAndRotation(1.5F, -4F, -1F, -0.7F, 0F, 0.35F));
        p6.addOrReplaceChild("right_horn", CubeListBuilder.create().texOffs(20, 35).addBox(-0.5F, -4F, -0.5F, 1F, 4F, 1F), PartPose.offsetAndRotation(-1.5F, -4F, -1F, -0.7F, 0F, -0.35F));
        PartDefinition p10 = p5.addOrReplaceChild("left_wing", CubeListBuilder.create().texOffs(0, 0).addBox(0F, -4F, -1.5F, 4F, 14F, 3F), PartPose.offsetAndRotation(4.5F, -10.5F, 0.5F, 0F, 0F, 0F));
        p10.addOrReplaceChild("left_claw_0", CubeListBuilder.create().texOffs(24, 17).addBox(-0.5F, 0F, -0.5F, 1F, 8F, 1F), PartPose.offsetAndRotation(0.5F, 9.5F, 0.5F, 0.08F, 0F, 0.05F));
        p10.addOrReplaceChild("left_claw_1", CubeListBuilder.create().texOffs(50, 0).addBox(-0.5F, 0F, -0.5F, 1F, 9F, 1F), PartPose.offsetAndRotation(1.5F, 9.5F, -0.5F, 0.08F, 0F, 0.015F));
        p10.addOrReplaceChild("left_claw_2", CubeListBuilder.create().texOffs(54, 0).addBox(-0.5F, 0F, -0.5F, 1F, 9F, 1F), PartPose.offsetAndRotation(2.5F, 9.5F, 0.5F, 0.08F, 0F, -0.02F));
        p10.addOrReplaceChild("left_claw_3", CubeListBuilder.create().texOffs(28, 17).addBox(-0.5F, 0F, -0.5F, 1F, 8F, 1F), PartPose.offsetAndRotation(3.5F, 9.5F, -0.5F, 0.08F, 0F, -0.055F));
        PartDefinition p15 = p5.addOrReplaceChild("right_wing", CubeListBuilder.create().texOffs(14, 0).addBox(-4F, -4F, -1.5F, 4F, 14F, 3F), PartPose.offsetAndRotation(-4.5F, -10.5F, 0.5F, 0F, 0F, 0F));
        p15.addOrReplaceChild("right_claw_0", CubeListBuilder.create().texOffs(32, 17).addBox(-0.5F, 0F, -0.5F, 1F, 8F, 1F), PartPose.offsetAndRotation(-0.5F, 9.5F, 0.5F, 0.08F, 0F, -0.05F));
        p15.addOrReplaceChild("right_claw_1", CubeListBuilder.create().texOffs(58, 0).addBox(-0.5F, 0F, -0.5F, 1F, 9F, 1F), PartPose.offsetAndRotation(-1.5F, 9.5F, -0.5F, 0.08F, 0F, -0.015F));
        p15.addOrReplaceChild("right_claw_2", CubeListBuilder.create().texOffs(0, 17).addBox(-0.5F, 0F, -0.5F, 1F, 9F, 1F), PartPose.offsetAndRotation(-2.5F, 9.5F, 0.5F, 0.08F, 0F, 0.02F));
        p15.addOrReplaceChild("right_claw_3", CubeListBuilder.create().texOffs(36, 17).addBox(-0.5F, 0F, -0.5F, 1F, 8F, 1F), PartPose.offsetAndRotation(-3.5F, 9.5F, -0.5F, 0.08F, 0F, 0.055F));
        return LayerDefinition.create(mesh, 64, 64);
    }
}
