// GENERATED by tools/gen_models.py from tools/mobs.py - do not edit by hand.
package com.thesift.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

public final class ModelGeometry {
    private ModelGeometry() {
    }

    public static LayerDefinition bulb() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-6F, -13F, -6F, 12F, 10F, 12F), PartPose.offsetAndRotation(0F, 24F, 0F, 0F, 0F, 0F));
        PartDefinition p1 = p0.addOrReplaceChild("left_ear", CubeListBuilder.create().texOffs(12, 37).addBox(-1.5F, -4F, -1F, 3F, 4F, 2F), PartPose.offsetAndRotation(3F, -13F, 1.5F, 0F, 0F, 0F));
        p1.addOrReplaceChild("left_ear_tip", CubeListBuilder.create().texOffs(32, 37).addBox(-1.5F, -3F, -1F, 3F, 3F, 2F), PartPose.offsetAndRotation(0F, -4F, 0F, 0F, 0F, 0F));
        PartDefinition p3 = p0.addOrReplaceChild("right_ear", CubeListBuilder.create().texOffs(22, 37).addBox(-1.5F, -4F, -1F, 3F, 4F, 2F), PartPose.offsetAndRotation(-3F, -13F, 1.5F, 0F, 0F, 0F));
        p3.addOrReplaceChild("right_ear_tip", CubeListBuilder.create().texOffs(42, 37).addBox(-1.5F, -3F, -1F, 3F, 3F, 2F), PartPose.offsetAndRotation(0F, -4F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("front_left_leg", CubeListBuilder.create().texOffs(48, 0).addBox(-1.5F, 0F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(3.5F, -3F, -3.5F, 0F, 0F, 0F));
        p0.addOrReplaceChild("front_right_leg", CubeListBuilder.create().texOffs(32, 22).addBox(-1.5F, 0F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(-3.5F, -3F, -3.5F, 0F, 0F, 0F));
        p0.addOrReplaceChild("back_left_leg", CubeListBuilder.create().texOffs(44, 22).addBox(-1.5F, 0F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(3.5F, -3F, 3.5F, 0F, 0F, 0F));
        p0.addOrReplaceChild("back_right_leg", CubeListBuilder.create().texOffs(0, 37).addBox(-1.5F, 0F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(-3.5F, -3F, 3.5F, 0F, 0F, 0F));
        root.addOrReplaceChild("core", CubeListBuilder.create().texOffs(0, 22).addBox(-4F, -11F, -4F, 8F, 7F, 8F), PartPose.offsetAndRotation(0F, 24F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition slumbler() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-8F, -5F, -11F, 16F, 9F, 22F), PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("crest", CubeListBuilder.create().texOffs(76, 0).addBox(0F, -4F, -9F, 0F, 4F, 18F), PartPose.offsetAndRotation(0F, -5F, 0F, 0F, 0F, 0F));
        PartDefinition p2 = p0.addOrReplaceChild("head", CubeListBuilder.create().texOffs(60, 31).addBox(-9F, -4F, -10F, 18F, 5F, 10F), PartPose.offsetAndRotation(0F, -1F, -11F, 0F, 0F, 0F));
        p2.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(34, 51).addBox(-9F, 0F, -10F, 18F, 3F, 10F), PartPose.offsetAndRotation(0F, 1F, 0F, 0F, 0F, 0F));
        PartDefinition p4 = p2.addOrReplaceChild("left_eye", CubeListBuilder.create().texOffs(116, 51).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(5.5F, -4F, -6F, 0F, 0F, 0F));
        p4.addOrReplaceChild("left_eyelid", CubeListBuilder.create().texOffs(18, 77).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F, new CubeDeformation(0.12F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        p2.addOrReplaceChild("left_gills", CubeListBuilder.create().texOffs(112, 0).addBox(0F, -5F, 0F, 5F, 8F, 0F), PartPose.offsetAndRotation(9F, -3F, -3F, 0F, -0.35F, 0F));
        PartDefinition p7 = p2.addOrReplaceChild("right_eye", CubeListBuilder.create().texOffs(30, 77).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(-5.5F, -4F, -6F, 0F, 0F, 0F));
        p7.addOrReplaceChild("right_eyelid", CubeListBuilder.create().texOffs(42, 77).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F, new CubeDeformation(0.12F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        p2.addOrReplaceChild("right_gills", CubeListBuilder.create().texOffs(116, 31).addBox(-5F, -5F, 0F, 5F, 8F, 0F), PartPose.offsetAndRotation(-9F, -3F, -3F, 0F, 0.35F, 0F));
        PartDefinition p10 = p0.addOrReplaceChild("left_front_leg", CubeListBuilder.create().texOffs(72, 65).addBox(0F, -1.5F, -2F, 5F, 3F, 4F), PartPose.offsetAndRotation(7.5F, 2.5F, -7F, 0F, 0F, 0F));
        p10.addOrReplaceChild("left_front_foot", CubeListBuilder.create().texOffs(0, 65).addBox(-2F, 0F, -2.5F, 4F, 7F, 5F), PartPose.offsetAndRotation(4.5F, 0.5F, 0F, 0F, 0F, 0F));
        PartDefinition p12 = p0.addOrReplaceChild("left_hind_leg", CubeListBuilder.create().texOffs(90, 65).addBox(0F, -1.5F, -2F, 5F, 3F, 4F), PartPose.offsetAndRotation(7.5F, 2.5F, 7F, 0F, 0F, 0F));
        p12.addOrReplaceChild("left_hind_foot", CubeListBuilder.create().texOffs(18, 65).addBox(-2F, 0F, -2.5F, 4F, 7F, 5F), PartPose.offsetAndRotation(4.5F, 0.5F, 0F, 0F, 0F, 0F));
        PartDefinition p14 = p0.addOrReplaceChild("right_front_leg", CubeListBuilder.create().texOffs(108, 65).addBox(-5F, -1.5F, -2F, 5F, 3F, 4F), PartPose.offsetAndRotation(-7.5F, 2.5F, -7F, 0F, 0F, 0F));
        p14.addOrReplaceChild("right_front_foot", CubeListBuilder.create().texOffs(36, 65).addBox(-2F, 0F, -2.5F, 4F, 7F, 5F), PartPose.offsetAndRotation(-4.5F, 0.5F, 0F, 0F, 0F, 0F));
        PartDefinition p16 = p0.addOrReplaceChild("right_hind_leg", CubeListBuilder.create().texOffs(0, 77).addBox(-5F, -1.5F, -2F, 5F, 3F, 4F), PartPose.offsetAndRotation(-7.5F, 2.5F, 7F, 0F, 0F, 0F));
        p16.addOrReplaceChild("right_hind_foot", CubeListBuilder.create().texOffs(54, 65).addBox(-2F, 0F, -2.5F, 4F, 7F, 5F), PartPose.offsetAndRotation(-4.5F, 0.5F, 0F, 0F, 0F, 0F));
        PartDefinition p18 = p0.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(20, 31).addBox(-5F, -3F, 0F, 10F, 6F, 10F), PartPose.offsetAndRotation(0F, -1F, 11F, 0F, 0F, 0F));
        PartDefinition p19 = p18.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(0, 51).addBox(-3.5F, -2F, 0F, 7F, 4F, 10F), PartPose.offsetAndRotation(0F, 0F, 10F, 0F, 0F, 0F));
        p19.addOrReplaceChild("tail3", CubeListBuilder.create().texOffs(90, 51).addBox(-2F, -1.5F, 0F, 4F, 3F, 9F).texOffs(0, 31).addBox(0F, -5F, 0F, 0F, 10F, 10F), PartPose.offsetAndRotation(0F, 0F, 10F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    public static LayerDefinition sifter() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(32, 33).addBox(-3.5F, -14F, -2.5F, 7F, 4F, 5F), PartPose.offsetAndRotation(0F, 24F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(0, 33).addBox(-1.75F, 0F, -2F, 3.5F, 10F, 4F), PartPose.offsetAndRotation(1.75F, -10F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("left_fin", CubeListBuilder.create().texOffs(56, 0).addBox(0F, 0F, -1.5F, 1F, 5F, 3F), PartPose.offsetAndRotation(3.5F, -13.5F, 0F, 0F, 0F, -0.35F));
        p0.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(16, 33).addBox(-1.75F, 0F, -2F, 3.5F, 10F, 4F), PartPose.offsetAndRotation(-1.75F, -10F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("right_fin", CubeListBuilder.create().texOffs(56, 17).addBox(-1F, 0F, -1.5F, 1F, 5F, 3F), PartPose.offsetAndRotation(-3.5F, -13.5F, 0F, 0F, 0F, 0.35F));
        PartDefinition p5 = p0.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 17).addBox(-7F, -2F, -7.5F, 14F, 2F, 14F), PartPose.offsetAndRotation(0F, -14F, 0F, 0F, 0F, 0F));
        p5.addOrReplaceChild("lower_tooth_0", CubeListBuilder.create().texOffs(0, 47).addBox(0F, -1F, 0F, 1F, 1F, 1F), PartPose.offsetAndRotation(-4.5F, -2F, -7F, 0F, 0F, 0F));
        p5.addOrReplaceChild("lower_tooth_1", CubeListBuilder.create().texOffs(4, 47).addBox(0F, -1F, 0F, 1F, 1F, 1F), PartPose.offsetAndRotation(-0.5F, -2F, -7F, 0F, 0F, 0F));
        p5.addOrReplaceChild("lower_tooth_2", CubeListBuilder.create().texOffs(8, 47).addBox(0F, -1F, 0F, 1F, 1F, 1F), PartPose.offsetAndRotation(3.5F, -2F, -7F, 0F, 0F, 0F));
        PartDefinition p9 = p5.addOrReplaceChild("lid", CubeListBuilder.create().texOffs(0, 0).addBox(-7F, -3F, -14F, 14F, 3F, 14F), PartPose.offsetAndRotation(0F, -2F, 6.5F, 0F, 0F, 0F));
        p9.addOrReplaceChild("upper_tooth_0", CubeListBuilder.create().texOffs(56, 33).addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offsetAndRotation(-6F, 0F, -13.5F, 0F, 0F, 0F));
        p9.addOrReplaceChild("upper_tooth_1", CubeListBuilder.create().texOffs(12, 47).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offsetAndRotation(-3.5F, 0F, -13.5F, 0F, 0F, 0F));
        p9.addOrReplaceChild("upper_tooth_2", CubeListBuilder.create().texOffs(16, 47).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offsetAndRotation(2.5F, 0F, -13.5F, 0F, 0F, 0F));
        p9.addOrReplaceChild("upper_tooth_3", CubeListBuilder.create().texOffs(60, 33).addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offsetAndRotation(5F, 0F, -13.5F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition enchoer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(104, 24).addBox(-2.5F, -1F, -2.5F, 5F, 5F, 5F).texOffs(34, 38).addBox(-3F, 4F, -3.5F, 6F, 2F, 6F), PartPose.offsetAndRotation(3.5F, 18F, 0.5F, 0F, 0F, 0F));
        root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(0, 38).addBox(-2.5F, -1F, -2.5F, 5F, 5F, 5F).texOffs(58, 38).addBox(-3F, 4F, -3.5F, 6F, 2F, 6F), PartPose.offsetAndRotation(-3.5F, 18F, 0.5F, 0F, 0F, 0F));
        PartDefinition p2 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-6.5F, -13F, -5F, 13F, 14F, 10F).texOffs(46, 0).addBox(-5.5F, -21F, -4.5F, 11F, 9F, 9F).texOffs(72, 24).addBox(-4.5F, -23F, -2F, 9F, 3F, 7F), PartPose.offsetAndRotation(0F, 18F, 0F, 0F, 0F, 0F));
        PartDefinition p3 = p2.addOrReplaceChild("head", CubeListBuilder.create().texOffs(86, 0).addBox(-4.5F, -9F, -4.5F, 9F, 10F, 8F).texOffs(20, 38).addBox(-3F, -7F, -5.5F, 6F, 8F, 1F).texOffs(120, 0).addBox(-1F, -3F, -6.5F, 2F, 2F, 1F), PartPose.offsetAndRotation(0F, -19F, -4F, 0F, 0F, 0F));
        p3.addOrReplaceChild("left_antler", CubeListBuilder.create().texOffs(118, 38).addBox(0F, -1.5F, -1F, 3F, 2F, 2F).texOffs(0, 48).addBox(2F, -3.5F, -1.5F, 7F, 3F, 3F).texOffs(74, 48).addBox(3F, -4.5F, -1F, 1F, 1F, 1F).texOffs(124, 24).addBox(5F, -5.5F, -1F, 1F, 2F, 1F).texOffs(78, 48).addBox(7F, -4.5F, -1F, 1F, 1F, 1F).texOffs(62, 48).addBox(8F, -5.5F, -1F, 1F, 2F, 1F).texOffs(50, 48).addBox(9F, -2.5F, -1F, 1F, 1F, 2F), PartPose.offsetAndRotation(4F, -7.5F, -0.5F, 0F, 0F, -0.32F));
        p3.addOrReplaceChild("right_antler", CubeListBuilder.create().texOffs(40, 48).addBox(-3F, -1.5F, -1F, 3F, 2F, 2F).texOffs(20, 48).addBox(-9F, -3.5F, -1.5F, 7F, 3F, 3F).texOffs(82, 48).addBox(-4F, -4.5F, -1F, 1F, 1F, 1F).texOffs(66, 48).addBox(-6F, -5.5F, -1F, 1F, 2F, 1F).texOffs(86, 48).addBox(-8F, -4.5F, -1F, 1F, 1F, 1F).texOffs(70, 48).addBox(-9F, -5.5F, -1F, 1F, 2F, 1F).texOffs(56, 48).addBox(-10F, -2.5F, -1F, 1F, 1F, 2F), PartPose.offsetAndRotation(-4F, -7.5F, -0.5F, 0F, 0F, 0.32F));
        PartDefinition p6 = p2.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(0, 24).addBox(-1.5F, -1F, -2.5F, 4F, 9F, 5F), PartPose.offsetAndRotation(7F, -18.5F, -1F, 0F, 0F, -0.08F));
        p6.addOrReplaceChild("left_forearm", CubeListBuilder.create().texOffs(36, 24).addBox(-2F, -1F, -2.5F, 4F, 7F, 5F).texOffs(82, 38).addBox(-2F, 5F, -2.5F, 4F, 3F, 5F), PartPose.offsetAndRotation(0.5F, 8F, 0F, 0F, 0F, 0F));
        PartDefinition p8 = p2.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(18, 24).addBox(-2.5F, -1F, -2.5F, 4F, 9F, 5F), PartPose.offsetAndRotation(-7F, -18.5F, -1F, 0F, 0F, 0.08F));
        p8.addOrReplaceChild("right_forearm", CubeListBuilder.create().texOffs(54, 24).addBox(-2F, -1F, -2.5F, 4F, 7F, 5F).texOffs(100, 38).addBox(-2F, 5F, -2.5F, 4F, 3F, 5F), PartPose.offsetAndRotation(-0.5F, 8F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    public static LayerDefinition riveter() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(46, 27).addBox(-2.5F, -13F, -1.5F, 5F, 2F, 3F), PartPose.offsetAndRotation(0F, 24F, 0F, 0F, 0F, 0F));
        PartDefinition p1 = p0.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(40, 17).addBox(-1F, 0F, -1F, 2F, 6F, 2F), PartPose.offsetAndRotation(1.6F, -12F, 0F, -0.12F, 0F, 0F));
        p1.addOrReplaceChild("left_shin", CubeListBuilder.create().texOffs(56, 17).addBox(-1F, 0F, -1F, 2F, 5F, 2F).texOffs(24, 35).addBox(-1.5F, 5F, -2.5F, 3F, 1F, 3F), PartPose.offsetAndRotation(0F, 6F, 0F, 0.24F, 0F, 0F));
        PartDefinition p3 = p0.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(48, 17).addBox(-1F, 0F, -1F, 2F, 6F, 2F), PartPose.offsetAndRotation(-1.6F, -12F, 0F, -0.12F, 0F, 0F));
        p3.addOrReplaceChild("right_shin", CubeListBuilder.create().texOffs(28, 27).addBox(-1F, 0F, -1F, 2F, 5F, 2F).texOffs(36, 35).addBox(-1.5F, 5F, -2.5F, 3F, 1F, 3F), PartPose.offsetAndRotation(0F, 6F, 0F, 0.24F, 0F, 0F));
        PartDefinition p5 = p0.addOrReplaceChild("torso", CubeListBuilder.create().texOffs(36, 27).addBox(-1.5F, -4F, -1F, 3F, 4F, 2F).texOffs(28, 0).addBox(-3.5F, -10F, -2F, 7F, 6F, 4F).texOffs(0, 27).addBox(-4.5F, -12.5F, -2.5F, 9F, 3F, 5F).texOffs(52, 35).addBox(-0.5F, -14.5F, 0.5F, 1F, 2F, 1F).texOffs(48, 35).addBox(-0.5F, -15.5F, 2F, 1F, 3F, 1F), PartPose.offsetAndRotation(0F, -13F, 0F, 0.22F, 0F, 0F));
        PartDefinition p6 = p5.addOrReplaceChild("head", CubeListBuilder.create().texOffs(4, 17).addBox(-2.5F, -4F, -4.5F, 5F, 4F, 5F), PartPose.offsetAndRotation(0F, -11.5F, -2.5F, 0.08F, 0F, 0F));
        p6.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(0, 35).addBox(-2F, 0F, -4.5F, 4F, 1F, 4F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        p6.addOrReplaceChild("left_horn", CubeListBuilder.create().texOffs(16, 35).addBox(-0.5F, -4F, -0.5F, 1F, 4F, 1F), PartPose.offsetAndRotation(1.5F, -4F, -1F, -0.7F, 0F, 0.35F));
        p6.addOrReplaceChild("right_horn", CubeListBuilder.create().texOffs(20, 35).addBox(-0.5F, -4F, -0.5F, 1F, 4F, 1F), PartPose.offsetAndRotation(-1.5F, -4F, -1F, -0.7F, 0F, -0.35F));
        PartDefinition p10 = p5.addOrReplaceChild("left_wing", CubeListBuilder.create().texOffs(0, 0).addBox(0F, -4F, -1.5F, 4F, 14F, 3F), PartPose.offsetAndRotation(4.5F, -10.5F, 0.5F, 0F, 0F, 0F));
        p10.addOrReplaceChild("left_claw_0", CubeListBuilder.create().texOffs(24, 17).addBox(-0.5F, 0F, -0.5F, 1F, 8F, 1F), PartPose.offsetAndRotation(0.5F, 9.5F, 0.5F, 0.08F, 0F, 0.05F));
        p10.addOrReplaceChild("left_claw_1", CubeListBuilder.create().texOffs(50, 0).addBox(-0.5F, 0F, -0.5F, 1F, 9F, 1F), PartPose.offsetAndRotation(1.5F, 9.5F, -0.5F, 0.08F, 0F, 0.015F));
        p10.addOrReplaceChild("left_claw_2", CubeListBuilder.create().texOffs(54, 0).addBox(-0.5F, 0F, -0.5F, 1F, 9F, 1F), PartPose.offsetAndRotation(2.5F, 9.5F, 0.5F, 0.08F, 0F, -0.02F));
        p10.addOrReplaceChild("left_claw_3", CubeListBuilder.create().texOffs(28, 17).addBox(-0.5F, 0F, -0.5F, 1F, 8F, 1F), PartPose.offsetAndRotation(3.5F, 9.5F, -0.5F, 0.08F, 0F, -0.055F));
        PartDefinition p15 = p5.addOrReplaceChild("right_wing", CubeListBuilder.create().texOffs(14, 0).addBox(-4F, -4F, -1.5F, 4F, 14F, 3F), PartPose.offsetAndRotation(-4.5F, -10.5F, 0.5F, 0F, 0F, 0F));
        p15.addOrReplaceChild("right_claw_0", CubeListBuilder.create().texOffs(32, 17).addBox(-0.5F, 0F, -0.5F, 1F, 8F, 1F), PartPose.offsetAndRotation(-0.5F, 9.5F, 0.5F, 0.08F, 0F, -0.05F));
        p15.addOrReplaceChild("right_claw_1", CubeListBuilder.create().texOffs(58, 0).addBox(-0.5F, 0F, -0.5F, 1F, 9F, 1F), PartPose.offsetAndRotation(-1.5F, 9.5F, -0.5F, 0.08F, 0F, -0.015F));
        p15.addOrReplaceChild("right_claw_2", CubeListBuilder.create().texOffs(0, 17).addBox(-0.5F, 0F, -0.5F, 1F, 9F, 1F), PartPose.offsetAndRotation(-2.5F, 9.5F, 0.5F, 0.08F, 0F, 0.02F));
        p15.addOrReplaceChild("right_claw_3", CubeListBuilder.create().texOffs(36, 17).addBox(-0.5F, 0F, -0.5F, 1F, 8F, 1F), PartPose.offsetAndRotation(-3.5F, 9.5F, -0.5F, 0.08F, 0F, 0.055F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition harmoner() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(26, 23).addBox(-0.5F, 0F, -0.5F, 1F, 3F, 1F).texOffs(34, 23).addBox(-1F, 3F, -1.5F, 2F, 1F, 2F), PartPose.offsetAndRotation(1.5F, 20F, 0.5F, 0F, 0F, 0F));
        root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(30, 23).addBox(-0.5F, 0F, -0.5F, 1F, 3F, 1F).texOffs(42, 23).addBox(-1F, 3F, -1.5F, 2F, 1F, 2F), PartPose.offsetAndRotation(-1.5F, 20F, 0.5F, 0F, 0F, 0F));
        PartDefinition p2 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3F, -6F, -3.5F, 6F, 6F, 7F), PartPose.offsetAndRotation(0F, 20F, 0F, 0F, 0F, 0F));
        PartDefinition p3 = p2.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 13).addBox(-2.5F, -5F, -2.5F, 5F, 5F, 5F).texOffs(0, 23).addBox(-1.5F, -3F, -5.5F, 3F, 2F, 3F), PartPose.offsetAndRotation(0F, -6F, -2F, 0F, 0F, 0F));
        p3.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(16, 23).addBox(-1F, 0F, -2.5F, 2F, 1F, 2.5F), PartPose.offsetAndRotation(0F, -1F, -2.5F, 0F, 0F, 0F));
        PartDefinition p5 = p3.addOrReplaceChild("crest", CubeListBuilder.create(), PartPose.offsetAndRotation(0F, -5F, 0.5F, -0.35F, 0F, 0F));
        p5.addOrReplaceChild("plume_0", CubeListBuilder.create().texOffs(58, 13).addBox(-0.5F, -4F, -0.5F, 1F, 4F, 1F), PartPose.offsetAndRotation(-1F, 0F, 0F, 0F, 0F, -0.3F));
        p5.addOrReplaceChild("plume_1", CubeListBuilder.create().texOffs(58, 0).addBox(-0.5F, -6F, -0.5F, 1F, 6F, 1F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        p5.addOrReplaceChild("plume_2", CubeListBuilder.create().texOffs(12, 23).addBox(-0.5F, -4F, -0.5F, 1F, 4F, 1F), PartPose.offsetAndRotation(1F, 0F, 0F, 0F, 0F, 0.3F));
        p2.addOrReplaceChild("left_wing", CubeListBuilder.create().texOffs(26, 0).addBox(0F, 0F, 0F, 1F, 5F, 7F), PartPose.offsetAndRotation(3F, -5.5F, -2F, 0F, 0F, 0F));
        p2.addOrReplaceChild("right_wing", CubeListBuilder.create().texOffs(42, 0).addBox(-1F, 0F, 0F, 1F, 5F, 7F), PartPose.offsetAndRotation(-3F, -5.5F, -2F, 0F, 0F, 0F));
        PartDefinition p11 = p2.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(20, 13).addBox(-2F, -0.5F, 0F, 4F, 1F, 5F), PartPose.offsetAndRotation(0F, -2.5F, 3.5F, 0.3F, 0F, 0F));
        p11.addOrReplaceChild("tail_fan", CubeListBuilder.create().texOffs(38, 13).addBox(-3F, -0.5F, 0F, 6F, 1F, 4F), PartPose.offsetAndRotation(0F, 0F, 5F, 0.2F, 0F, 0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition dictator() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(86, 0).addBox(-1.25F, 0F, -1.25F, 2.5F, 12F, 2.5F).texOffs(40, 49).addBox(-1.75F, 1F, -1.75F, 3.5F, 5F, 3.5F), PartPose.offsetAndRotation(2.4F, 0F, 0F, -0.2F, 0F, 0F));
        PartDefinition p1 = p0.addOrReplaceChild("left_shin", CubeListBuilder.create().texOffs(110, 0).addBox(-1F, 0F, -1F, 2F, 12F, 2F).texOffs(96, 37).addBox(-1.5F, 0F, -2F, 3F, 8F, 3F).texOffs(64, 66).addBox(-0.5F, -1F, -3F, 1F, 2F, 2F), PartPose.offsetAndRotation(0F, 12F, 0F, 0.45F, 0F, 0F));
        p1.addOrReplaceChild("left_foot", CubeListBuilder.create().texOffs(110, 49).addBox(-1.5F, 0F, -4.5F, 3F, 1.5F, 5.5F), PartPose.offsetAndRotation(0F, 12F, 0F, -0.25F, 0F, 0F));
        PartDefinition p3 = root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(98, 0).addBox(-1.25F, 0F, -1.25F, 2.5F, 12F, 2.5F).texOffs(56, 49).addBox(-1.75F, 1F, -1.75F, 3.5F, 5F, 3.5F), PartPose.offsetAndRotation(-2.4F, 0F, 0F, -0.2F, 0F, 0F));
        PartDefinition p4 = p3.addOrReplaceChild("right_shin", CubeListBuilder.create().texOffs(118, 0).addBox(-1F, 0F, -1F, 2F, 12F, 2F).texOffs(108, 37).addBox(-1.5F, 0F, -2F, 3F, 8F, 3F).texOffs(70, 66).addBox(-0.5F, -1F, -3F, 1F, 2F, 2F), PartPose.offsetAndRotation(0F, 12F, 0F, 0.45F, 0F, 0F));
        p4.addOrReplaceChild("right_foot", CubeListBuilder.create().texOffs(0, 58).addBox(-1.5F, 0F, -4.5F, 3F, 1.5F, 5.5F), PartPose.offsetAndRotation(0F, 12F, 0F, -0.25F, 0F, 0F));
        PartDefinition p6 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(64, 58).addBox(-3.5F, -2F, -2F, 7F, 3F, 4F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        PartDefinition p7 = p6.addOrReplaceChild("torso", CubeListBuilder.create().texOffs(72, 49).addBox(-2F, -6F, -1.5F, 4F, 6F, 3F).texOffs(36, 0).addBox(-4F, -15F, -2.75F, 8F, 9F, 5.5F).texOffs(34, 58).addBox(-5F, -16F, -2.5F, 10F, 2F, 5F), PartPose.offsetAndRotation(0F, -2F, 0F, 0.12F, 0F, 0F));
        p7.addOrReplaceChild("coat_tail", CubeListBuilder.create().texOffs(0, 0).addBox(-4.5F, 0F, 0F, 9F, 22F, 1F), PartPose.offsetAndRotation(0F, -15F, 2.75F, 0.12F, 0F, 0F));
        PartDefinition p9 = p7.addOrReplaceChild("neck", CubeListBuilder.create().texOffs(120, 37).addBox(-1F, -4F, -1F, 2F, 4F, 2F).texOffs(86, 58).addBox(-2F, -2F, -1.75F, 4F, 2F, 3.5F), PartPose.offsetAndRotation(0F, -16F, -0.5F, 0.15F, 0F, 0F));
        PartDefinition p10 = p9.addOrReplaceChild("head", CubeListBuilder.create().texOffs(64, 0).addBox(-3F, -10F, -3F, 6F, 10F, 5F).texOffs(32, 72).addBox(-0.5F, 0F, -3F, 1F, 2F, 1F), PartPose.offsetAndRotation(0F, -4F, 0F, 0F, 0F, 0F));
        PartDefinition p11 = p10.addOrReplaceChild("crown", CubeListBuilder.create(), PartPose.offsetAndRotation(0F, -10F, 0F, 0F, 0F, 0F));
        PartDefinition p12 = p11.addOrReplaceChild("left_horn", CubeListBuilder.create().texOffs(114, 58).addBox(-1F, -4F, -1F, 2F, 4F, 2F), PartPose.offsetAndRotation(2.2F, 0F, -0.5F, -0.2F, 0F, 0.75F));
        PartDefinition p13 = p12.addOrReplaceChild("left_horn_mid", CubeListBuilder.create().texOffs(0, 66).addBox(-0.75F, -4F, -0.75F, 1.5F, 4F, 1.5F), PartPose.offsetAndRotation(0F, -4F, 0F, -0.35F, 0F, -0.7F));
        p13.addOrReplaceChild("left_horn_tip", CubeListBuilder.create().texOffs(76, 66).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F), PartPose.offsetAndRotation(0F, -4F, 0F, -0.6F, 0F, -0.6F));
        PartDefinition p15 = p11.addOrReplaceChild("right_horn", CubeListBuilder.create().texOffs(8, 66).addBox(-1F, -4F, -1F, 2F, 4F, 2F), PartPose.offsetAndRotation(-2.2F, 0F, -0.5F, -0.2F, 0F, -0.75F));
        PartDefinition p16 = p15.addOrReplaceChild("right_horn_mid", CubeListBuilder.create().texOffs(16, 66).addBox(-0.75F, -4F, -0.75F, 1.5F, 4F, 1.5F), PartPose.offsetAndRotation(0F, -4F, 0F, -0.35F, 0F, 0.7F));
        p16.addOrReplaceChild("right_horn_tip", CubeListBuilder.create().texOffs(80, 66).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F), PartPose.offsetAndRotation(0F, -4F, 0F, -0.6F, 0F, 0.6F));
        p10.addOrReplaceChild("left_ear_upper", CubeListBuilder.create().texOffs(108, 66).addBox(0F, -1F, -0.25F, 5F, 2F, 0.5F), PartPose.offsetAndRotation(3F, -7.5F, 0F, 0F, 0.35F, -0.45F));
        p10.addOrReplaceChild("left_ear_lower", CubeListBuilder.create().texOffs(12, 72).addBox(0F, -1F, -0.25F, 4F, 2F, 0.5F), PartPose.offsetAndRotation(3F, -4.5F, 0F, 0F, 0.6F, 0.25F));
        p10.addOrReplaceChild("right_ear_upper", CubeListBuilder.create().texOffs(0, 72).addBox(-5F, -1F, -0.25F, 5F, 2F, 0.5F), PartPose.offsetAndRotation(-3F, -7.5F, 0F, 0F, -0.35F, 0.45F));
        p10.addOrReplaceChild("right_ear_lower", CubeListBuilder.create().texOffs(22, 72).addBox(-4F, -1F, -0.25F, 4F, 2F, 0.5F), PartPose.offsetAndRotation(-3F, -4.5F, 0F, 0F, -0.6F, -0.25F));
        PartDefinition p22 = p7.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(0, 23).addBox(-1F, -1F, -1F, 2F, 12F, 2F).texOffs(0, 49).addBox(-2.5F, -2.5F, -2.5F, 5F, 4F, 5F).texOffs(84, 66).addBox(1F, -5F, -1.5F, 1F, 3F, 1F).texOffs(88, 66).addBox(1F, -5F, 0.5F, 1F, 3F, 1F), PartPose.offsetAndRotation(5.5F, -14F, 0F, 0F, 0F, -0.08F));
        PartDefinition p23 = p22.addOrReplaceChild("left_forearm", CubeListBuilder.create().texOffs(116, 23).addBox(-1F, 0F, -1F, 2F, 10F, 2F).texOffs(86, 49).addBox(-1.5F, 3F, -1.5F, 3F, 6F, 3F), PartPose.offsetAndRotation(0F, 11F, 0F, -0.15F, 0F, 0F));
        PartDefinition p24 = p23.addOrReplaceChild("left_hand", CubeListBuilder.create().texOffs(24, 66).addBox(-1.5F, 0F, -1.5F, 3F, 2F, 3F).texOffs(48, 66).addBox(-1.5F, 2F, -1.5F, 1F, 4F, 1F).texOffs(92, 66).addBox(-0.5F, 2F, -0.5F, 1F, 3F, 1F).texOffs(52, 66).addBox(0.5F, 2F, -1.5F, 1F, 4F, 1F), PartPose.offsetAndRotation(0F, 10F, 0F, 0F, 0F, 0F));
        p24.addOrReplaceChild("left_strings", CubeListBuilder.create().texOffs(24, 0).addBox(0F, 0F, -1.5F, 0F, 16F, 3F), PartPose.offsetAndRotation(0F, 2F, 0F, 0F, 0F, 0F));
        PartDefinition p26 = p7.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(8, 23).addBox(-1F, -1F, -1F, 2F, 12F, 2F).texOffs(20, 49).addBox(-2.5F, -2.5F, -2.5F, 5F, 4F, 5F).texOffs(96, 66).addBox(-2F, -5F, -1.5F, 1F, 3F, 1F).texOffs(100, 66).addBox(-2F, -5F, 0.5F, 1F, 3F, 1F), PartPose.offsetAndRotation(-5.5F, -14F, 0F, 0F, 0F, 0.08F));
        PartDefinition p27 = p26.addOrReplaceChild("right_forearm", CubeListBuilder.create().texOffs(0, 37).addBox(-1F, 0F, -1F, 2F, 10F, 2F).texOffs(98, 49).addBox(-1.5F, 3F, -1.5F, 3F, 6F, 3F), PartPose.offsetAndRotation(0F, 11F, 0F, -0.15F, 0F, 0F));
        PartDefinition p28 = p27.addOrReplaceChild("right_hand", CubeListBuilder.create().texOffs(36, 66).addBox(-1.5F, 0F, -1.5F, 3F, 2F, 3F).texOffs(56, 66).addBox(-1.5F, 2F, -1.5F, 1F, 4F, 1F).texOffs(104, 66).addBox(-0.5F, 2F, -0.5F, 1F, 3F, 1F).texOffs(60, 66).addBox(0.5F, 2F, -1.5F, 1F, 4F, 1F), PartPose.offsetAndRotation(0F, 10F, 0F, 0F, 0F, 0F));
        PartDefinition p29 = p28.addOrReplaceChild("baton", CubeListBuilder.create().texOffs(20, 0).addBox(-0.5F, -8F, -0.5F, 1F, 22F, 1F).texOffs(120, 66).addBox(-1F, 13F, -1F, 2F, 1F, 2F), PartPose.offsetAndRotation(0F, 2F, 0F, 1.35F, 0F, 0F));
        PartDefinition p30 = p29.addOrReplaceChild("staff_skull", CubeListBuilder.create().texOffs(18, 58).addBox(-2F, 0F, -2F, 4F, 4F, 4F).texOffs(102, 58).addBox(-1.25F, 5.5F, -1.25F, 2.5F, 2.5F, 2.5F), PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, 0F));
        p30.addOrReplaceChild("staff_prong_l", CubeListBuilder.create().texOffs(124, 23).addBox(-0.5F, 0F, -0.5F, 1F, 5F, 1F).texOffs(36, 72).addBox(-1F, 4.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(1.7F, 3.5F, 0F, 0F, 0F, -0.35F));
        p30.addOrReplaceChild("staff_prong_r", CubeListBuilder.create().texOffs(122, 58).addBox(-0.5F, 0F, -0.5F, 1F, 5F, 1F).texOffs(40, 72).addBox(0F, 4.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(-1.7F, 3.5F, 0F, 0F, 0F, 0.35F));
        p28.addOrReplaceChild("right_strings", CubeListBuilder.create().texOffs(30, 0).addBox(0F, 0F, -1.5F, 0F, 16F, 3F), PartPose.offsetAndRotation(0F, 2F, 0F, 0F, 0F, 0F));
        PartDefinition p34 = p7.addOrReplaceChild("left_crane_wing", CubeListBuilder.create().texOffs(8, 37).addBox(0F, -0.5F, 0F, 12F, 1F, 10F), PartPose.offsetAndRotation(2.5F, -14.5F, 3F, 0.2F, -0.5F, 0F));
        p34.addOrReplaceChild("left_crane_wing_tip", CubeListBuilder.create().texOffs(16, 23).addBox(0F, -0.5F, 0F, 14F, 1F, 11F), PartPose.offsetAndRotation(12F, 0F, 0F, 0F, 0F, 0F));
        PartDefinition p36 = p7.addOrReplaceChild("right_crane_wing", CubeListBuilder.create().texOffs(52, 37).addBox(-12F, -0.5F, 0F, 12F, 1F, 10F), PartPose.offsetAndRotation(-2.5F, -14.5F, 3F, 0.2F, 0.5F, 0F));
        p36.addOrReplaceChild("right_crane_wing_tip", CubeListBuilder.create().texOffs(66, 23).addBox(-14F, -0.5F, 0F, 14F, 1F, 11F), PartPose.offsetAndRotation(-12F, 0F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 128, 192);
    }

    public static LayerDefinition strummer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("spider", CubeListBuilder.create().texOffs(58, 0).addBox(-5F, -3F, -5F, 10F, 6F, 10F), PartPose.offsetAndRotation(0F, 17.5F, 0F, 0F, 0F, 0F));
        PartDefinition p1 = p0.addOrReplaceChild("spider_head", CubeListBuilder.create().texOffs(12, 25).addBox(-4F, -2.5F, -5F, 8F, 5F, 5F), PartPose.offsetAndRotation(0F, 0F, -5F, 0F, 0F, 0F));
        p1.addOrReplaceChild("left_fang", CubeListBuilder.create().texOffs(24, 37).addBox(-0.75F, 0F, -0.75F, 1.5F, 3.5F, 1.5F), PartPose.offsetAndRotation(1.5F, 2F, -5F, 0F, 0F, 0F));
        p1.addOrReplaceChild("right_fang", CubeListBuilder.create().texOffs(32, 37).addBox(-0.75F, 0F, -0.75F, 1.5F, 3.5F, 1.5F), PartPose.offsetAndRotation(-1.5F, 2F, -5F, 0F, 0F, 0F));
        PartDefinition p4 = p0.addOrReplaceChild("abdomen", CubeListBuilder.create().texOffs(0, 0).addBox(-7F, -7F, 0F, 14F, 10F, 15F).texOffs(44, 37).addBox(-1.5F, -2F, 15F, 3F, 3F, 2F), PartPose.offsetAndRotation(0F, -1F, 4.5F, -0.15F, 0F, 0F));
        p4.addOrReplaceChild("left_abdomen_tendril", CubeListBuilder.create().texOffs(82, 25).addBox(-1F, -8F, 0F, 2F, 8F, 0F), PartPose.offsetAndRotation(4F, -7F, 6F, -0.3F, 0F, 0.5F));
        p4.addOrReplaceChild("right_abdomen_tendril", CubeListBuilder.create().texOffs(86, 25).addBox(-1F, -8F, 0F, 2F, 8F, 0F), PartPose.offsetAndRotation(-4F, -7F, 6F, -0.3F, 0F, -0.5F));
        PartDefinition p7 = p0.addOrReplaceChild("left_leg_0", CubeListBuilder.create().texOffs(102, 43).addBox(0F, -0.75F, -0.75F, 10F, 1.5F, 1.5F), PartPose.offsetAndRotation(4.5F, 0F, -3.5F, 0F, 0.55F, -0.75F));
        p7.addOrReplaceChild("left_shin_0", CubeListBuilder.create().texOffs(54, 37).addBox(0F, -0.6F, -0.6F, 15F, 1.2F, 1.2F), PartPose.offsetAndRotation(10F, 0F, 0F, 0F, 0F, 1.75F));
        PartDefinition p9 = p0.addOrReplaceChild("right_leg_0", CubeListBuilder.create().texOffs(102, 47).addBox(-10F, -0.75F, -0.75F, 10F, 1.5F, 1.5F), PartPose.offsetAndRotation(-4.5F, 0F, -3.5F, 0F, -0.55F, 0.75F));
        p9.addOrReplaceChild("right_shin_0", CubeListBuilder.create().texOffs(88, 37).addBox(-15F, -0.6F, -0.6F, 15F, 1.2F, 1.2F), PartPose.offsetAndRotation(-10F, 0F, 0F, 0F, 0F, -1.75F));
        PartDefinition p11 = p0.addOrReplaceChild("left_leg_1", CubeListBuilder.create().texOffs(0, 51).addBox(0F, -0.75F, -0.75F, 10F, 1.5F, 1.5F), PartPose.offsetAndRotation(4.5F, 0F, -1.2F, 0F, 0.2F, -0.75F));
        p11.addOrReplaceChild("left_shin_1", CubeListBuilder.create().texOffs(0, 43).addBox(0F, -0.6F, -0.6F, 15F, 1.2F, 1.2F), PartPose.offsetAndRotation(10F, 0F, 0F, 0F, 0F, 1.75F));
        PartDefinition p13 = p0.addOrReplaceChild("right_leg_1", CubeListBuilder.create().texOffs(24, 51).addBox(-10F, -0.75F, -0.75F, 10F, 1.5F, 1.5F), PartPose.offsetAndRotation(-4.5F, 0F, -1.2F, 0F, -0.2F, 0.75F));
        p13.addOrReplaceChild("right_shin_1", CubeListBuilder.create().texOffs(34, 43).addBox(-15F, -0.6F, -0.6F, 15F, 1.2F, 1.2F), PartPose.offsetAndRotation(-10F, 0F, 0F, 0F, 0F, -1.75F));
        PartDefinition p15 = p0.addOrReplaceChild("left_leg_2", CubeListBuilder.create().texOffs(48, 51).addBox(0F, -0.75F, -0.75F, 10F, 1.5F, 1.5F), PartPose.offsetAndRotation(4.5F, 0F, 1.2F, 0F, -0.2F, -0.75F));
        p15.addOrReplaceChild("left_shin_2", CubeListBuilder.create().texOffs(68, 43).addBox(0F, -0.6F, -0.6F, 15F, 1.2F, 1.2F), PartPose.offsetAndRotation(10F, 0F, 0F, 0F, 0F, 1.75F));
        PartDefinition p17 = p0.addOrReplaceChild("right_leg_2", CubeListBuilder.create().texOffs(72, 51).addBox(-10F, -0.75F, -0.75F, 10F, 1.5F, 1.5F), PartPose.offsetAndRotation(-4.5F, 0F, 1.2F, 0F, 0.2F, 0.75F));
        p17.addOrReplaceChild("right_shin_2", CubeListBuilder.create().texOffs(0, 47).addBox(-15F, -0.6F, -0.6F, 15F, 1.2F, 1.2F), PartPose.offsetAndRotation(-10F, 0F, 0F, 0F, 0F, -1.75F));
        PartDefinition p19 = p0.addOrReplaceChild("left_leg_3", CubeListBuilder.create().texOffs(96, 51).addBox(0F, -0.75F, -0.75F, 10F, 1.5F, 1.5F), PartPose.offsetAndRotation(4.5F, 0F, 3.5F, 0F, -0.55F, -0.75F));
        p19.addOrReplaceChild("left_shin_3", CubeListBuilder.create().texOffs(34, 47).addBox(0F, -0.6F, -0.6F, 15F, 1.2F, 1.2F), PartPose.offsetAndRotation(10F, 0F, 0F, 0F, 0F, 1.75F));
        PartDefinition p21 = p0.addOrReplaceChild("right_leg_3", CubeListBuilder.create().texOffs(0, 55).addBox(-10F, -0.75F, -0.75F, 10F, 1.5F, 1.5F), PartPose.offsetAndRotation(-4.5F, 0F, 3.5F, 0F, 0.55F, 0.75F));
        p21.addOrReplaceChild("right_shin_3", CubeListBuilder.create().texOffs(68, 47).addBox(-15F, -0.6F, -0.6F, 15F, 1.2F, 1.2F), PartPose.offsetAndRotation(-10F, 0F, 0F, 0F, 0F, -1.75F));
        PartDefinition p23 = p0.addOrReplaceChild("mantis", CubeListBuilder.create().texOffs(98, 0).addBox(-2F, -11F, -2F, 4F, 11F, 4F).texOffs(38, 25).addBox(-2.5F, -4F, -2.5F, 5F, 4F, 5F), PartPose.offsetAndRotation(0F, -3F, -1.5F, 0.08F, 0F, 0F));
        p23.addOrReplaceChild("left_mantis_wing", CubeListBuilder.create().texOffs(0, 25).addBox(-1.5F, 0F, 0F, 3F, 12F, 0F), PartPose.offsetAndRotation(1.5F, -9F, 2F, 0.35F, 0.2F, 0.12F));
        p23.addOrReplaceChild("right_mantis_wing", CubeListBuilder.create().texOffs(6, 25).addBox(-1.5F, 0F, 0F, 3F, 12F, 0F), PartPose.offsetAndRotation(-1.5F, -9F, 2F, 0.35F, -0.2F, -0.12F));
        PartDefinition p26 = p23.addOrReplaceChild("mantis_head", CubeListBuilder.create().texOffs(90, 25).addBox(-2.5F, -3.5F, -2.5F, 5F, 3.5F, 3F), PartPose.offsetAndRotation(0F, -11F, -0.5F, 0F, 0F, 0F));
        p26.addOrReplaceChild("left_mantis_eye", CubeListBuilder.create().texOffs(0, 37).addBox(-1.25F, -1.5F, -1.5F, 2.5F, 3F, 3F), PartPose.offsetAndRotation(2.5F, -3F, -1F, 0F, 0F, 0F));
        p26.addOrReplaceChild("left_antenna", CubeListBuilder.create().texOffs(74, 25).addBox(-1F, -9F, 0F, 2F, 9F, 0F), PartPose.offsetAndRotation(0.8F, -3.5F, -2F, -0.6F, 0F, 0.25F));
        p26.addOrReplaceChild("right_mantis_eye", CubeListBuilder.create().texOffs(12, 37).addBox(-1.25F, -1.5F, -1.5F, 2.5F, 3F, 3F), PartPose.offsetAndRotation(-2.5F, -3F, -1F, 0F, 0F, 0F));
        p26.addOrReplaceChild("right_antenna", CubeListBuilder.create().texOffs(78, 25).addBox(-1F, -9F, 0F, 2F, 9F, 0F), PartPose.offsetAndRotation(-0.8F, -3.5F, -2F, -0.6F, 0F, -0.25F));
        PartDefinition p31 = p23.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(106, 25).addBox(-0.75F, 0F, -0.75F, 1.5F, 5F, 1.5F), PartPose.offsetAndRotation(2.2F, -9.5F, -1.5F, -0.7F, 0F, -0.15F));
        PartDefinition p32 = p31.addOrReplaceChild("left_femur", CubeListBuilder.create().texOffs(58, 25).addBox(-0.75F, 0F, -0.75F, 1.5F, 7F, 1.5F).texOffs(24, 55).addBox(-0.25F, 1.5F, -1.5F, 0.5F, 1F, 0.75F).texOffs(28, 55).addBox(-0.25F, 3.5F, -1.5F, 0.5F, 1F, 0.75F).texOffs(32, 55).addBox(-0.25F, 5.5F, -1.5F, 0.5F, 1F, 0.75F), PartPose.offsetAndRotation(0F, 5F, 0F, -1.4F, 0F, 0F));
        PartDefinition p33 = p32.addOrReplaceChild("left_hand", CubeListBuilder.create().texOffs(122, 25).addBox(-0.5F, 0F, -0.5F, 1F, 5F, 1F).texOffs(122, 37).addBox(-0.5F, 4.5F, -1.5F, 1F, 1F, 1.5F), PartPose.offsetAndRotation(0F, 7F, 0F, 2.5F, 0F, 0F));
        p33.addOrReplaceChild("left_strings", CubeListBuilder.create().texOffs(114, 0).addBox(0F, 0F, -1.5F, 0F, 12F, 3F), PartPose.offsetAndRotation(0F, 4.5F, 0F, -1.1F, 0F, 0F));
        PartDefinition p35 = p23.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(114, 25).addBox(-0.75F, 0F, -0.75F, 1.5F, 5F, 1.5F), PartPose.offsetAndRotation(-2.2F, -9.5F, -1.5F, -0.7F, 0F, 0.15F));
        PartDefinition p36 = p35.addOrReplaceChild("right_femur", CubeListBuilder.create().texOffs(66, 25).addBox(-0.75F, 0F, -0.75F, 1.5F, 7F, 1.5F).texOffs(36, 55).addBox(-0.25F, 1.5F, -1.5F, 0.5F, 1F, 0.75F).texOffs(40, 55).addBox(-0.25F, 3.5F, -1.5F, 0.5F, 1F, 0.75F).texOffs(44, 55).addBox(-0.25F, 5.5F, -1.5F, 0.5F, 1F, 0.75F), PartPose.offsetAndRotation(0F, 5F, 0F, -1.4F, 0F, 0F));
        PartDefinition p37 = p36.addOrReplaceChild("right_hand", CubeListBuilder.create().texOffs(40, 37).addBox(-0.5F, 0F, -0.5F, 1F, 5F, 1F).texOffs(120, 51).addBox(-0.5F, 4.5F, -1.5F, 1F, 1F, 1.5F), PartPose.offsetAndRotation(0F, 7F, 0F, 2.5F, 0F, 0F));
        p37.addOrReplaceChild("right_strings", CubeListBuilder.create().texOffs(120, 0).addBox(0F, 0F, -1.5F, 0F, 12F, 3F), PartPose.offsetAndRotation(0F, 4.5F, 0F, -1.1F, 0F, 0F));
        return LayerDefinition.create(mesh, 128, 160);
    }

    public static LayerDefinition strumling() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(42, 0).addBox(-3.5F, -2.5F, -3.5F, 7F, 5F, 7F), PartPose.offsetAndRotation(0F, 16F, 0F, 0F, 0F, 0F));
        PartDefinition p1 = p0.addOrReplaceChild("head", CubeListBuilder.create().texOffs(70, 0).addBox(-3F, -2.5F, -5F, 6F, 5F, 5F).texOffs(4, 41).addBox(-3.2F, -3F, -5.2F, 6.4F, 1F, 2F), PartPose.offsetAndRotation(0F, -0.3F, -3.5F, 0F, 0F, 0F));
        p1.addOrReplaceChild("left_fang", CubeListBuilder.create().texOffs(100, 19).addBox(-0.8F, 0F, -0.8F, 1.6F, 2.4F, 1.6F).texOffs(114, 37).addBox(-0.5F, 2.2F, -0.9F, 1F, 2.2F, 1F).texOffs(22, 41).addBox(-0.35F, 4.2F, -1.6F, 0.7F, 0.7F, 1.2F), PartPose.offsetAndRotation(1.2F, 1.6F, -4.6F, -0.25F, 0F, 0F));
        p1.addOrReplaceChild("left_palp", CubeListBuilder.create().texOffs(80, 19).addBox(-0.45F, -0.45F, -3.2F, 0.9F, 0.9F, 3.2F).texOffs(28, 41).addBox(-0.55F, -0.55F, -3.9F, 1.1F, 1.1F, 0.9F), PartPose.offsetAndRotation(2.4F, 1.2F, -4.4F, 0.5F, 0.25F, 0F));
        p1.addOrReplaceChild("right_fang", CubeListBuilder.create().texOffs(108, 19).addBox(-0.8F, 0F, -0.8F, 1.6F, 2.4F, 1.6F).texOffs(118, 37).addBox(-0.5F, 2.2F, -0.9F, 1F, 2.2F, 1F).texOffs(34, 41).addBox(-0.35F, 4.2F, -1.6F, 0.7F, 0.7F, 1.2F), PartPose.offsetAndRotation(-1.2F, 1.6F, -4.6F, -0.25F, 0F, 0F));
        p1.addOrReplaceChild("right_palp", CubeListBuilder.create().texOffs(90, 19).addBox(-0.45F, -0.45F, -3.2F, 0.9F, 0.9F, 3.2F).texOffs(40, 41).addBox(-0.55F, -0.55F, -3.9F, 1.1F, 1.1F, 0.9F), PartPose.offsetAndRotation(-2.4F, 1.2F, -4.4F, 0.5F, -0.25F, 0F));
        PartDefinition p6 = p0.addOrReplaceChild("abdomen", CubeListBuilder.create().texOffs(0, 0).addBox(-5F, -5F, 0F, 10F, 8F, 11F).texOffs(92, 0).addBox(-4.5F, -5.9F, 0.6F, 9F, 1.4F, 3.4F).texOffs(0, 19).addBox(-4.2F, -5.9F, 4F, 8.4F, 1.4F, 3.4F).texOffs(26, 19).addBox(-3.6F, -5.9F, 7.4F, 7.2F, 1.4F, 3.4F).texOffs(112, 25).addBox(2.3F, -6.1F, 3.2F, 1.8F, 1.4F, 1.8F).texOffs(120, 25).addBox(-4.1F, -6.1F, 3.2F, 1.8F, 1.4F, 1.8F).texOffs(112, 29).addBox(2.3F, -6.1F, 6.6F, 1.8F, 1.4F, 1.8F).texOffs(120, 29).addBox(-4.1F, -6.1F, 6.6F, 1.8F, 1.4F, 1.8F).texOffs(118, 0).addBox(5F, -3.4F, 2F, 1.4F, 2.2F, 2.4F).texOffs(50, 19).addBox(5F, -2.8F, 6.5F, 1.4F, 2.2F, 2.4F).texOffs(60, 19).addBox(-6.4F, -3.4F, 2F, 1.4F, 2.2F, 2.4F).texOffs(70, 19).addBox(-6.4F, -2.8F, 6.5F, 1.4F, 2.2F, 2.4F).texOffs(116, 19).addBox(-1.2F, -1.6F, 10.6F, 2.4F, 2F, 1.4F), PartPose.offsetAndRotation(0F, -0.8F, 3.2F, -0.28F, 0F, 0F));
        p6.addOrReplaceChild("left_tendril", CubeListBuilder.create().texOffs(122, 37).addBox(-1F, -4F, 0F, 2F, 4F, 0F), PartPose.offsetAndRotation(2.2F, -6F, 9F, -0.6F, 0F, 0.5F));
        p6.addOrReplaceChild("right_tendril", CubeListBuilder.create().texOffs(0, 41).addBox(-1F, -4F, 0F, 2F, 4F, 0F), PartPose.offsetAndRotation(-2.2F, -6F, 9F, -0.6F, 0F, -0.5F));
        PartDefinition p9 = p0.addOrReplaceChild("left_leg_0", CubeListBuilder.create().texOffs(0, 33).addBox(0F, -0.7F, -0.7F, 9F, 1.4F, 1.4F).texOffs(110, 33).addBox(8.2F, -0.9F, -0.9F, 1.6F, 1.8F, 1.8F), PartPose.offsetAndRotation(3.2F, 0F, -2.6F, 0F, 0.62F, -0.8F));
        PartDefinition p10 = p9.addOrReplaceChild("left_tibia_0", CubeListBuilder.create().texOffs(0, 25).addBox(0F, -0.55F, -0.55F, 12F, 1.1F, 1.1F), PartPose.offsetAndRotation(9F, 0F, 0F, 0F, 0F, 1.7F));
        p10.addOrReplaceChild("left_tarsus_0", CubeListBuilder.create().texOffs(46, 41).addBox(0F, -0.4F, -0.4F, 5F, 0.8F, 0.8F).texOffs(118, 41).addBox(5F, -0.3F, -0.3F, 0.9F, 0.6F, 0.6F), PartPose.offsetAndRotation(12F, 0F, 0F, 0F, 0F, 0.5F));
        PartDefinition p12 = p0.addOrReplaceChild("right_leg_0", CubeListBuilder.create().texOffs(22, 33).addBox(-9F, -0.7F, -0.7F, 9F, 1.4F, 1.4F).texOffs(118, 33).addBox(-9.8F, -0.9F, -0.9F, 1.6F, 1.8F, 1.8F), PartPose.offsetAndRotation(-3.2F, 0F, -2.6F, 0F, -0.62F, 0.8F));
        PartDefinition p13 = p12.addOrReplaceChild("right_tibia_0", CubeListBuilder.create().texOffs(28, 25).addBox(-12F, -0.55F, -0.55F, 12F, 1.1F, 1.1F), PartPose.offsetAndRotation(-9F, 0F, 0F, 0F, 0F, -1.7F));
        p13.addOrReplaceChild("right_tarsus_0", CubeListBuilder.create().texOffs(58, 41).addBox(-5F, -0.4F, -0.4F, 5F, 0.8F, 0.8F).texOffs(122, 41).addBox(-5.9F, -0.3F, -0.3F, 0.9F, 0.6F, 0.6F), PartPose.offsetAndRotation(-12F, 0F, 0F, 0F, 0F, -0.5F));
        PartDefinition p15 = p0.addOrReplaceChild("left_leg_1", CubeListBuilder.create().texOffs(44, 33).addBox(0F, -0.7F, -0.7F, 9F, 1.4F, 1.4F).texOffs(66, 37).addBox(8.2F, -0.9F, -0.9F, 1.6F, 1.8F, 1.8F), PartPose.offsetAndRotation(3.2F, 0F, -0.9F, 0F, 0.22F, -0.8F));
        PartDefinition p16 = p15.addOrReplaceChild("left_tibia_1", CubeListBuilder.create().texOffs(56, 25).addBox(0F, -0.55F, -0.55F, 12F, 1.1F, 1.1F), PartPose.offsetAndRotation(9F, 0F, 0F, 0F, 0F, 1.7F));
        p16.addOrReplaceChild("left_tarsus_1", CubeListBuilder.create().texOffs(70, 41).addBox(0F, -0.4F, -0.4F, 5F, 0.8F, 0.8F).texOffs(24, 45).addBox(5F, -0.3F, -0.3F, 0.9F, 0.6F, 0.6F), PartPose.offsetAndRotation(12F, 0F, 0F, 0F, 0F, 0.5F));
        PartDefinition p18 = p0.addOrReplaceChild("right_leg_1", CubeListBuilder.create().texOffs(66, 33).addBox(-9F, -0.7F, -0.7F, 9F, 1.4F, 1.4F).texOffs(74, 37).addBox(-9.8F, -0.9F, -0.9F, 1.6F, 1.8F, 1.8F), PartPose.offsetAndRotation(-3.2F, 0F, -0.9F, 0F, -0.22F, 0.8F));
        PartDefinition p19 = p18.addOrReplaceChild("right_tibia_1", CubeListBuilder.create().texOffs(84, 25).addBox(-12F, -0.55F, -0.55F, 12F, 1.1F, 1.1F), PartPose.offsetAndRotation(-9F, 0F, 0F, 0F, 0F, -1.7F));
        p19.addOrReplaceChild("right_tarsus_1", CubeListBuilder.create().texOffs(82, 41).addBox(-5F, -0.4F, -0.4F, 5F, 0.8F, 0.8F).texOffs(28, 45).addBox(-5.9F, -0.3F, -0.3F, 0.9F, 0.6F, 0.6F), PartPose.offsetAndRotation(-12F, 0F, 0F, 0F, 0F, -0.5F));
        PartDefinition p21 = p0.addOrReplaceChild("left_leg_2", CubeListBuilder.create().texOffs(88, 33).addBox(0F, -0.7F, -0.7F, 9F, 1.4F, 1.4F).texOffs(82, 37).addBox(8.2F, -0.9F, -0.9F, 1.6F, 1.8F, 1.8F), PartPose.offsetAndRotation(3.2F, 0F, 0.9F, 0F, -0.22F, -0.8F));
        PartDefinition p22 = p21.addOrReplaceChild("left_tibia_2", CubeListBuilder.create().texOffs(0, 29).addBox(0F, -0.55F, -0.55F, 12F, 1.1F, 1.1F), PartPose.offsetAndRotation(9F, 0F, 0F, 0F, 0F, 1.7F));
        p22.addOrReplaceChild("left_tarsus_2", CubeListBuilder.create().texOffs(94, 41).addBox(0F, -0.4F, -0.4F, 5F, 0.8F, 0.8F).texOffs(32, 45).addBox(5F, -0.3F, -0.3F, 0.9F, 0.6F, 0.6F), PartPose.offsetAndRotation(12F, 0F, 0F, 0F, 0F, 0.5F));
        PartDefinition p24 = p0.addOrReplaceChild("right_leg_2", CubeListBuilder.create().texOffs(0, 37).addBox(-9F, -0.7F, -0.7F, 9F, 1.4F, 1.4F).texOffs(90, 37).addBox(-9.8F, -0.9F, -0.9F, 1.6F, 1.8F, 1.8F), PartPose.offsetAndRotation(-3.2F, 0F, 0.9F, 0F, 0.22F, 0.8F));
        PartDefinition p25 = p24.addOrReplaceChild("right_tibia_2", CubeListBuilder.create().texOffs(28, 29).addBox(-12F, -0.55F, -0.55F, 12F, 1.1F, 1.1F), PartPose.offsetAndRotation(-9F, 0F, 0F, 0F, 0F, -1.7F));
        p25.addOrReplaceChild("right_tarsus_2", CubeListBuilder.create().texOffs(106, 41).addBox(-5F, -0.4F, -0.4F, 5F, 0.8F, 0.8F).texOffs(36, 45).addBox(-5.9F, -0.3F, -0.3F, 0.9F, 0.6F, 0.6F), PartPose.offsetAndRotation(-12F, 0F, 0F, 0F, 0F, -0.5F));
        PartDefinition p27 = p0.addOrReplaceChild("left_leg_3", CubeListBuilder.create().texOffs(22, 37).addBox(0F, -0.7F, -0.7F, 9F, 1.4F, 1.4F).texOffs(98, 37).addBox(8.2F, -0.9F, -0.9F, 1.6F, 1.8F, 1.8F), PartPose.offsetAndRotation(3.2F, 0F, 2.6F, 0F, -0.62F, -0.8F));
        PartDefinition p28 = p27.addOrReplaceChild("left_tibia_3", CubeListBuilder.create().texOffs(56, 29).addBox(0F, -0.55F, -0.55F, 12F, 1.1F, 1.1F), PartPose.offsetAndRotation(9F, 0F, 0F, 0F, 0F, 1.7F));
        p28.addOrReplaceChild("left_tarsus_3", CubeListBuilder.create().texOffs(0, 45).addBox(0F, -0.4F, -0.4F, 5F, 0.8F, 0.8F).texOffs(40, 45).addBox(5F, -0.3F, -0.3F, 0.9F, 0.6F, 0.6F), PartPose.offsetAndRotation(12F, 0F, 0F, 0F, 0F, 0.5F));
        PartDefinition p30 = p0.addOrReplaceChild("right_leg_3", CubeListBuilder.create().texOffs(44, 37).addBox(-9F, -0.7F, -0.7F, 9F, 1.4F, 1.4F).texOffs(106, 37).addBox(-9.8F, -0.9F, -0.9F, 1.6F, 1.8F, 1.8F), PartPose.offsetAndRotation(-3.2F, 0F, 2.6F, 0F, 0.62F, 0.8F));
        PartDefinition p31 = p30.addOrReplaceChild("right_tibia_3", CubeListBuilder.create().texOffs(84, 29).addBox(-12F, -0.55F, -0.55F, 12F, 1.1F, 1.1F), PartPose.offsetAndRotation(-9F, 0F, 0F, 0F, 0F, -1.7F));
        p31.addOrReplaceChild("right_tarsus_3", CubeListBuilder.create().texOffs(12, 45).addBox(-5F, -0.4F, -0.4F, 5F, 0.8F, 0.8F).texOffs(44, 45).addBox(-5.9F, -0.3F, -0.3F, 0.9F, 0.6F, 0.6F), PartPose.offsetAndRotation(-12F, 0F, 0F, 0F, 0F, -0.5F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    public static LayerDefinition conductor_mask() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("mask", CubeListBuilder.create().texOffs(0, 0).addBox(-5F, -14F, -1F, 10F, 14F, 2F).texOffs(0, 16).addBox(-4F, -1F, -1.5F, 8F, 2F, 2F), PartPose.offsetAndRotation(0F, 12F, 0F, 0F, 0F, 0F));
        PartDefinition p1 = p0.addOrReplaceChild("left_horn", CubeListBuilder.create().texOffs(32, 0).addBox(-1F, -4F, -1F, 2F, 4F, 2F), PartPose.offsetAndRotation(3.5F, -13F, 0F, 0F, 0F, 0.6F));
        p1.addOrReplaceChild("left_horn_tip", CubeListBuilder.create().texOffs(48, 0).addBox(-0.5F, -4F, -0.5F, 1F, 4F, 1F), PartPose.offsetAndRotation(0F, -4F, 0F, 0F, 0F, -0.7F));
        p0.addOrReplaceChild("left_ribbon", CubeListBuilder.create().texOffs(24, 0).addBox(-1F, 0F, 0F, 2F, 14F, 0F), PartPose.offsetAndRotation(5F, -8F, 0.5F, 0.2F, 0F, -0.25F));
        PartDefinition p4 = p0.addOrReplaceChild("right_horn", CubeListBuilder.create().texOffs(40, 0).addBox(-1F, -4F, -1F, 2F, 4F, 2F), PartPose.offsetAndRotation(-3.5F, -13F, 0F, 0F, 0F, -0.6F));
        p4.addOrReplaceChild("right_horn_tip", CubeListBuilder.create().texOffs(52, 0).addBox(-0.5F, -4F, -0.5F, 1F, 4F, 1F), PartPose.offsetAndRotation(0F, -4F, 0F, 0F, 0F, 0.7F));
        p0.addOrReplaceChild("right_ribbon", CubeListBuilder.create().texOffs(28, 0).addBox(-1F, 0F, 0F, 2F, 14F, 0F), PartPose.offsetAndRotation(-5F, -8F, 0.5F, 0.2F, 0F, 0.25F));
        p0.addOrReplaceChild("crown", CubeListBuilder.create().texOffs(20, 16).addBox(-3.5F, -2F, -0.5F, 1F, 2F, 1F).texOffs(56, 0).addBox(-1.5F, -3.5F, -0.5F, 1F, 3.5F, 1F).texOffs(60, 0).addBox(0.5F, -3.5F, -0.5F, 1F, 3.5F, 1F).texOffs(24, 16).addBox(2.5F, -2F, -0.5F, 1F, 2F, 1F), PartPose.offsetAndRotation(0F, -14F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition thumper() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 32).addBox(-10F, 1F, -12F, 20F, 3F, 24F).texOffs(0, 0).addBox(-12F, -3F, -14F, 24F, 4F, 28F).texOffs(104, 0).addBox(-10F, -8F, -12F, 20F, 5F, 24F).texOffs(192, 0).addBox(-7F, -11F, -9F, 14F, 3F, 18F).texOffs(246, 32).addBox(9.75F, -7F, -10.75F, 1.5F, 9F, 1.5F).texOffs(0, 77).addBox(6.75F, -10F, -10.75F, 1.5F, 3.5F, 1.5F).texOffs(0, 59).addBox(-11.25F, -7F, -10.75F, 1.5F, 9F, 1.5F).texOffs(8, 77).addBox(-8.25F, -10F, -10.75F, 1.5F, 3.5F, 1.5F).texOffs(86, 77).addBox(-7.5F, -11.5F, -10.75F, 15F, 1.5F, 1.5F).texOffs(8, 59).addBox(9.75F, -7F, -5.75F, 1.5F, 9F, 1.5F).texOffs(16, 77).addBox(6.75F, -10F, -5.75F, 1.5F, 3.5F, 1.5F).texOffs(16, 59).addBox(-11.25F, -7F, -5.75F, 1.5F, 9F, 1.5F).texOffs(24, 77).addBox(-8.25F, -10F, -5.75F, 1.5F, 3.5F, 1.5F).texOffs(120, 77).addBox(-7.5F, -11.5F, -5.75F, 15F, 1.5F, 1.5F).texOffs(24, 59).addBox(9.75F, -7F, 4.25F, 1.5F, 9F, 1.5F).texOffs(32, 77).addBox(6.75F, -10F, 4.25F, 1.5F, 3.5F, 1.5F).texOffs(32, 59).addBox(-11.25F, -7F, 4.25F, 1.5F, 9F, 1.5F).texOffs(40, 77).addBox(-8.25F, -10F, 4.25F, 1.5F, 3.5F, 1.5F).texOffs(154, 77).addBox(-7.5F, -11.5F, 4.25F, 15F, 1.5F, 1.5F).texOffs(40, 59).addBox(9.75F, -7F, 9.25F, 1.5F, 9F, 1.5F).texOffs(48, 77).addBox(6.75F, -10F, 9.25F, 1.5F, 3.5F, 1.5F).texOffs(48, 59).addBox(-11.25F, -7F, 9.25F, 1.5F, 9F, 1.5F).texOffs(56, 77).addBox(-8.25F, -10F, 9.25F, 1.5F, 3.5F, 1.5F).texOffs(188, 77).addBox(-7.5F, -11.5F, 9.25F, 15F, 1.5F, 1.5F), PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("growth_0", CubeListBuilder.create().texOffs(232, 70).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F).texOffs(132, 83).addBox(-2.5F, -4F, -0.25F, 5F, 1F, 0.5F), PartPose.offsetAndRotation(0F, -11F, -7F, 0F, 0F, 0F));
        p0.addOrReplaceChild("growth_1", CubeListBuilder.create().texOffs(244, 70).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F).texOffs(144, 83).addBox(-2.5F, -4F, -0.25F, 5F, 1F, 0.5F), PartPose.offsetAndRotation(0F, -11F, 7F, 0F, 0F, 0F));
        PartDefinition p3 = p0.addOrReplaceChild("vent_top", CubeListBuilder.create().texOffs(112, 70).addBox(-2.5F, -0.75F, -2.5F, 5F, 1F, 5F).texOffs(48, 83).addBox(-3F, -1.5F, -3F, 6F, 1.5F, 0.75F).texOffs(62, 83).addBox(-3F, -1.5F, 2.25F, 6F, 1.5F, 0.75F).texOffs(238, 59).addBox(-3F, -1.5F, -2.25F, 0.75F, 1.5F, 4.5F).texOffs(48, 70).addBox(2.25F, -1.5F, -2.25F, 0.75F, 1.5F, 4.5F), PartPose.offsetAndRotation(0F, -11F, 1F, 0F, 0F, 0F));
        p3.addOrReplaceChild("vent_top_lit", CubeListBuilder.create().texOffs(132, 70).addBox(-2.5F, -0.75F, -2.5F, 5F, 1F, 5F, new CubeDeformation(0.2F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        p3.addOrReplaceChild("vent_top_lid", CubeListBuilder.create().texOffs(214, 59).addBox(-3F, -0.75F, 0F, 6F, 0.75F, 6F), PartPose.offsetAndRotation(0F, -1.5F, -3F, 0F, 0F, 0F));
        PartDefinition p6 = p0.addOrReplaceChild("vent_left", CubeListBuilder.create().texOffs(152, 70).addBox(-2.5F, -0.75F, -2.5F, 5F, 1F, 5F).texOffs(76, 83).addBox(-3F, -1.5F, -3F, 6F, 1.5F, 0.75F).texOffs(90, 83).addBox(-3F, -1.5F, 2.25F, 6F, 1.5F, 0.75F).texOffs(60, 70).addBox(-3F, -1.5F, -2.25F, 0.75F, 1.5F, 4.5F).texOffs(72, 70).addBox(2.25F, -1.5F, -2.25F, 0.75F, 1.5F, 4.5F), PartPose.offsetAndRotation(12F, -1F, 0F, 0F, 0F, 1.5708F));
        p6.addOrReplaceChild("vent_left_lit", CubeListBuilder.create().texOffs(172, 70).addBox(-2.5F, -0.75F, -2.5F, 5F, 1F, 5F, new CubeDeformation(0.2F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        p6.addOrReplaceChild("vent_left_lid", CubeListBuilder.create().texOffs(0, 70).addBox(-3F, -0.75F, 0F, 6F, 0.75F, 6F), PartPose.offsetAndRotation(0F, -1.5F, -3F, 0F, 0F, 0F));
        PartDefinition p9 = p0.addOrReplaceChild("vent_right", CubeListBuilder.create().texOffs(192, 70).addBox(-2.5F, -0.75F, -2.5F, 5F, 1F, 5F).texOffs(104, 83).addBox(-3F, -1.5F, -3F, 6F, 1.5F, 0.75F).texOffs(118, 83).addBox(-3F, -1.5F, 2.25F, 6F, 1.5F, 0.75F).texOffs(84, 70).addBox(-3F, -1.5F, -2.25F, 0.75F, 1.5F, 4.5F).texOffs(96, 70).addBox(2.25F, -1.5F, -2.25F, 0.75F, 1.5F, 4.5F), PartPose.offsetAndRotation(-12F, -1F, 0F, 0F, 0F, -1.5708F));
        p9.addOrReplaceChild("vent_right_lit", CubeListBuilder.create().texOffs(212, 70).addBox(-2.5F, -0.75F, -2.5F, 5F, 1F, 5F, new CubeDeformation(0.2F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        p9.addOrReplaceChild("vent_right_lid", CubeListBuilder.create().texOffs(24, 70).addBox(-3F, -0.75F, 0F, 6F, 0.75F, 6F), PartPose.offsetAndRotation(0F, -1.5F, -3F, 0F, 0F, 0F));
        PartDefinition p12 = p0.addOrReplaceChild("neck", CubeListBuilder.create().texOffs(218, 32).addBox(-3.5F, -3.5F, -6F, 7F, 7F, 7F), PartPose.offsetAndRotation(0F, -1F, -12F, 0F, 0F, 0F));
        PartDefinition p13 = p12.addOrReplaceChild("head", CubeListBuilder.create().texOffs(88, 32).addBox(-4.5F, -5F, -8F, 9F, 7F, 8F).texOffs(64, 77).addBox(-2F, -1F, -10F, 4F, 3F, 2F).texOffs(156, 83).addBox(-1F, 2F, -10F, 2F, 1F, 1F), PartPose.offsetAndRotation(0F, -1F, -6F, 0F, 0F, 0F));
        p13.addOrReplaceChild("left_brow", CubeListBuilder.create().texOffs(222, 77).addBox(-2F, -0.75F, -1F, 4F, 1.5F, 1.5F), PartPose.offsetAndRotation(2.6F, -4.2F, -8F, 0F, 0F, 0F));
        p13.addOrReplaceChild("left_tendril", CubeListBuilder.create().texOffs(250, 59).addBox(-1F, -7F, 0F, 2F, 7F, 0F), PartPose.offsetAndRotation(3.5F, -5F, -3F, 0.2F, 0F, 0.6F));
        p13.addOrReplaceChild("right_brow", CubeListBuilder.create().texOffs(234, 77).addBox(-2F, -0.75F, -1F, 4F, 1.5F, 1.5F), PartPose.offsetAndRotation(-2.6F, -4.2F, -8F, 0F, 0F, 0F));
        p13.addOrReplaceChild("right_tendril", CubeListBuilder.create().texOffs(108, 70).addBox(-1F, -7F, 0F, 2F, 7F, 0F), PartPose.offsetAndRotation(-3.5F, -5F, -3F, 0.2F, 0F, -0.6F));
        p13.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(56, 59).addBox(-4F, 0F, -7F, 8F, 2F, 7F).texOffs(246, 77).addBox(-1F, -1F, -8F, 2F, 3F, 1F), PartPose.offsetAndRotation(0F, 2F, -1F, 0F, 0F, 0F));
        p0.addOrReplaceChild("front_left_leg", CubeListBuilder.create().texOffs(122, 32).addBox(-3F, -1F, -3F, 6F, 9F, 6F).texOffs(0, 83).addBox(-2.5F, 0F, -3.5F, 5F, 3F, 1F).texOffs(86, 59).addBox(-3.5F, 6F, -3.5F, 7F, 2F, 7F), PartPose.offsetAndRotation(9F, 2F, -8.5F, 0F, 0F, 0F));
        p0.addOrReplaceChild("front_right_leg", CubeListBuilder.create().texOffs(146, 32).addBox(-3F, -1F, -3F, 6F, 9F, 6F).texOffs(12, 83).addBox(-2.5F, 0F, -3.5F, 5F, 3F, 1F).texOffs(114, 59).addBox(-3.5F, 6F, -3.5F, 7F, 2F, 7F), PartPose.offsetAndRotation(-9F, 2F, -8.5F, 0F, 0F, 0F));
        p0.addOrReplaceChild("hind_left_leg", CubeListBuilder.create().texOffs(170, 32).addBox(-3F, -1F, -3F, 6F, 9F, 6F).texOffs(24, 83).addBox(-2.5F, 0F, -3.5F, 5F, 3F, 1F).texOffs(142, 59).addBox(-3.5F, 6F, -3.5F, 7F, 2F, 7F), PartPose.offsetAndRotation(9F, 2F, 8.5F, 0F, 0F, 0F));
        p0.addOrReplaceChild("hind_right_leg", CubeListBuilder.create().texOffs(194, 32).addBox(-3F, -1F, -3F, 6F, 9F, 6F).texOffs(36, 83).addBox(-2.5F, 0F, -3.5F, 5F, 3F, 1F).texOffs(170, 59).addBox(-3.5F, 6F, -3.5F, 7F, 2F, 7F), PartPose.offsetAndRotation(-9F, 2F, 8.5F, 0F, 0F, 0F));
        p0.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(198, 59).addBox(-1.5F, -1F, 0F, 3F, 3F, 5F).texOffs(76, 77).addBox(-1F, -0.5F, 5F, 2F, 2F, 3F), PartPose.offsetAndRotation(0F, 0F, 13F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 256, 352);
    }

    public static LayerDefinition stomper() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-16F, -20F, -18F, 32F, 20F, 36F).texOffs(0, 56).addBox(-17F, -7F, -19F, 34F, 9F, 38F), PartPose.offsetAndRotation(0F, 11F, 2F, 0F, 0F, 0F));
        PartDefinition p1 = p0.addOrReplaceChild("hump", CubeListBuilder.create().texOffs(136, 0).addBox(-12F, -6F, -13F, 24F, 6F, 26F).texOffs(192, 124).addBox(-8F, -8F, -8F, 16F, 2F, 13F), PartPose.offsetAndRotation(0F, -20F, 0F, 0F, 0F, 0F));
        p1.addOrReplaceChild("spiracle_0", CubeListBuilder.create().texOffs(86, 183).addBox(-1.5F, -1.5F, -1.5F, 3F, 1.5F, 3F), PartPose.offsetAndRotation(-4.5F, -8F, -5F, 0F, 0F, 0F));
        p1.addOrReplaceChild("spiracle_1", CubeListBuilder.create().texOffs(98, 183).addBox(-1.5F, -1.5F, -1.5F, 3F, 1.5F, 3F), PartPose.offsetAndRotation(4.5F, -8F, -5F, 0F, 0F, 0F));
        p1.addOrReplaceChild("spiracle_2", CubeListBuilder.create().texOffs(110, 183).addBox(-1.5F, -1.5F, -1.5F, 3F, 1.5F, 3F), PartPose.offsetAndRotation(0F, -8F, 3F, 0F, 0F, 0F));
        p1.addOrReplaceChild("plant_0", CubeListBuilder.create().texOffs(26, 172).addBox(-5.5F, -11F, 0F, 11F, 11F, 0F).texOffs(232, 56).addBox(0F, -11F, -5.5F, 0F, 11F, 11F), PartPose.offsetAndRotation(-8F, -6F, -9F, 0F, 0F, 0F));
        p1.addOrReplaceChild("plant_1", CubeListBuilder.create().texOffs(178, 172).addBox(-4F, -8F, 0F, 8F, 8F, 0F).texOffs(144, 124).addBox(0F, -8F, -4F, 0F, 8F, 8F), PartPose.offsetAndRotation(8F, -6F, -9F, 0F, 0.6F, 0F));
        p1.addOrReplaceChild("plant_2", CubeListBuilder.create().texOffs(128, 172).addBox(-4F, -9F, 0F, 8F, 9F, 0F).texOffs(40, 124).addBox(0F, -9F, -4F, 0F, 9F, 8F), PartPose.offsetAndRotation(-3F, -8F, -5F, 0F, 1.2F, 0F));
        p1.addOrReplaceChild("plant_3", CubeListBuilder.create().texOffs(144, 172).addBox(-4F, -9F, 0F, 8F, 9F, 0F).texOffs(56, 124).addBox(0F, -9F, -4F, 0F, 9F, 8F), PartPose.offsetAndRotation(4F, -8F, 1F, 0F, 1.8F, 0F));
        p1.addOrReplaceChild("plant_4", CubeListBuilder.create().texOffs(70, 172).addBox(-5F, -10F, 0F, 10F, 10F, 0F).texOffs(236, 0).addBox(0F, -10F, -5F, 0F, 10F, 10F), PartPose.offsetAndRotation(8F, -6F, 9F, 0F, 2.4F, 0F));
        p1.addOrReplaceChild("plant_5", CubeListBuilder.create().texOffs(28, 183).addBox(-4F, -7F, 0F, 8F, 7F, 0F).texOffs(232, 142).addBox(0F, -7F, -4F, 0F, 7F, 8F), PartPose.offsetAndRotation(-8F, -6F, 8F, 0F, 3F, 0F));
        p1.addOrReplaceChild("plant_6", CubeListBuilder.create().texOffs(226, 172).addBox(-3.5F, -8F, 0F, 7F, 8F, 0F).texOffs(16, 157).addBox(0F, -8F, -3.5F, 0F, 8F, 7F), PartPose.offsetAndRotation(-3F, -8F, 3F, 0F, 3.6F, 0F));
        p1.addOrReplaceChild("plant_7", CubeListBuilder.create().texOffs(44, 183).addBox(-4F, -7F, 0F, 8F, 7F, 0F).texOffs(0, 157).addBox(0F, -7F, -4F, 0F, 7F, 8F), PartPose.offsetAndRotation(2F, -6F, 10F, 0F, 4.2F, 0F));
        p0.addOrReplaceChild("body_plant_0", CubeListBuilder.create().texOffs(194, 172).addBox(-4F, -8F, 0F, 8F, 8F, 0F).texOffs(160, 124).addBox(0F, -8F, -4F, 0F, 8F, 8F), PartPose.offsetAndRotation(-13F, -20F, -15F, 0F, 0.3F, 0F));
        p0.addOrReplaceChild("body_plant_1", CubeListBuilder.create().texOffs(240, 172).addBox(-3.5F, -8F, 0F, 7F, 8F, 0F).texOffs(30, 157).addBox(0F, -8F, -3.5F, 0F, 8F, 7F), PartPose.offsetAndRotation(13F, -20F, -14F, 0F, 1.2F, 0F));
        p0.addOrReplaceChild("body_plant_2", CubeListBuilder.create().texOffs(0, 183).addBox(-3.5F, -8F, 0F, 7F, 8F, 0F).texOffs(44, 157).addBox(0F, -8F, -3.5F, 0F, 8F, 7F), PartPose.offsetAndRotation(-13F, -20F, 15F, 0F, 2.1F, 0F));
        p0.addOrReplaceChild("body_plant_3", CubeListBuilder.create().texOffs(210, 172).addBox(-4F, -8F, 0F, 8F, 8F, 0F).texOffs(176, 124).addBox(0F, -8F, -4F, 0F, 8F, 8F), PartPose.offsetAndRotation(13F, -20F, 14F, 0F, 3F, 0F));
        p0.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(90, 172).addBox(-1.5F, -1.5F, 0F, 3F, 3F, 7F).texOffs(110, 172).addBox(-2.5F, -2.5F, 6F, 5F, 5F, 4F), PartPose.offsetAndRotation(0F, -15F, 18F, -0.7F, 0F, 0F));
        PartDefinition p18 = p0.addOrReplaceChild("head", CubeListBuilder.create().texOffs(144, 56).addBox(-15F, -10F, -13F, 30F, 12F, 14F).texOffs(72, 124).addBox(-12F, -13F, -11F, 24F, 4F, 12F), PartPose.offsetAndRotation(0F, -6F, -18F, 0F, 0F, 0F));
        p18.addOrReplaceChild("head_plant_0", CubeListBuilder.create().texOffs(14, 183).addBox(-3.5F, -8F, 0F, 7F, 8F, 0F).texOffs(58, 157).addBox(0F, -8F, -3.5F, 0F, 8F, 7F), PartPose.offsetAndRotation(-7F, -13F, -6F, 0F, 0.5F, 0F));
        p18.addOrReplaceChild("head_plant_1", CubeListBuilder.create().texOffs(60, 183).addBox(-3.5F, -7F, 0F, 7F, 7F, 0F).texOffs(136, 157).addBox(0F, -7F, -3.5F, 0F, 7F, 7F), PartPose.offsetAndRotation(8F, -13F, -4F, 0F, -0.4F, 0F));
        PartDefinition p21 = p18.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(160, 103).addBox(-15F, 0F, -13F, 30F, 5F, 14F), PartPose.offsetAndRotation(0F, 2F, 0F, 0F, 0F, 0F));
        p21.addOrReplaceChild("throat", CubeListBuilder.create().texOffs(0, 142).addBox(-9F, -1F, -5F, 18F, 5F, 10F), PartPose.offsetAndRotation(0F, 5F, -6F, 0F, 0F, 0F));
        PartDefinition p23 = p18.addOrReplaceChild("left_eye", CubeListBuilder.create().texOffs(72, 157).addBox(-4F, -5F, -4F, 8F, 6F, 8F), PartPose.offsetAndRotation(8.5F, -12F, -7F, 0F, 0F, 0F));
        p23.addOrReplaceChild("left_eyelid", CubeListBuilder.create().texOffs(180, 157).addBox(-4F, -5F, -4F, 8F, 3F, 8F, new CubeDeformation(0.15F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        p18.addOrReplaceChild("left_small_eye", CubeListBuilder.create().texOffs(244, 157).addBox(-2F, -2F, -1.5F, 4F, 4F, 2F), PartPose.offsetAndRotation(12.5F, -5.5F, -13F, 0F, 0F, 0F));
        p18.addOrReplaceChild("left_ear", CubeListBuilder.create().texOffs(0, 124).addBox(0F, -1F, -4F, 2F, 10F, 8F), PartPose.offsetAndRotation(15F, -8F, -4F, 0F, -0.3F, 0.35F));
        PartDefinition p27 = p18.addOrReplaceChild("right_eye", CubeListBuilder.create().texOffs(104, 157).addBox(-4F, -5F, -4F, 8F, 6F, 8F), PartPose.offsetAndRotation(-8.5F, -12F, -7F, 0F, 0F, 0F));
        p27.addOrReplaceChild("right_eyelid", CubeListBuilder.create().texOffs(212, 157).addBox(-4F, -5F, -4F, 8F, 3F, 8F, new CubeDeformation(0.15F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        p18.addOrReplaceChild("right_small_eye", CubeListBuilder.create().texOffs(74, 183).addBox(-2F, -2F, -1.5F, 4F, 4F, 2F), PartPose.offsetAndRotation(-12.5F, -5.5F, -13F, 0F, 0F, 0F));
        p18.addOrReplaceChild("right_ear", CubeListBuilder.create().texOffs(20, 124).addBox(-2F, -1F, -4F, 2F, 10F, 8F), PartPose.offsetAndRotation(-15F, -8F, -4F, 0F, 0.3F, -0.35F));
        PartDefinition p31 = p18.addOrReplaceChild("trunk_0", CubeListBuilder.create().texOffs(150, 157).addBox(-4F, 0F, -3.5F, 8F, 6F, 7F), PartPose.offsetAndRotation(0F, -5F, -14F, -0.1F, 0F, 0F));
        PartDefinition p32 = p31.addOrReplaceChild("trunk_1", CubeListBuilder.create().texOffs(0, 172).addBox(-3.5F, 0F, -3F, 7F, 5F, 6F), PartPose.offsetAndRotation(0F, 6F, 0F, -0.2F, 0F, 0F));
        PartDefinition p33 = p32.addOrReplaceChild("trunk_2", CubeListBuilder.create().texOffs(48, 172).addBox(-3F, 0F, -2.5F, 6F, 5F, 5F), PartPose.offsetAndRotation(0F, 5F, 0F, -0.35F, 0F, 0F));
        p33.addOrReplaceChild("trunk_3", CubeListBuilder.create().texOffs(160, 172).addBox(-2.5F, 0F, -2F, 5F, 4F, 4F), PartPose.offsetAndRotation(0F, 5F, 0F, -0.6F, 0F, 0F));
        PartDefinition p35 = p0.addOrReplaceChild("front_left_leg", CubeListBuilder.create().texOffs(0, 103).addBox(-5F, 0F, -5F, 10F, 11F, 10F), PartPose.offsetAndRotation(11F, -2F, -10F, 0F, 0F, 0F));
        p35.addOrReplaceChild("front_left_foot", CubeListBuilder.create().texOffs(56, 142).addBox(-5.5F, 0F, -5.5F, 11F, 4F, 11F), PartPose.offsetAndRotation(0F, 9F, 0F, 0F, 0F, 0F));
        PartDefinition p37 = p0.addOrReplaceChild("front_right_leg", CubeListBuilder.create().texOffs(40, 103).addBox(-5F, 0F, -5F, 10F, 11F, 10F), PartPose.offsetAndRotation(-11F, -2F, -10F, 0F, 0F, 0F));
        p37.addOrReplaceChild("front_right_foot", CubeListBuilder.create().texOffs(100, 142).addBox(-5.5F, 0F, -5.5F, 11F, 4F, 11F), PartPose.offsetAndRotation(0F, 9F, 0F, 0F, 0F, 0F));
        PartDefinition p39 = p0.addOrReplaceChild("back_left_leg", CubeListBuilder.create().texOffs(80, 103).addBox(-5F, 0F, -5F, 10F, 11F, 10F), PartPose.offsetAndRotation(11F, -2F, 10F, 0F, 0F, 0F));
        p39.addOrReplaceChild("back_left_foot", CubeListBuilder.create().texOffs(144, 142).addBox(-5.5F, 0F, -5.5F, 11F, 4F, 11F), PartPose.offsetAndRotation(0F, 9F, 0F, 0F, 0F, 0F));
        PartDefinition p41 = p0.addOrReplaceChild("back_right_leg", CubeListBuilder.create().texOffs(120, 103).addBox(-5F, 0F, -5F, 10F, 11F, 10F), PartPose.offsetAndRotation(-11F, -2F, 10F, 0F, 0F, 0F));
        p41.addOrReplaceChild("back_right_foot", CubeListBuilder.create().texOffs(188, 142).addBox(-5.5F, 0F, -5.5F, 11F, 4F, 11F), PartPose.offsetAndRotation(0F, 9F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 256, 256);
    }

    public static LayerDefinition sky_whale() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-16F, -14F, -22F, 32F, 26F, 44F).texOffs(0, 70).addBox(-13F, 12F, -20F, 26F, 2F, 30F), PartPose.offsetAndRotation(0F, 4F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("back_tuft_0", CubeListBuilder.create().texOffs(0, 145).addBox(-7F, -5F, -6F, 14F, 6F, 12F).texOffs(132, 196).addBox(-5F, -8F, -4F, 8F, 3F, 6F).texOffs(24, 207).addBox(1F, -7F, -2F, 5F, 2F, 6F), PartPose.offsetAndRotation(-6F, -14F, -14F, 0F, 0F, 0F));
        p0.addOrReplaceChild("back_tuft_1", CubeListBuilder.create().texOffs(190, 102).addBox(-8F, -6F, -6F, 16F, 7F, 12F).texOffs(102, 196).addBox(-6F, -9F, -4F, 9F, 3F, 6F).texOffs(224, 196).addBox(1F, -8F, -2F, 6F, 2F, 6F), PartPose.offsetAndRotation(5F, -14F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("back_tuft_2", CubeListBuilder.create().texOffs(68, 163).addBox(-6F, -5F, -5F, 12F, 6F, 10F).texOffs(0, 207).addBox(-4F, -8F, -3F, 7F, 3F, 5F).texOffs(154, 207).addBox(1F, -7F, -2F, 4F, 2F, 5F), PartPose.offsetAndRotation(-4F, -14F, 13F, 0F, 0F, 0F));
        p0.addOrReplaceChild("back_flower_0", CubeListBuilder.create().texOffs(66, 196).addBox(-4.5F, -10F, 0F, 9F, 10F, 0F).texOffs(0, 126).addBox(0F, -10F, -4.5F, 0F, 10F, 9F), PartPose.offsetAndRotation(10F, -14F, -15F, 0F, 0F, 0F));
        p0.addOrReplaceChild("back_flower_1", CubeListBuilder.create().texOffs(84, 196).addBox(-4.5F, -10F, 0F, 9F, 10F, 0F).texOffs(18, 126).addBox(0F, -10F, -4.5F, 0F, 10F, 9F), PartPose.offsetAndRotation(-12F, -14F, -4F, 0F, 0.7F, 0F));
        p0.addOrReplaceChild("back_flower_2", CubeListBuilder.create().texOffs(160, 196).addBox(-4F, -9F, 0F, 8F, 9F, 0F).texOffs(204, 145).addBox(0F, -9F, -4F, 0F, 9F, 8F), PartPose.offsetAndRotation(11F, -14F, 10F, 0F, 1.4F, 0F));
        p0.addOrReplaceChild("back_flower_3", CubeListBuilder.create().texOffs(176, 196).addBox(-4F, -9F, 0F, 8F, 9F, 0F).texOffs(220, 145).addBox(0F, -9F, -4F, 0F, 9F, 8F), PartPose.offsetAndRotation(-11F, -14F, 9F, 0F, 2.1F, 0F));
        p0.addOrReplaceChild("back_flower_4", CubeListBuilder.create().texOffs(192, 196).addBox(-4F, -9F, 0F, 8F, 9F, 0F).texOffs(236, 145).addBox(0F, -9F, -4F, 0F, 9F, 8F), PartPose.offsetAndRotation(-1F, -14F, 19F, 0F, 2.8F, 0F));
        p0.addOrReplaceChild("back_flower_5", CubeListBuilder.create().texOffs(90, 207).addBox(-4F, -8F, 0F, 8F, 8F, 0F).texOffs(56, 180).addBox(0F, -8F, -4F, 0F, 8F, 8F), PartPose.offsetAndRotation(12F, -14F, -3F, 0F, 3.5F, 0F));
        p0.addOrReplaceChild("vine_0", CubeListBuilder.create().texOffs(72, 180).addBox(-3.5F, 0F, 0F, 7F, 16F, 0F).texOffs(242, 0).addBox(0F, 0F, -3.5F, 0F, 16F, 7F), PartPose.offsetAndRotation(17F, -13F, -12F, 0F, 0F, 0F));
        p0.addOrReplaceChild("vine_1", CubeListBuilder.create().texOffs(206, 180).addBox(-3.5F, 0F, 0F, 7F, 12F, 0F).texOffs(36, 126).addBox(0F, 0F, -3.5F, 0F, 12F, 7F), PartPose.offsetAndRotation(17F, -13F, 4F, 0F, 0F, 0F));
        p0.addOrReplaceChild("vine_2", CubeListBuilder.create().texOffs(148, 180).addBox(-3.5F, 0F, 0F, 7F, 14F, 0F).texOffs(162, 102).addBox(0F, 0F, -3.5F, 0F, 14F, 7F), PartPose.offsetAndRotation(17F, -13F, 16F, 0F, 0F, 0F));
        p0.addOrReplaceChild("vine_3", CubeListBuilder.create().texOffs(162, 180).addBox(-3.5F, 0F, 0F, 7F, 14F, 0F).texOffs(176, 102).addBox(0F, 0F, -3.5F, 0F, 14F, 7F), PartPose.offsetAndRotation(-17F, -13F, -8F, 0F, 0F, 0F));
        p0.addOrReplaceChild("vine_4", CubeListBuilder.create().texOffs(86, 180).addBox(-3.5F, 0F, 0F, 7F, 16F, 0F).texOffs(236, 70).addBox(0F, 0F, -3.5F, 0F, 16F, 7F), PartPose.offsetAndRotation(-17F, -13F, 8F, 0F, 0F, 0F));
        p0.addOrReplaceChild("vine_5", CubeListBuilder.create().texOffs(0, 196).addBox(-3.5F, 0F, 0F, 7F, 11F, 0F).texOffs(228, 126).addBox(0F, 0F, -3.5F, 0F, 11F, 7F), PartPose.offsetAndRotation(-17F, -13F, 18F, 0F, 0F, 0F));
        PartDefinition p16 = p0.addOrReplaceChild("head", CubeListBuilder.create().texOffs(152, 0).addBox(-15F, -12F, -15F, 30F, 24F, 15F).texOffs(164, 126).addBox(-10F, -16F, -14F, 20F, 6F, 12F), PartPose.offsetAndRotation(0F, -1F, -22F, 0F, 0F, 0F));
        p16.addOrReplaceChild("head_flower", CubeListBuilder.create().texOffs(208, 196).addBox(-4F, -9F, 0F, 8F, 9F, 0F).texOffs(0, 163).addBox(0F, -9F, -4F, 0F, 9F, 8F), PartPose.offsetAndRotation(4F, -16F, -9F, 0F, 0.4F, 0F));
        PartDefinition p18 = p16.addOrReplaceChild("snout", CubeListBuilder.create().texOffs(16, 163).addBox(-10F, -5F, -6F, 20F, 10F, 6F), PartPose.offsetAndRotation(0F, 3F, -15F, 0F, 0F, 0F));
        p18.addOrReplaceChild("nose_ring", CubeListBuilder.create().texOffs(172, 207).addBox(-3F, 0F, -0.5F, 6F, 6F, 1F), PartPose.offsetAndRotation(0F, 1F, -6F, 0.15F, 0F, 0F));
        p16.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(0, 102).addBox(-14F, 0F, -19F, 28F, 5F, 19F).texOffs(100, 180).addBox(-7F, 5F, -17F, 14F, 4F, 10F), PartPose.offsetAndRotation(0F, 8F, 0F, 0F, 0F, 0F));
        p16.addOrReplaceChild("left_eye", CubeListBuilder.create().texOffs(232, 163).addBox(-1F, -4F, -4F, 2F, 8F, 8F), PartPose.offsetAndRotation(15F, -3F, -9F, 0F, 0F, 0F));
        p16.addOrReplaceChild("left_cheek", CubeListBuilder.create().texOffs(94, 102).addBox(0F, -5F, -6F, 5F, 10F, 12F), PartPose.offsetAndRotation(14F, 5F, -8F, 0F, 0F, -0.2F));
        p16.addOrReplaceChild("left_ear", CubeListBuilder.create().texOffs(106, 207).addBox(0F, -1F, -2.5F, 7F, 2F, 5F), PartPose.offsetAndRotation(15F, -7F, -5F, 0F, 0F, 0.5F));
        PartDefinition p24 = p16.addOrReplaceChild("left_horn", CubeListBuilder.create().texOffs(14, 196).addBox(0F, -2.5F, -2.5F, 8F, 5F, 5F), PartPose.offsetAndRotation(12F, -12F, -7F, 0F, 0.2F, -0.25F));
        PartDefinition p25 = p24.addOrReplaceChild("left_horn_tip", CubeListBuilder.create().texOffs(46, 207).addBox(0F, -2F, -2F, 7F, 4F, 4F), PartPose.offsetAndRotation(7.5F, 0F, 0F, -0.3F, 0F, -0.9F));
        p25.addOrReplaceChild("left_horn_point", CubeListBuilder.create().texOffs(186, 207).addBox(0F, -1.5F, -1.5F, 5F, 3F, 3F), PartPose.offsetAndRotation(6.5F, 0F, 0F, -0.2F, 0F, -0.7F));
        p16.addOrReplaceChild("right_eye", CubeListBuilder.create().texOffs(36, 180).addBox(-1F, -4F, -4F, 2F, 8F, 8F), PartPose.offsetAndRotation(-15F, -3F, -9F, 0F, 0F, 0F));
        p16.addOrReplaceChild("right_cheek", CubeListBuilder.create().texOffs(128, 102).addBox(-5F, -5F, -6F, 5F, 10F, 12F), PartPose.offsetAndRotation(-14F, 5F, -8F, 0F, 0F, 0.2F));
        p16.addOrReplaceChild("right_ear", CubeListBuilder.create().texOffs(130, 207).addBox(-7F, -1F, -2.5F, 7F, 2F, 5F), PartPose.offsetAndRotation(-15F, -7F, -5F, 0F, 0F, -0.5F));
        PartDefinition p30 = p16.addOrReplaceChild("right_horn", CubeListBuilder.create().texOffs(40, 196).addBox(-8F, -2.5F, -2.5F, 8F, 5F, 5F), PartPose.offsetAndRotation(-12F, -12F, -7F, 0F, -0.2F, 0.25F));
        PartDefinition p31 = p30.addOrReplaceChild("right_horn_tip", CubeListBuilder.create().texOffs(68, 207).addBox(-7F, -2F, -2F, 7F, 4F, 4F), PartPose.offsetAndRotation(-7.5F, 0F, 0F, -0.3F, 0F, 0.9F));
        p31.addOrReplaceChild("right_horn_point", CubeListBuilder.create().texOffs(202, 207).addBox(-5F, -1.5F, -1.5F, 5F, 3F, 3F), PartPose.offsetAndRotation(-6.5F, 0F, 0F, -0.2F, 0F, 0.7F));
        PartDefinition p33 = p0.addOrReplaceChild("left_flipper", CubeListBuilder.create().texOffs(64, 145).addBox(0F, -1F, -7F, 20F, 2F, 15F).texOffs(156, 163).addBox(0F, -2.5F, -6F, 7F, 4F, 12F), PartPose.offsetAndRotation(16F, 6F, -10F, 0F, 0F, 0.3F));
        p33.addOrReplaceChild("left_flipper_vine", CubeListBuilder.create().texOffs(220, 180).addBox(-3F, 0F, 0F, 6F, 12F, 0F).texOffs(242, 126).addBox(0F, 0F, -3F, 0F, 12F, 6F), PartPose.offsetAndRotation(13F, 1F, 2F, 0F, 0F, 0F));
        PartDefinition p35 = p0.addOrReplaceChild("right_flipper", CubeListBuilder.create().texOffs(134, 145).addBox(-20F, -1F, -7F, 20F, 2F, 15F).texOffs(194, 163).addBox(-7F, -2.5F, -6F, 7F, 4F, 12F), PartPose.offsetAndRotation(-16F, 6F, -10F, 0F, 0F, -0.3F));
        p35.addOrReplaceChild("right_flipper_vine", CubeListBuilder.create().texOffs(232, 180).addBox(-3F, 0F, 0F, 6F, 12F, 0F).texOffs(52, 145).addBox(0F, 0F, -3F, 0F, 12F, 6F), PartPose.offsetAndRotation(-13F, 1F, 2F, 0F, 0F, 0F));
        PartDefinition p37 = p0.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(112, 70).addBox(-12F, -10F, 0F, 24F, 20F, 12F).texOffs(112, 163).addBox(-6F, -15F, 0F, 12F, 6F, 10F), PartPose.offsetAndRotation(0F, -1F, 22F, 0F, 0F, 0F));
        PartDefinition p38 = p37.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(184, 70).addBox(-8F, -7F, 0F, 16F, 14F, 10F), PartPose.offsetAndRotation(0F, 0F, 12F, 0F, 0F, 0F));
        PartDefinition p39 = p38.addOrReplaceChild("tail3", CubeListBuilder.create().texOffs(0, 180).addBox(-5F, -4F, 0F, 10F, 8F, 8F), PartPose.offsetAndRotation(0F, 0F, 10F, 0F, 0F, 0F));
        p39.addOrReplaceChild("flukes", CubeListBuilder.create().texOffs(50, 126).addBox(-21F, -1.5F, -2F, 42F, 3F, 15F).texOffs(176, 180).addBox(-4F, -4F, -1F, 8F, 6F, 7F), PartPose.offsetAndRotation(0F, 0F, 7F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 256, 256);
    }

    public static LayerDefinition fanfare_eel() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(34, 0).addBox(-2.5F, -2.5F, -6F, 5F, 5F, 6F), PartPose.offsetAndRotation(0F, 20F, -6F, 0F, 0F, 0F));
        PartDefinition p1 = p0.addOrReplaceChild("pipe", CubeListBuilder.create().texOffs(0, 21).addBox(-1.5F, -1.5F, -3F, 3F, 3F, 3F), PartPose.offsetAndRotation(0F, 0.5F, -6F, 0F, 0F, 0F));
        PartDefinition p2 = p1.addOrReplaceChild("bell", CubeListBuilder.create().texOffs(78, 0).addBox(-4F, -4F, -2F, 8F, 8F, 2F), PartPose.offsetAndRotation(0F, 0F, -3F, 0F, 0F, 0F));
        p2.addOrReplaceChild("bell_fin_0", CubeListBuilder.create().texOffs(118, 0).addBox(0F, -8F, -1F, 0F, 5F, 4F), PartPose.offsetAndRotation(0F, 0F, -1F, 0F, 0F, 0F));
        p2.addOrReplaceChild("bell_fin_1", CubeListBuilder.create().texOffs(42, 12).addBox(0F, -8F, -1F, 0F, 5F, 4F), PartPose.offsetAndRotation(0F, 0F, -1F, 0F, 0F, 1.5708F));
        p2.addOrReplaceChild("bell_fin_2", CubeListBuilder.create().texOffs(50, 12).addBox(0F, -8F, -1F, 0F, 5F, 4F), PartPose.offsetAndRotation(0F, 0F, -1F, 0F, 0F, 3.1416F));
        p2.addOrReplaceChild("bell_fin_3", CubeListBuilder.create().texOffs(58, 12).addBox(0F, -8F, -1F, 0F, 5F, 4F), PartPose.offsetAndRotation(0F, 0F, -1F, 0F, 0F, -1.5708F));
        p0.addOrReplaceChild("crest", CubeListBuilder.create().texOffs(66, 12).addBox(0F, -3F, -2F, 0F, 3F, 5F), PartPose.offsetAndRotation(0F, -2.5F, -3F, 0F, 0F, 0F));
        PartDefinition p8 = p0.addOrReplaceChild("segment_0", CubeListBuilder.create().texOffs(0, 0).addBox(-2.25F, -2.25F, 0F, 4.5F, 4.5F, 7F).texOffs(18, 12).addBox(0F, -4.75F, 0.5F, 0F, 2.5F, 6F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        PartDefinition p9 = p8.addOrReplaceChild("segment_1", CubeListBuilder.create().texOffs(56, 0).addBox(-2F, -2F, 0F, 4F, 4F, 7F).texOffs(30, 12).addBox(0F, -4.5F, 0.5F, 0F, 2.5F, 6F), PartPose.offsetAndRotation(0F, 0F, 7F, 0F, 0F, 0F));
        PartDefinition p10 = p9.addOrReplaceChild("segment_2", CubeListBuilder.create().texOffs(98, 0).addBox(-1.75F, -1.75F, 0F, 3.5F, 3.5F, 6F).texOffs(76, 12).addBox(0F, -4.25F, 0.5F, 0F, 2.5F, 5F), PartPose.offsetAndRotation(0F, 0F, 7F, 0F, 0F, 0F));
        PartDefinition p11 = p10.addOrReplaceChild("segment_3", CubeListBuilder.create().texOffs(0, 12).addBox(-1.5F, -1.5F, 0F, 3F, 3F, 6F).texOffs(86, 12).addBox(0F, -4F, 0.5F, 0F, 2.5F, 5F), PartPose.offsetAndRotation(0F, 0F, 6F, 0F, 0F, 0F));
        p11.addOrReplaceChild("segment_4", CubeListBuilder.create().texOffs(96, 12).addBox(-1F, -1F, 0F, 2F, 2F, 5F).texOffs(110, 12).addBox(0F, -3.5F, 0.5F, 0F, 2.5F, 4F).texOffs(24, 0).addBox(0F, -3.5F, 4.5F, 0F, 7F, 5F), PartPose.offsetAndRotation(0F, 0F, 6F, 0F, 0F, 0F));
        p0.addOrReplaceChild("left_fin", CubeListBuilder.create().texOffs(12, 21).addBox(0F, 0F, -1F, 3F, 0F, 3F), PartPose.offsetAndRotation(2.5F, 1.5F, -1F, 0F, 0.4F, 0.5F));
        p0.addOrReplaceChild("right_fin", CubeListBuilder.create().texOffs(24, 21).addBox(-3F, 0F, -1F, 3F, 0F, 3F), PartPose.offsetAndRotation(-2.5F, 1.5F, -1F, 0F, -0.4F, -0.5F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition kazoo_fish() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-1.5F, -2.5F, -3F, 3F, 5F, 6F), PartPose.offsetAndRotation(0F, 21F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("left_eye", CubeListBuilder.create().texOffs(40, 0).addBox(0F, -1.5F, -1.5F, 1F, 3F, 3F), PartPose.offsetAndRotation(1.5F, -1.5F, -2F, 0F, 0F, 0F));
        p0.addOrReplaceChild("right_eye", CubeListBuilder.create().texOffs(10, 11).addBox(-1F, -1F, -1F, 1F, 2F, 2F), PartPose.offsetAndRotation(-1.5F, -1.5F, -2F, 0F, 0F, 0F));
        p0.addOrReplaceChild("kazoo", CubeListBuilder.create().texOffs(28, 0).addBox(-1F, -1F, -4F, 2F, 2F, 4F).texOffs(40, 11).addBox(-0.75F, -2F, -3F, 1.5F, 1F, 1.5F), PartPose.offsetAndRotation(0F, 0.5F, -3F, 0F, 0F, 0F));
        PartDefinition p4 = p0.addOrReplaceChild("tuft", CubeListBuilder.create().texOffs(0, 11).addBox(-1F, -1F, -1.5F, 2F, 1F, 3F), PartPose.offsetAndRotation(0F, -2.5F, -0.5F, 0F, 0F, 0F));
        p4.addOrReplaceChild("tuft_sprout", CubeListBuilder.create().texOffs(48, 11).addBox(-1.5F, -3F, 0F, 3F, 3F, 0F).texOffs(48, 0).addBox(0F, -3F, -1.5F, 0F, 3F, 3F), PartPose.offsetAndRotation(0F, -1F, 0F, 0F, 0.6F, 0F));
        p0.addOrReplaceChild("dorsal", CubeListBuilder.create().texOffs(54, 0).addBox(0F, -3F, -0.5F, 0F, 3F, 3F), PartPose.offsetAndRotation(0F, -2.5F, 1F, 0F, 0F, 0F));
        p0.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(18, 0).addBox(0F, -3F, 0F, 0F, 6F, 5F), PartPose.offsetAndRotation(0F, 0F, 3F, 0F, 0F, 0F));
        p0.addOrReplaceChild("left_fin", CubeListBuilder.create().texOffs(16, 11).addBox(0F, 0F, 0F, 2.5F, 0F, 2.5F), PartPose.offsetAndRotation(1.5F, 1.5F, -0.5F, 0F, 0F, 0.6F));
        p0.addOrReplaceChild("right_fin", CubeListBuilder.create().texOffs(28, 11).addBox(-2.5F, 0F, 0F, 2.5F, 0F, 2.5F), PartPose.offsetAndRotation(-1.5F, 1.5F, -0.5F, 0F, 0F, -0.6F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    public static LayerDefinition tubafish() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-6F, -6F, -6F, 12F, 11F, 12F), PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("mouth", CubeListBuilder.create().texOffs(96, 0).addBox(-2F, -1.5F, -2F, 4F, 3F, 2F), PartPose.offsetAndRotation(0F, 1.5F, -6F, 0F, 0F, 0F));
        PartDefinition p2 = p0.addOrReplaceChild("tuba", CubeListBuilder.create().texOffs(84, 0).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(0F, -6F, 1F, 0F, 0F, 0F));
        PartDefinition p3 = p2.addOrReplaceChild("tuba_bell", CubeListBuilder.create().texOffs(48, 0).addBox(-3.5F, -3F, -3.5F, 7F, 3F, 7F), PartPose.offsetAndRotation(0F, -3F, 0F, 0.2F, 0F, 0F));
        p3.addOrReplaceChild("tentacle_0", CubeListBuilder.create().texOffs(108, 0).addBox(-0.5F, -3.5F, -0.5F, 1F, 3.5F, 1F), PartPose.offsetAndRotation(2.6F, -3F, 0F, 0F, 0F, 0.5F));
        p3.addOrReplaceChild("tentacle_1", CubeListBuilder.create().texOffs(112, 0).addBox(-0.5F, -3.5F, -0.5F, 1F, 3.5F, 1F), PartPose.offsetAndRotation(1.3F, -3F, 2.2517F, -0.433F, 0F, 0.25F));
        p3.addOrReplaceChild("tentacle_2", CubeListBuilder.create().texOffs(116, 0).addBox(-0.5F, -3.5F, -0.5F, 1F, 3.5F, 1F), PartPose.offsetAndRotation(-1.3F, -3F, 2.2517F, -0.433F, 0F, -0.25F));
        p3.addOrReplaceChild("tentacle_3", CubeListBuilder.create().texOffs(120, 0).addBox(-0.5F, -3.5F, -0.5F, 1F, 3.5F, 1F), PartPose.offsetAndRotation(-2.6F, -3F, 0F, 0F, 0F, -0.5F));
        p3.addOrReplaceChild("tentacle_4", CubeListBuilder.create().texOffs(124, 0).addBox(-0.5F, -3.5F, -0.5F, 1F, 3.5F, 1F), PartPose.offsetAndRotation(-1.3F, -3F, -2.2517F, 0.433F, 0F, -0.25F));
        p3.addOrReplaceChild("tentacle_5", CubeListBuilder.create().texOffs(0, 23).addBox(-0.5F, -3.5F, -0.5F, 1F, 3.5F, 1F), PartPose.offsetAndRotation(1.3F, -3F, -2.2517F, 0.433F, 0F, 0.25F));
        p0.addOrReplaceChild("valve_0", CubeListBuilder.create().texOffs(4, 23).addBox(-0.75F, -2F, -0.75F, 1.5F, 2F, 1.5F), PartPose.offsetAndRotation(-3.5F, -6F, -2.5F, 0F, 0F, 0F));
        p0.addOrReplaceChild("valve_1", CubeListBuilder.create().texOffs(12, 23).addBox(-0.75F, -2F, -0.75F, 1.5F, 2F, 1.5F), PartPose.offsetAndRotation(3.5F, -6F, -2.5F, 0F, 0F, 0F));
        p0.addOrReplaceChild("spike_0", CubeListBuilder.create().texOffs(32, 23).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).texOffs(84, 23).addBox(-1.5F, -2.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(0F, -6F, -3F, -0.6F, 0F, 0F));
        p0.addOrReplaceChild("spike_1", CubeListBuilder.create().texOffs(36, 23).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).texOffs(88, 23).addBox(0.5F, -2.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(-6F, -1F, 0F, 0F, 0F, 1.2F));
        p0.addOrReplaceChild("spike_2", CubeListBuilder.create().texOffs(40, 23).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).texOffs(92, 23).addBox(-1.5F, -2.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(6F, -1F, 0F, 0F, 0F, -1.2F));
        p0.addOrReplaceChild("spike_3", CubeListBuilder.create().texOffs(44, 23).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).texOffs(96, 23).addBox(0.5F, -2.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(0F, -1F, 6F, 0.9F, 0F, 0F));
        p0.addOrReplaceChild("spike_4", CubeListBuilder.create().texOffs(48, 23).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).texOffs(100, 23).addBox(-1.5F, -2.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(-4.5F, -5F, 4F, 0.6F, 0F, 0.7F));
        p0.addOrReplaceChild("spike_5", CubeListBuilder.create().texOffs(52, 23).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).texOffs(104, 23).addBox(0.5F, -2.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(4.5F, -5F, 4F, 0.6F, 0F, -0.7F));
        p0.addOrReplaceChild("spike_6", CubeListBuilder.create().texOffs(56, 23).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).texOffs(108, 23).addBox(-1.5F, -2.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(-4.5F, 3F, -4F, -1.2F, 0F, 0.6F));
        p0.addOrReplaceChild("spike_7", CubeListBuilder.create().texOffs(60, 23).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).texOffs(112, 23).addBox(0.5F, -2.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(4.5F, 3F, -4F, -1.2F, 0F, -0.6F));
        p0.addOrReplaceChild("spike_8", CubeListBuilder.create().texOffs(64, 23).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).texOffs(116, 23).addBox(-1.5F, -2.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(-6F, -4F, -3F, -0.4F, 0F, 1F));
        p0.addOrReplaceChild("spike_9", CubeListBuilder.create().texOffs(68, 23).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).texOffs(120, 23).addBox(0.5F, -2.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(6F, -4F, -3F, -0.4F, 0F, -1F));
        p0.addOrReplaceChild("spike_10", CubeListBuilder.create().texOffs(72, 23).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).texOffs(124, 23).addBox(-1.5F, -2.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(0F, 5F, 0F, 3.14F, 0F, 0F));
        p0.addOrReplaceChild("spike_11", CubeListBuilder.create().texOffs(76, 23).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).texOffs(0, 28).addBox(0.5F, -2.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(-4F, 4F, 4F, 2.2F, 0F, 0.6F));
        p0.addOrReplaceChild("spike_12", CubeListBuilder.create().texOffs(80, 23).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).texOffs(4, 28).addBox(-1.5F, -2.5F, -0.5F, 1F, 1F, 1F), PartPose.offsetAndRotation(4F, 4F, 4F, 2.2F, 0F, -0.6F));
        p0.addOrReplaceChild("left_fin", CubeListBuilder.create().texOffs(20, 23).addBox(0F, -2F, 0F, 3F, 4F, 0F), PartPose.offsetAndRotation(6F, 0F, -1F, 0F, 0.3F, 0F));
        p0.addOrReplaceChild("right_fin", CubeListBuilder.create().texOffs(26, 23).addBox(-3F, -2F, 0F, 3F, 4F, 0F), PartPose.offsetAndRotation(-6F, 0F, -1F, 0F, -0.3F, 0F));
        p0.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(76, 0).addBox(0F, -3F, 0F, 0F, 6F, 4F), PartPose.offsetAndRotation(0F, -0.5F, 6F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    public static LayerDefinition sculk_parasite() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-3F, -2.5F, -4F, 6F, 4F, 4F).texOffs(0, 21).addBox(-3.25F, -3F, -4.25F, 6.5F, 1F, 1.5F), PartPose.offsetAndRotation(0F, 21F, -6F, 0F, 0F, 0F));
        PartDefinition p1 = p0.addOrReplaceChild("left_mandible", CubeListBuilder.create().texOffs(14, 15).addBox(-0.6F, -0.6F, -2.6F, 1.2F, 1.2F, 2.6F).texOffs(60, 28).addBox(-1F, 0F, -1F, 0.4F, 0.4F, 0.4F).texOffs(0, 30).addBox(-1F, 0F, -2F, 0.4F, 0.4F, 0.4F), PartPose.offsetAndRotation(1.7F, 1F, -3.8F, 0F, -0.35F, 0F));
        p1.addOrReplaceChild("left_mandible_tip", CubeListBuilder.create().texOffs(18, 21).addBox(-0.45F, -0.45F, -2F, 0.9F, 0.9F, 2F), PartPose.offsetAndRotation(0F, 0F, -2.5F, 0F, 1.05F, 0F));
        p0.addOrReplaceChild("left_tendril", CubeListBuilder.create().texOffs(56, 0).addBox(-1F, -4F, 0F, 2F, 4F, 0F), PartPose.offsetAndRotation(1.8F, -2.5F, -1.5F, -0.5F, 0F, 0.45F));
        PartDefinition p4 = p0.addOrReplaceChild("right_mandible", CubeListBuilder.create().texOffs(24, 15).addBox(-0.6F, -0.6F, -2.6F, 1.2F, 1.2F, 2.6F).texOffs(4, 30).addBox(0.6F, 0F, -1F, 0.4F, 0.4F, 0.4F).texOffs(8, 30).addBox(0.6F, 0F, -2F, 0.4F, 0.4F, 0.4F), PartPose.offsetAndRotation(-1.7F, 1F, -3.8F, 0F, 0.35F, 0F));
        p4.addOrReplaceChild("right_mandible_tip", CubeListBuilder.create().texOffs(24, 21).addBox(-0.45F, -0.45F, -2F, 0.9F, 0.9F, 2F), PartPose.offsetAndRotation(0F, 0F, -2.5F, 0F, -1.05F, 0F));
        p0.addOrReplaceChild("right_tendril", CubeListBuilder.create().texOffs(60, 0).addBox(-1F, -4F, 0F, 2F, 4F, 0F), PartPose.offsetAndRotation(-1.8F, -2.5F, -1.5F, -0.5F, 0F, -0.45F));
        PartDefinition p7 = p0.addOrReplaceChild("segment_0", CubeListBuilder.create().texOffs(20, 0).addBox(-2.75F, -1.8F, 0F, 5.5F, 3.6F, 2.6F), PartPose.offsetAndRotation(0F, 0F, -0.3F, 0F, 0F, 0F));
        p7.addOrReplaceChild("spine_0", CubeListBuilder.create().texOffs(42, 21).addBox(-0.4F, -1.4F, -0.4F, 0.8F, 1.4F, 0.8F), PartPose.offsetAndRotation(0F, -1.8F, 1.2F, -0.55F, 0F, 0F));
        PartDefinition p9 = p7.addOrReplaceChild("left_leg_0", CubeListBuilder.create().texOffs(54, 21).addBox(0F, -0.4F, -0.4F, 2.6F, 0.8F, 0.8F), PartPose.offsetAndRotation(2.45F, 0.8F, 1.2F, 0F, 0.45F, 0.25F));
        p9.addOrReplaceChild("left_foot_0", CubeListBuilder.create().texOffs(40, 26).addBox(0F, -0.35F, -0.35F, 2F, 0.7F, 0.7F), PartPose.offsetAndRotation(2.5F, 0F, 0F, 0F, 0F, 0.85F));
        PartDefinition p11 = p7.addOrReplaceChild("right_leg_0", CubeListBuilder.create().texOffs(0, 24).addBox(-2.6F, -0.4F, -0.4F, 2.6F, 0.8F, 0.8F), PartPose.offsetAndRotation(-2.45F, 0.8F, 1.2F, 0F, -0.45F, -0.25F));
        p11.addOrReplaceChild("right_foot_0", CubeListBuilder.create().texOffs(46, 26).addBox(-2F, -0.35F, -0.35F, 2F, 0.7F, 0.7F), PartPose.offsetAndRotation(-2.5F, 0F, 0F, 0F, 0F, -0.85F));
        PartDefinition p13 = p7.addOrReplaceChild("segment_1", CubeListBuilder.create().texOffs(38, 0).addBox(-2.75F, -1.8F, 0F, 5.5F, 3.6F, 2.6F), PartPose.offsetAndRotation(0F, 0F, 2.2F, 0F, 0F, 0F));
        p13.addOrReplaceChild("spine_1", CubeListBuilder.create().texOffs(46, 21).addBox(-0.4F, -1.25F, -0.4F, 0.8F, 1.25F, 0.8F), PartPose.offsetAndRotation(0F, -1.8F, 1.2F, -0.55F, 0F, 0F));
        PartDefinition p15 = p13.addOrReplaceChild("left_leg_1", CubeListBuilder.create().texOffs(8, 24).addBox(0F, -0.4F, -0.4F, 2.6F, 0.8F, 0.8F), PartPose.offsetAndRotation(2.45F, 0.8F, 1.2F, 0F, 0.3F, 0.25F));
        p15.addOrReplaceChild("left_foot_1", CubeListBuilder.create().texOffs(52, 26).addBox(0F, -0.35F, -0.35F, 2F, 0.7F, 0.7F), PartPose.offsetAndRotation(2.5F, 0F, 0F, 0F, 0F, 0.85F));
        PartDefinition p17 = p13.addOrReplaceChild("right_leg_1", CubeListBuilder.create().texOffs(16, 24).addBox(-2.6F, -0.4F, -0.4F, 2.6F, 0.8F, 0.8F), PartPose.offsetAndRotation(-2.45F, 0.8F, 1.2F, 0F, -0.3F, -0.25F));
        p17.addOrReplaceChild("right_foot_1", CubeListBuilder.create().texOffs(58, 26).addBox(-2F, -0.35F, -0.35F, 2F, 0.7F, 0.7F), PartPose.offsetAndRotation(-2.5F, 0F, 0F, 0F, 0F, -0.85F));
        PartDefinition p19 = p13.addOrReplaceChild("segment_2", CubeListBuilder.create().texOffs(0, 8).addBox(-2.5F, -1.7F, 0F, 5F, 3.4F, 2.6F), PartPose.offsetAndRotation(0F, 0F, 2.2F, 0F, 0F, 0F));
        p19.addOrReplaceChild("spine_2", CubeListBuilder.create().texOffs(50, 21).addBox(-0.4F, -1.1F, -0.4F, 0.8F, 1.1F, 0.8F), PartPose.offsetAndRotation(0F, -1.7F, 1.2F, -0.55F, 0F, 0F));
        PartDefinition p21 = p19.addOrReplaceChild("left_leg_2", CubeListBuilder.create().texOffs(24, 24).addBox(0F, -0.4F, -0.4F, 2.6F, 0.8F, 0.8F), PartPose.offsetAndRotation(2.2F, 0.8F, 1.2F, 0F, 0.15F, 0.25F));
        p21.addOrReplaceChild("left_foot_2", CubeListBuilder.create().texOffs(0, 28).addBox(0F, -0.35F, -0.35F, 2F, 0.7F, 0.7F), PartPose.offsetAndRotation(2.5F, 0F, 0F, 0F, 0F, 0.85F));
        PartDefinition p23 = p19.addOrReplaceChild("right_leg_2", CubeListBuilder.create().texOffs(32, 24).addBox(-2.6F, -0.4F, -0.4F, 2.6F, 0.8F, 0.8F), PartPose.offsetAndRotation(-2.2F, 0.8F, 1.2F, 0F, -0.15F, -0.25F));
        p23.addOrReplaceChild("right_foot_2", CubeListBuilder.create().texOffs(6, 28).addBox(-2F, -0.35F, -0.35F, 2F, 0.7F, 0.7F), PartPose.offsetAndRotation(-2.5F, 0F, 0F, 0F, 0F, -0.85F));
        PartDefinition p25 = p19.addOrReplaceChild("segment_3", CubeListBuilder.create().texOffs(16, 8).addBox(-2.5F, -1.6F, 0F, 5F, 3.2F, 2.6F), PartPose.offsetAndRotation(0F, 0F, 2.2F, 0F, 0F, 0F));
        p25.addOrReplaceChild("spine_3", CubeListBuilder.create().texOffs(12, 30).addBox(-0.4F, -0.95F, -0.4F, 0.8F, 0.95F, 0.8F), PartPose.offsetAndRotation(0F, -1.6F, 1.2F, -0.55F, 0F, 0F));
        PartDefinition p27 = p25.addOrReplaceChild("left_leg_3", CubeListBuilder.create().texOffs(40, 24).addBox(0F, -0.4F, -0.4F, 2.6F, 0.8F, 0.8F), PartPose.offsetAndRotation(2.2F, 0.8F, 1.2F, 0F, 0F, 0.25F));
        p27.addOrReplaceChild("left_foot_3", CubeListBuilder.create().texOffs(12, 28).addBox(0F, -0.35F, -0.35F, 2F, 0.7F, 0.7F), PartPose.offsetAndRotation(2.5F, 0F, 0F, 0F, 0F, 0.85F));
        PartDefinition p29 = p25.addOrReplaceChild("right_leg_3", CubeListBuilder.create().texOffs(48, 24).addBox(-2.6F, -0.4F, -0.4F, 2.6F, 0.8F, 0.8F), PartPose.offsetAndRotation(-2.2F, 0.8F, 1.2F, 0F, 0F, -0.25F));
        p29.addOrReplaceChild("right_foot_3", CubeListBuilder.create().texOffs(18, 28).addBox(-2F, -0.35F, -0.35F, 2F, 0.7F, 0.7F), PartPose.offsetAndRotation(-2.5F, 0F, 0F, 0F, 0F, -0.85F));
        PartDefinition p31 = p25.addOrReplaceChild("segment_4", CubeListBuilder.create().texOffs(32, 8).addBox(-2.25F, -1.5F, 0F, 4.5F, 3F, 2.6F), PartPose.offsetAndRotation(0F, 0F, 2.2F, 0F, 0F, 0F));
        p31.addOrReplaceChild("spine_4", CubeListBuilder.create().texOffs(16, 30).addBox(-0.4F, -0.8F, -0.4F, 0.8F, 0.8F, 0.8F), PartPose.offsetAndRotation(0F, -1.5F, 1.2F, -0.55F, 0F, 0F));
        PartDefinition p33 = p31.addOrReplaceChild("left_leg_4", CubeListBuilder.create().texOffs(56, 24).addBox(0F, -0.4F, -0.4F, 2.6F, 0.8F, 0.8F), PartPose.offsetAndRotation(1.95F, 0.8F, 1.2F, 0F, -0.15F, 0.25F));
        p33.addOrReplaceChild("left_foot_4", CubeListBuilder.create().texOffs(24, 28).addBox(0F, -0.35F, -0.35F, 2F, 0.7F, 0.7F), PartPose.offsetAndRotation(2.5F, 0F, 0F, 0F, 0F, 0.85F));
        PartDefinition p35 = p31.addOrReplaceChild("right_leg_4", CubeListBuilder.create().texOffs(0, 26).addBox(-2.6F, -0.4F, -0.4F, 2.6F, 0.8F, 0.8F), PartPose.offsetAndRotation(-1.95F, 0.8F, 1.2F, 0F, 0.15F, -0.25F));
        p35.addOrReplaceChild("right_foot_4", CubeListBuilder.create().texOffs(30, 28).addBox(-2F, -0.35F, -0.35F, 2F, 0.7F, 0.7F), PartPose.offsetAndRotation(-2.5F, 0F, 0F, 0F, 0F, -0.85F));
        PartDefinition p37 = p31.addOrReplaceChild("segment_5", CubeListBuilder.create().texOffs(48, 8).addBox(-2F, -1.3F, 0F, 4F, 2.6F, 2.6F), PartPose.offsetAndRotation(0F, 0F, 2.2F, 0F, 0F, 0F));
        p37.addOrReplaceChild("spine_5", CubeListBuilder.create().texOffs(20, 30).addBox(-0.4F, -0.65F, -0.4F, 0.8F, 0.65F, 0.8F), PartPose.offsetAndRotation(0F, -1.3F, 1.2F, -0.55F, 0F, 0F));
        PartDefinition p39 = p37.addOrReplaceChild("left_leg_5", CubeListBuilder.create().texOffs(8, 26).addBox(0F, -0.4F, -0.4F, 2.6F, 0.8F, 0.8F), PartPose.offsetAndRotation(1.7F, 0.8F, 1.2F, 0F, -0.3F, 0.25F));
        p39.addOrReplaceChild("left_foot_5", CubeListBuilder.create().texOffs(36, 28).addBox(0F, -0.35F, -0.35F, 2F, 0.7F, 0.7F), PartPose.offsetAndRotation(2.5F, 0F, 0F, 0F, 0F, 0.85F));
        PartDefinition p41 = p37.addOrReplaceChild("right_leg_5", CubeListBuilder.create().texOffs(16, 26).addBox(-2.6F, -0.4F, -0.4F, 2.6F, 0.8F, 0.8F), PartPose.offsetAndRotation(-1.7F, 0.8F, 1.2F, 0F, 0.3F, -0.25F));
        p41.addOrReplaceChild("right_foot_5", CubeListBuilder.create().texOffs(42, 28).addBox(-2F, -0.35F, -0.35F, 2F, 0.7F, 0.7F), PartPose.offsetAndRotation(-2.5F, 0F, 0F, 0F, 0F, -0.85F));
        PartDefinition p43 = p37.addOrReplaceChild("segment_6", CubeListBuilder.create().texOffs(0, 15).addBox(-1.6F, -1.1F, 0F, 3.2F, 2.2F, 2.6F), PartPose.offsetAndRotation(0F, 0F, 2.2F, 0F, 0F, 0F));
        p43.addOrReplaceChild("spine_6", CubeListBuilder.create().texOffs(24, 30).addBox(-0.4F, -0.5F, -0.4F, 0.8F, 0.5F, 0.8F), PartPose.offsetAndRotation(0F, -1.1F, 1.2F, -0.55F, 0F, 0F));
        PartDefinition p45 = p43.addOrReplaceChild("left_leg_6", CubeListBuilder.create().texOffs(24, 26).addBox(0F, -0.4F, -0.4F, 2.6F, 0.8F, 0.8F), PartPose.offsetAndRotation(1.3F, 0.8F, 1.2F, 0F, -0.45F, 0.25F));
        p45.addOrReplaceChild("left_foot_6", CubeListBuilder.create().texOffs(48, 28).addBox(0F, -0.35F, -0.35F, 2F, 0.7F, 0.7F), PartPose.offsetAndRotation(2.5F, 0F, 0F, 0F, 0F, 0.85F));
        PartDefinition p47 = p43.addOrReplaceChild("right_leg_6", CubeListBuilder.create().texOffs(32, 26).addBox(-2.6F, -0.4F, -0.4F, 2.6F, 0.8F, 0.8F), PartPose.offsetAndRotation(-1.3F, 0.8F, 1.2F, 0F, 0.45F, -0.25F));
        p47.addOrReplaceChild("right_foot_6", CubeListBuilder.create().texOffs(54, 28).addBox(-2F, -0.35F, -0.35F, 2F, 0.7F, 0.7F), PartPose.offsetAndRotation(-2.5F, 0F, 0F, 0F, 0F, -0.85F));
        p43.addOrReplaceChild("left_cercus", CubeListBuilder.create().texOffs(34, 15).addBox(-0.3F, -0.3F, 0F, 0.6F, 0.6F, 3.5F), PartPose.offsetAndRotation(1F, 0.3F, 2.3F, -0.25F, 0.45F, 0F));
        p43.addOrReplaceChild("right_cercus", CubeListBuilder.create().texOffs(44, 15).addBox(-0.3F, -0.3F, 0F, 0.6F, 0.6F, 3.5F), PartPose.offsetAndRotation(-1F, 0.3F, 2.3F, -0.25F, -0.45F, 0F));
        PartDefinition p51 = p43.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(54, 15).addBox(-0.6F, -0.6F, 0F, 1.2F, 1.2F, 2.4F), PartPose.offsetAndRotation(0F, -0.5F, 2.2F, 0.8F, 0F, 0F));
        p51.addOrReplaceChild("stinger", CubeListBuilder.create().texOffs(30, 21).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 1.8F).texOffs(36, 21).addBox(-0.25F, -0.25F, 1.6F, 0.5F, 0.5F, 1.2F), PartPose.offsetAndRotation(0F, 0F, 2.3F, 0.7F, 0F, 0F));
        return LayerDefinition.create(mesh, 64, 64);
    }
}
