// GENERATED by tools/gen_models.py from tools/mobs.py - do not edit by hand.
package com.thesift.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

public final class ModelGeometry {
    private ModelGeometry() {
    }

    public static LayerDefinition bulb() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-4.5F, -6F, -4F, 9F, 6F, 8F), PartPose.offsetAndRotation(0F, 24F, 0F, 0F, 0F, 0F));
        PartDefinition p1 = p0.addOrReplaceChild("head", CubeListBuilder.create().texOffs(34, 0).addBox(-4F, -7F, -4F, 8F, 7F, 7F).texOffs(0, 14).addBox(-4.5F, -4F, -3.5F, 1F, 3F, 5F).texOffs(12, 14).addBox(3.5F, -4F, -3.5F, 1F, 3F, 5F), PartPose.offsetAndRotation(0F, -6F, -0.5F, 0F, 0F, 0F));
        p1.addOrReplaceChild("eyelids", CubeListBuilder.create().texOffs(46, 22).addBox(-4F, -6F, -4.02F, 8F, 3F, 0F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        PartDefinition p3 = p1.addOrReplaceChild("left_ear", CubeListBuilder.create().texOffs(24, 14).addBox(-1F, -5F, -0.5F, 2F, 5F, 1F), PartPose.offsetAndRotation(2.3F, -6.5F, 0.5F, -0.12F, 0F, 0.18F));
        p3.addOrReplaceChild("left_ear_tip", CubeListBuilder.create().texOffs(10, 22).addBox(-1F, -4F, -0.5F, 2F, 4F, 1F), PartPose.offsetAndRotation(0F, -5F, 0F, 0F, 0F, 0F));
        PartDefinition p5 = p1.addOrReplaceChild("right_ear", CubeListBuilder.create().texOffs(30, 14).addBox(-1F, -5F, -0.5F, 2F, 5F, 1F), PartPose.offsetAndRotation(-2.3F, -6.5F, 0.5F, -0.12F, 0F, -0.18F));
        p5.addOrReplaceChild("right_ear_tip", CubeListBuilder.create().texOffs(16, 22).addBox(-1F, -4F, -0.5F, 2F, 4F, 1F), PartPose.offsetAndRotation(0F, -5F, 0F, 0F, 0F, 0F));
        PartDefinition p7 = p1.addOrReplaceChild("stalk", CubeListBuilder.create().texOffs(60, 14).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F), PartPose.offsetAndRotation(0F, -7F, -1.5F, -0.25F, 0F, 0F));
        p7.addOrReplaceChild("lure", CubeListBuilder.create().texOffs(22, 22).addBox(-1F, -2F, -1F, 2F, 2F, 2F), PartPose.offsetAndRotation(0F, -3F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(0, 22).addBox(-1.5F, -1.5F, 0F, 3F, 3F, 2F), PartPose.offsetAndRotation(0F, -3F, 4F, 0F, 0F, 0F));
        p0.addOrReplaceChild("left_foot", CubeListBuilder.create().texOffs(36, 14).addBox(-1F, -1F, -2.5F, 2F, 1F, 4F), PartPose.offsetAndRotation(2.6F, 0F, 1.5F, 0F, 0F, 0F));
        p0.addOrReplaceChild("left_paw", CubeListBuilder.create().texOffs(30, 22).addBox(-1F, -1.5F, -1F, 2F, 1.5F, 2F), PartPose.offsetAndRotation(2.2F, 0F, -3.2F, 0F, 0F, 0F));
        p0.addOrReplaceChild("right_foot", CubeListBuilder.create().texOffs(48, 14).addBox(-1F, -1F, -2.5F, 2F, 1F, 4F), PartPose.offsetAndRotation(-2.6F, 0F, 1.5F, 0F, 0F, 0F));
        p0.addOrReplaceChild("right_paw", CubeListBuilder.create().texOffs(38, 22).addBox(-1F, -1.5F, -1F, 2F, 1.5F, 2F), PartPose.offsetAndRotation(-2.2F, 0F, -3.2F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition slumbler() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-8F, -5F, -11F, 16F, 9F, 22F), PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("crest", CubeListBuilder.create().texOffs(76, 0).addBox(0F, -4F, -9F, 0F, 4F, 18F), PartPose.offsetAndRotation(0F, -5F, 0F, 0F, 0F, 0F));
        PartDefinition p2 = p0.addOrReplaceChild("head", CubeListBuilder.create().texOffs(60, 31).addBox(-9F, -4F, -10F, 18F, 5F, 10F), PartPose.offsetAndRotation(0F, -1F, -11F, 0F, 0F, 0F));
        p2.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(34, 51).addBox(-9F, 0F, -10F, 18F, 3F, 10F), PartPose.offsetAndRotation(0F, 1F, 0F, 0F, 0F, 0F));
        PartDefinition p4 = p2.addOrReplaceChild("left_eye", CubeListBuilder.create().texOffs(116, 51).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(5.5F, -4F, -6F, 0F, 0F, 0F));
        p4.addOrReplaceChild("left_eyelid", CubeListBuilder.create().texOffs(18, 77).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F, new CubeDeformation(0.12F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        p2.addOrReplaceChild("left_gills", CubeListBuilder.create().texOffs(112, 0).addBox(0F, -5F, 0F, 5F, 8F, 0F), PartPose.offsetAndRotation(9F, -3F, -3F, 0F, -0.35F, 0F));
        PartDefinition p7 = p2.addOrReplaceChild("right_eye", CubeListBuilder.create().texOffs(30, 77).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(-5.5F, -4F, -6F, 0F, 0F, 0F));
        p7.addOrReplaceChild("right_eyelid", CubeListBuilder.create().texOffs(42, 77).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F, new CubeDeformation(0.12F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        p2.addOrReplaceChild("right_gills", CubeListBuilder.create().texOffs(116, 31).addBox(-5F, -5F, 0F, 5F, 8F, 0F), PartPose.offsetAndRotation(-9F, -3F, -3F, 0F, 0.35F, 0F));
        PartDefinition p10 = p0.addOrReplaceChild("left_front_leg", CubeListBuilder.create().texOffs(72, 65).addBox(0F, -1.5F, -2F, 5F, 3F, 4F), PartPose.offsetAndRotation(7.5F, 2.5F, -7F, 0F, 0F, 0F));
        p10.addOrReplaceChild("left_front_foot", CubeListBuilder.create().texOffs(0, 65).addBox(-2F, 0F, -2.5F, 4F, 7F, 5F), PartPose.offsetAndRotation(4.5F, 0.5F, 0F, 0F, 0F, 0F));
        PartDefinition p12 = p0.addOrReplaceChild("left_hind_leg", CubeListBuilder.create().texOffs(90, 65).addBox(0F, -1.5F, -2F, 5F, 3F, 4F), PartPose.offsetAndRotation(7.5F, 2.5F, 7F, 0F, 0F, 0F));
        p12.addOrReplaceChild("left_hind_foot", CubeListBuilder.create().texOffs(18, 65).addBox(-2F, 0F, -2.5F, 4F, 7F, 5F), PartPose.offsetAndRotation(4.5F, 0.5F, 0F, 0F, 0F, 0F));
        PartDefinition p14 = p0.addOrReplaceChild("right_front_leg", CubeListBuilder.create().texOffs(108, 65).addBox(-5F, -1.5F, -2F, 5F, 3F, 4F), PartPose.offsetAndRotation(-7.5F, 2.5F, -7F, 0F, 0F, 0F));
        p14.addOrReplaceChild("right_front_foot", CubeListBuilder.create().texOffs(36, 65).addBox(-2F, 0F, -2.5F, 4F, 7F, 5F), PartPose.offsetAndRotation(-4.5F, 0.5F, 0F, 0F, 0F, 0F));
        PartDefinition p16 = p0.addOrReplaceChild("right_hind_leg", CubeListBuilder.create().texOffs(0, 77).addBox(-5F, -1.5F, -2F, 5F, 3F, 4F), PartPose.offsetAndRotation(-7.5F, 2.5F, 7F, 0F, 0F, 0F));
        p16.addOrReplaceChild("right_hind_foot", CubeListBuilder.create().texOffs(54, 65).addBox(-2F, 0F, -2.5F, 4F, 7F, 5F), PartPose.offsetAndRotation(-4.5F, 0.5F, 0F, 0F, 0F, 0F));
        PartDefinition p18 = p0.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(20, 31).addBox(-5F, -3F, 0F, 10F, 6F, 10F), PartPose.offsetAndRotation(0F, -1F, 11F, 0F, 0F, 0F));
        PartDefinition p19 = p18.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(0, 51).addBox(-3.5F, -2F, 0F, 7F, 4F, 10F), PartPose.offsetAndRotation(0F, 0F, 10F, 0F, 0F, 0F));
        p19.addOrReplaceChild("tail3", CubeListBuilder.create().texOffs(90, 51).addBox(-2F, -1.5F, 0F, 4F, 3F, 9F).texOffs(0, 31).addBox(0F, -5F, 0F, 0F, 10F, 10F), PartPose.offsetAndRotation(0F, 0F, 10F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    public static LayerDefinition sifter() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-5F, -9F, -4.5F, 10F, 10F, 9F).texOffs(0, 19).addBox(-4F, -12F, -3.5F, 8F, 3F, 7F), PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(0, 29).addBox(-4.5F, -1F, -2F, 9F, 3F, 3F), PartPose.offsetAndRotation(0F, 0F, -4.5F, 0F, 0F, 0F));
        PartDefinition p2 = p0.addOrReplaceChild("left_antenna", CubeListBuilder.create().texOffs(38, 19).addBox(-0.5F, -6F, -0.5F, 1F, 6F, 1F), PartPose.offsetAndRotation(3.2F, -11.5F, -0.5F, -0.25F, 0F, 0.45F));
        p2.addOrReplaceChild("left_antenna_tip", CubeListBuilder.create().texOffs(24, 29).addBox(-1.5F, -3F, -0.5F, 3F, 3F, 1F), PartPose.offsetAndRotation(0F, -6F, 0F, 0F, 0F, 0F));
        PartDefinition p4 = p0.addOrReplaceChild("right_antenna", CubeListBuilder.create().texOffs(42, 19).addBox(-0.5F, -6F, -0.5F, 1F, 6F, 1F), PartPose.offsetAndRotation(-3.2F, -11.5F, -0.5F, -0.25F, 0F, -0.45F));
        p4.addOrReplaceChild("right_antenna_tip", CubeListBuilder.create().texOffs(32, 29).addBox(-1.5F, -3F, -0.5F, 3F, 3F, 1F), PartPose.offsetAndRotation(0F, -6F, 0F, 0F, 0F, 0F));
        p0.addOrReplaceChild("tentacle_0", CubeListBuilder.create().texOffs(46, 19).addBox(-0.5F, 0F, -0.5F, 1F, 4F, 1F), PartPose.offsetAndRotation(-3F, 0.5F, -1.6F, 0F, 0F, 0F));
        p0.addOrReplaceChild("tentacle_1", CubeListBuilder.create().texOffs(50, 19).addBox(-0.5F, 0F, -0.5F, 1F, 4F, 1F), PartPose.offsetAndRotation(-1F, 0.5F, -2.2F, 0F, 0F, 0F));
        p0.addOrReplaceChild("tentacle_2", CubeListBuilder.create().texOffs(54, 19).addBox(-0.5F, 0F, -0.5F, 1F, 4F, 1F), PartPose.offsetAndRotation(1F, 0.5F, -2.2F, 0F, 0F, 0F));
        p0.addOrReplaceChild("tentacle_3", CubeListBuilder.create().texOffs(58, 19).addBox(-0.5F, 0F, -0.5F, 1F, 4F, 1F), PartPose.offsetAndRotation(3F, 0.5F, -1.6F, 0F, 0F, 0F));
        p0.addOrReplaceChild("left_front_leg", CubeListBuilder.create().texOffs(38, 0).addBox(-1F, 0F, -1F, 2F, 8F, 2F), PartPose.offsetAndRotation(4.2F, -0.5F, -2.8F, 0F, 0F, -0.35F));
        p0.addOrReplaceChild("left_hind_leg", CubeListBuilder.create().texOffs(46, 0).addBox(-1F, 0F, -1F, 2F, 8F, 2F), PartPose.offsetAndRotation(4.2F, -0.5F, 2.8F, 0F, 0F, -0.35F));
        p0.addOrReplaceChild("right_front_leg", CubeListBuilder.create().texOffs(54, 0).addBox(-1F, 0F, -1F, 2F, 8F, 2F), PartPose.offsetAndRotation(-4.2F, -0.5F, -2.8F, 0F, 0F, 0.35F));
        p0.addOrReplaceChild("right_hind_leg", CubeListBuilder.create().texOffs(30, 19).addBox(-1F, 0F, -1F, 2F, 8F, 2F), PartPose.offsetAndRotation(-4.2F, -0.5F, 2.8F, 0F, 0F, 0.35F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition enchoer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(54, 0).addBox(-1.5F, 0F, -1.5F, 3F, 14F, 3F), PartPose.offsetAndRotation(2.3F, 10F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(66, 0).addBox(-1.5F, 0F, -1.5F, 3F, 14F, 3F), PartPose.offsetAndRotation(-2.3F, 10F, 0F, 0F, 0F, 0F));
        PartDefinition p2 = root.addOrReplaceChild("torso", CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -14F, -2.5F, 8F, 14F, 5F), PartPose.offsetAndRotation(0F, 10F, 0F, 0F, 0F, 0F));
        PartDefinition p3 = p2.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(24, 19).addBox(-1.5F, -1.5F, 0F, 3F, 3F, 6F), PartPose.offsetAndRotation(0F, -2F, 2.5F, 0.6F, 0F, 0F));
        p3.addOrReplaceChild("tail_tip", CubeListBuilder.create().texOffs(50, 19).addBox(-1F, -1F, 0F, 2F, 2F, 6F), PartPose.offsetAndRotation(0F, 0F, 6F, 0.3F, 0F, 0F));
        PartDefinition p5 = p2.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 19).addBox(-3F, -8F, -3F, 6F, 8F, 6F).texOffs(82, 19).addBox(-2F, -4F, -5F, 4F, 3F, 2F), PartPose.offsetAndRotation(0F, -14F, -0.5F, 0F, 0F, 0F));
        PartDefinition p6 = p5.addOrReplaceChild("left_antler", CubeListBuilder.create().texOffs(66, 19).addBox(-0.5F, -6F, -0.5F, 1F, 6F, 1F).texOffs(102, 19).addBox(0F, -4F, -0.5F, 2F, 1F, 1F), PartPose.offsetAndRotation(2F, -8F, 0F, -0.15F, 0F, 0.35F));
        p6.addOrReplaceChild("left_antler_tip", CubeListBuilder.create().texOffs(74, 19).addBox(-0.5F, -5F, -0.5F, 1F, 5F, 1F).texOffs(108, 19).addBox(0F, -3F, -0.5F, 2F, 1F, 1F).texOffs(94, 19).addBox(-0.5F, -7F, -0.5F, 1F, 2F, 1F), PartPose.offsetAndRotation(0F, -6F, 0F, 0F, 0F, -0.45F));
        PartDefinition p8 = p5.addOrReplaceChild("right_antler", CubeListBuilder.create().texOffs(70, 19).addBox(-0.5F, -6F, -0.5F, 1F, 6F, 1F).texOffs(114, 19).addBox(-2F, -4F, -0.5F, 2F, 1F, 1F), PartPose.offsetAndRotation(-2F, -8F, 0F, -0.15F, 0F, -0.35F));
        p8.addOrReplaceChild("right_antler_tip", CubeListBuilder.create().texOffs(78, 19).addBox(-0.5F, -5F, -0.5F, 1F, 5F, 1F).texOffs(120, 19).addBox(-2F, -3F, -0.5F, 2F, 1F, 1F).texOffs(98, 19).addBox(-0.5F, -7F, -0.5F, 1F, 2F, 1F), PartPose.offsetAndRotation(0F, -6F, 0F, 0F, 0F, 0.45F));
        PartDefinition p10 = p2.addOrReplaceChild("left_wing", CubeListBuilder.create().texOffs(110, 0).addBox(-1F, -1F, -1F, 2F, 10F, 2F).texOffs(26, 0).addBox(0F, 0F, 1F, 0F, 10F, 7F), PartPose.offsetAndRotation(4.2F, -13F, 0.5F, 0F, 0F, 0F));
        p10.addOrReplaceChild("left_wing_tip", CubeListBuilder.create().texOffs(42, 19).addBox(-0.5F, 0F, -0.5F, 1F, 8F, 1F).texOffs(78, 0).addBox(0F, 0F, 0.5F, 0F, 8F, 8F), PartPose.offsetAndRotation(0F, 9F, 0F, 0F, 0F, 0F));
        PartDefinition p12 = p2.addOrReplaceChild("right_wing", CubeListBuilder.create().texOffs(118, 0).addBox(-1F, -1F, -1F, 2F, 10F, 2F).texOffs(40, 0).addBox(0F, 0F, 1F, 0F, 10F, 7F), PartPose.offsetAndRotation(-4.2F, -13F, 0.5F, 0F, 0F, 0F));
        p12.addOrReplaceChild("right_wing_tip", CubeListBuilder.create().texOffs(46, 19).addBox(-0.5F, 0F, -0.5F, 1F, 8F, 1F).texOffs(94, 0).addBox(0F, 0F, 0.5F, 0F, 8F, 8F), PartPose.offsetAndRotation(0F, 9F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition riveter() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(16, 26).addBox(0.5F, 0F, -1F, 2F, 1F, 2F).texOffs(0, 26).addBox(1F, 1F, -0.5F, 1F, 3F, 1F).texOffs(24, 26).addBox(-2.5F, 0F, -1F, 2F, 1F, 2F).texOffs(4, 26).addBox(-2F, 1F, -0.5F, 1F, 3F, 1F).texOffs(0, 0).addBox(-3F, 4F, -2.5F, 6F, 9F, 5F), PartPose.offsetAndRotation(0F, 5F, 0F, 0F, 0F, 0F));
        PartDefinition p1 = p0.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 14).addBox(-3.5F, 0F, -3.5F, 7F, 5F, 7F), PartPose.offsetAndRotation(0F, 13F, -0.5F, 0F, 0F, 0F));
        p1.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(40, 14).addBox(-3F, 0F, -5.5F, 6F, 2F, 6F), PartPose.offsetAndRotation(0F, 4F, 2F, 0F, 0F, 0F));
        PartDefinition p3 = p1.addOrReplaceChild("left_horn", CubeListBuilder.create().texOffs(54, 0).addBox(-0.5F, 0F, -0.5F, 1F, 5F, 1F), PartPose.offsetAndRotation(3.5F, 1.5F, 0F, 0F, 0F, -0.6F));
        p3.addOrReplaceChild("left_horn_tip", CubeListBuilder.create().texOffs(8, 26).addBox(-0.5F, 0F, -0.5F, 1F, 3F, 1F), PartPose.offsetAndRotation(0F, 5F, 0F, 0F, 0F, 0.5F));
        PartDefinition p5 = p1.addOrReplaceChild("right_horn", CubeListBuilder.create().texOffs(58, 0).addBox(-0.5F, 0F, -0.5F, 1F, 5F, 1F), PartPose.offsetAndRotation(-3.5F, 1.5F, 0F, 0F, 0F, 0.6F));
        p5.addOrReplaceChild("right_horn_tip", CubeListBuilder.create().texOffs(12, 26).addBox(-0.5F, 0F, -0.5F, 1F, 3F, 1F), PartPose.offsetAndRotation(0F, 5F, 0F, 0F, 0F, -0.5F));
        PartDefinition p7 = p0.addOrReplaceChild("left_wing", CubeListBuilder.create().texOffs(22, 0).addBox(0F, 0F, 0F, 5F, 13F, 0F).texOffs(0, 30).addBox(0F, -0.5F, -0.5F, 5F, 1F, 1F), PartPose.offsetAndRotation(3F, 5F, 0.5F, 0F, -1F, 0F));
        p7.addOrReplaceChild("left_wing_tip", CubeListBuilder.create().texOffs(42, 0).addBox(0F, 0F, 0F, 6F, 12F, 0F).texOffs(32, 26).addBox(0F, -0.5F, -0.5F, 6F, 1F, 1F), PartPose.offsetAndRotation(5F, 0F, 0F, 0F, -1.2F, 0F));
        PartDefinition p9 = p0.addOrReplaceChild("right_wing", CubeListBuilder.create().texOffs(32, 0).addBox(-5F, 0F, 0F, 5F, 13F, 0F).texOffs(12, 30).addBox(-5F, -0.5F, -0.5F, 5F, 1F, 1F), PartPose.offsetAndRotation(-3F, 5F, 0.5F, 0F, 1F, 0F));
        p9.addOrReplaceChild("right_wing_tip", CubeListBuilder.create().texOffs(28, 14).addBox(-6F, 0F, 0F, 6F, 12F, 0F).texOffs(46, 26).addBox(-6F, -0.5F, -0.5F, 6F, 1F, 1F), PartPose.offsetAndRotation(-5F, 0F, 0F, 0F, 1.2F, 0F));
        return LayerDefinition.create(mesh, 64, 64);
    }
}
