// GENERATED by tools/gen_java.py from tools/spec.py - do not edit by hand.
package com.thesift.registry;

import com.thesift.TheSift;
import com.thesift.block.*;
import net.minecraft.util.ColorRGBA;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredRegister;

public final class ModBlocks {
    public static final DeferredRegister.Blocks BLOCKS = DeferredRegister.createBlocks(TheSift.MODID);

    public static final DeferredBlock<Block> DREAMSTONE = BLOCKS.registerBlock("dreamstone", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<StairBlock> DREAMSTONE_STAIRS = BLOCKS.registerBlock("dreamstone_stairs", p -> new StairBlock(DREAMSTONE.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<SlabBlock> DREAMSTONE_SLAB = BLOCKS.registerBlock("dreamstone_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<Block> COBBLED_DREAMSTONE = BLOCKS.registerBlock("cobbled_dreamstone", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<StairBlock> COBBLED_DREAMSTONE_STAIRS = BLOCKS.registerBlock("cobbled_dreamstone_stairs", p -> new StairBlock(COBBLED_DREAMSTONE.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<SlabBlock> COBBLED_DREAMSTONE_SLAB = BLOCKS.registerBlock("cobbled_dreamstone_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<WallBlock> COBBLED_DREAMSTONE_WALL = BLOCKS.registerBlock("cobbled_dreamstone_wall", WallBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<Block> POLISHED_DREAMSTONE = BLOCKS.registerBlock("polished_dreamstone", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<StairBlock> POLISHED_DREAMSTONE_STAIRS = BLOCKS.registerBlock("polished_dreamstone_stairs", p -> new StairBlock(POLISHED_DREAMSTONE.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<SlabBlock> POLISHED_DREAMSTONE_SLAB = BLOCKS.registerBlock("polished_dreamstone_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<WallBlock> POLISHED_DREAMSTONE_WALL = BLOCKS.registerBlock("polished_dreamstone_wall", WallBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<Block> DREAMSTONE_BRICKS = BLOCKS.registerBlock("dreamstone_bricks", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<StairBlock> DREAMSTONE_BRICK_STAIRS = BLOCKS.registerBlock("dreamstone_brick_stairs", p -> new StairBlock(DREAMSTONE_BRICKS.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<SlabBlock> DREAMSTONE_BRICK_SLAB = BLOCKS.registerBlock("dreamstone_brick_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<WallBlock> DREAMSTONE_BRICK_WALL = BLOCKS.registerBlock("dreamstone_brick_wall", WallBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<Block> CRACKED_DREAMSTONE_BRICKS = BLOCKS.registerBlock("cracked_dreamstone_bricks", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<Block> MOSSY_DREAMSTONE_BRICKS = BLOCKS.registerBlock("mossy_dreamstone_bricks", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<StairBlock> MOSSY_DREAMSTONE_BRICK_STAIRS = BLOCKS.registerBlock("mossy_dreamstone_brick_stairs", p -> new StairBlock(MOSSY_DREAMSTONE_BRICKS.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<SlabBlock> MOSSY_DREAMSTONE_BRICK_SLAB = BLOCKS.registerBlock("mossy_dreamstone_brick_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<WallBlock> MOSSY_DREAMSTONE_BRICK_WALL = BLOCKS.registerBlock("mossy_dreamstone_brick_wall", WallBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<Block> DREAMSTONE_TILES = BLOCKS.registerBlock("dreamstone_tiles", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<StairBlock> DREAMSTONE_TILE_STAIRS = BLOCKS.registerBlock("dreamstone_tile_stairs", p -> new StairBlock(DREAMSTONE_TILES.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<SlabBlock> DREAMSTONE_TILE_SLAB = BLOCKS.registerBlock("dreamstone_tile_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<WallBlock> DREAMSTONE_TILE_WALL = BLOCKS.registerBlock("dreamstone_tile_wall", WallBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<Block> CHISELED_DREAMSTONE = BLOCKS.registerBlock("chiseled_dreamstone", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<RotatedPillarBlock> DREAMSTONE_PILLAR = BLOCKS.registerBlock("dreamstone_pillar", RotatedPillarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<RotatedPillarBlock> HUSHSLATE = BLOCKS.registerBlock("hushslate", RotatedPillarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<Block> COBBLED_HUSHSLATE = BLOCKS.registerBlock("cobbled_hushslate", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<StairBlock> COBBLED_HUSHSLATE_STAIRS = BLOCKS.registerBlock("cobbled_hushslate_stairs", p -> new StairBlock(COBBLED_HUSHSLATE.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<SlabBlock> COBBLED_HUSHSLATE_SLAB = BLOCKS.registerBlock("cobbled_hushslate_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<WallBlock> COBBLED_HUSHSLATE_WALL = BLOCKS.registerBlock("cobbled_hushslate_wall", WallBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<Block> POLISHED_HUSHSLATE = BLOCKS.registerBlock("polished_hushslate", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<StairBlock> POLISHED_HUSHSLATE_STAIRS = BLOCKS.registerBlock("polished_hushslate_stairs", p -> new StairBlock(POLISHED_HUSHSLATE.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<SlabBlock> POLISHED_HUSHSLATE_SLAB = BLOCKS.registerBlock("polished_hushslate_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<WallBlock> POLISHED_HUSHSLATE_WALL = BLOCKS.registerBlock("polished_hushslate_wall", WallBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<Block> HUSHSLATE_BRICKS = BLOCKS.registerBlock("hushslate_bricks", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<StairBlock> HUSHSLATE_BRICK_STAIRS = BLOCKS.registerBlock("hushslate_brick_stairs", p -> new StairBlock(HUSHSLATE_BRICKS.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<SlabBlock> HUSHSLATE_BRICK_SLAB = BLOCKS.registerBlock("hushslate_brick_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<WallBlock> HUSHSLATE_BRICK_WALL = BLOCKS.registerBlock("hushslate_brick_wall", WallBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<Block> CRACKED_HUSHSLATE_BRICKS = BLOCKS.registerBlock("cracked_hushslate_bricks", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<Block> HUSHSLATE_TILES = BLOCKS.registerBlock("hushslate_tiles", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<StairBlock> HUSHSLATE_TILE_STAIRS = BLOCKS.registerBlock("hushslate_tile_stairs", p -> new StairBlock(HUSHSLATE_TILES.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<SlabBlock> HUSHSLATE_TILE_SLAB = BLOCKS.registerBlock("hushslate_tile_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<WallBlock> HUSHSLATE_TILE_WALL = BLOCKS.registerBlock("hushslate_tile_wall", WallBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<Block> CHISELED_HUSHSLATE = BLOCKS.registerBlock("chiseled_hushslate", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<ColoredFallingBlock> DREAMSAND = BLOCKS.registerBlock("dreamsand", p -> new ColoredFallingBlock(new ColorRGBA(0xF2A7C3), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SAND).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<SuspiciousDreamsandBlock> SUSPICIOUS_DREAMSAND = BLOCKS.registerBlock("suspicious_dreamsand", SuspiciousDreamsandBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SUSPICIOUS_SAND).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<Block> DREAMSANDSTONE = BLOCKS.registerBlock("dreamsandstone", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<StairBlock> DREAMSANDSTONE_STAIRS = BLOCKS.registerBlock("dreamsandstone_stairs", p -> new StairBlock(DREAMSANDSTONE.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<SlabBlock> DREAMSANDSTONE_SLAB = BLOCKS.registerBlock("dreamsandstone_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<WallBlock> DREAMSANDSTONE_WALL = BLOCKS.registerBlock("dreamsandstone_wall", WallBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<Block> SMOOTH_DREAMSANDSTONE = BLOCKS.registerBlock("smooth_dreamsandstone", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<StairBlock> SMOOTH_DREAMSANDSTONE_STAIRS = BLOCKS.registerBlock("smooth_dreamsandstone_stairs", p -> new StairBlock(SMOOTH_DREAMSANDSTONE.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<SlabBlock> SMOOTH_DREAMSANDSTONE_SLAB = BLOCKS.registerBlock("smooth_dreamsandstone_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<Block> CUT_DREAMSANDSTONE = BLOCKS.registerBlock("cut_dreamsandstone", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<SlabBlock> CUT_DREAMSANDSTONE_SLAB = BLOCKS.registerBlock("cut_dreamsandstone_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<Block> CHISELED_DREAMSANDSTONE = BLOCKS.registerBlock("chiseled_dreamsandstone", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<Block> BLUSH_BRICKS = BLOCKS.registerBlock("blush_bricks", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BRICKS).mapColor(MapColor.COLOR_RED));
    public static final DeferredBlock<StairBlock> BLUSH_BRICK_STAIRS = BLOCKS.registerBlock("blush_brick_stairs", p -> new StairBlock(BLUSH_BRICKS.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BRICKS).mapColor(MapColor.COLOR_RED));
    public static final DeferredBlock<SlabBlock> BLUSH_BRICK_SLAB = BLOCKS.registerBlock("blush_brick_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BRICKS).mapColor(MapColor.COLOR_RED));
    public static final DeferredBlock<WallBlock> BLUSH_BRICK_WALL = BLOCKS.registerBlock("blush_brick_wall", WallBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BRICKS).mapColor(MapColor.COLOR_RED));
    public static final DeferredBlock<Block> CRACKED_BLUSH_BRICKS = BLOCKS.registerBlock("cracked_blush_bricks", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BRICKS).mapColor(MapColor.COLOR_RED));
    public static final DeferredBlock<Block> CHISELED_BLUSH_BRICKS = BLOCKS.registerBlock("chiseled_blush_bricks", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BRICKS).mapColor(MapColor.COLOR_RED));
    public static final DeferredBlock<Block> SIFT_SOIL = BLOCKS.registerBlock("sift_soil", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT).mapColor(MapColor.TERRACOTTA_PINK));
    public static final DeferredBlock<SiftGrassBlock> SIFT_GRASS_BLOCK = BLOCKS.registerBlock("sift_grass_block", SiftGrassBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.GRASS_BLOCK).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<SiftGrassBlock> CORAL_TURF = BLOCKS.registerBlock("coral_turf", SiftGrassBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.GRASS_BLOCK).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<LumenMossBlock> LUMEN_MOSS_BLOCK = BLOCKS.registerBlock("lumen_moss_block", LumenMossBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.MOSS_BLOCK).mapColor(MapColor.COLOR_CYAN).lightLevel(s -> 6));
    public static final DeferredBlock<CarpetBlock> LUMEN_MOSS_CARPET = BLOCKS.registerBlock("lumen_moss_carpet", CarpetBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.MOSS_CARPET).mapColor(MapColor.COLOR_CYAN).lightLevel(s -> 4));
    public static final DeferredBlock<DropExperienceBlock> SIFTITE_ORE = BLOCKS.registerBlock("siftite_ore", p -> new DropExperienceBlock(UniformInt.of(1, 4), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.COLOR_LIGHT_BLUE).strength(3.0F, 3.0F).requiresCorrectToolForDrops());
    public static final DeferredBlock<DropExperienceBlock> DEEP_SIFTITE_ORE = BLOCKS.registerBlock("deep_siftite_ore", p -> new DropExperienceBlock(UniformInt.of(1, 4), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.COLOR_CYAN).strength(4.5F, 3.0F).requiresCorrectToolForDrops());
    public static final DeferredBlock<Block> SIFTITE_BLOCK = BLOCKS.registerBlock("siftite_block", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.NETHERITE_BLOCK).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<TransparentBlock> CHROME_GLASS = BLOCKS.registerBlock("chrome_glass", TransparentBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS).mapColor(MapColor.COLOR_LIGHT_BLUE).lightLevel(s -> 3));
    public static final DeferredBlock<RotatedPillarBlock> LULLWOOD_LOG = BLOCKS.registerBlock("lullwood_log", RotatedPillarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG).mapColor(MapColor.COLOR_GRAY));
    public static final DeferredBlock<RotatedPillarBlock> LULLWOOD_WOOD = BLOCKS.registerBlock("lullwood_wood", RotatedPillarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG).mapColor(MapColor.COLOR_GRAY));
    public static final DeferredBlock<RotatedPillarBlock> STRIPPED_LULLWOOD_LOG = BLOCKS.registerBlock("stripped_lullwood_log", RotatedPillarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG).mapColor(MapColor.COLOR_GRAY));
    public static final DeferredBlock<RotatedPillarBlock> STRIPPED_LULLWOOD_WOOD = BLOCKS.registerBlock("stripped_lullwood_wood", RotatedPillarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG).mapColor(MapColor.COLOR_GRAY));
    public static final DeferredBlock<Block> LULLWOOD_PLANKS = BLOCKS.registerBlock("lullwood_planks", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_LIGHT_GRAY));
    public static final DeferredBlock<StairBlock> LULLWOOD_STAIRS = BLOCKS.registerBlock("lullwood_stairs", p -> new StairBlock(LULLWOOD_PLANKS.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_LIGHT_GRAY));
    public static final DeferredBlock<SlabBlock> LULLWOOD_SLAB = BLOCKS.registerBlock("lullwood_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_LIGHT_GRAY));
    public static final DeferredBlock<FenceBlock> LULLWOOD_FENCE = BLOCKS.registerBlock("lullwood_fence", FenceBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_LIGHT_GRAY));
    public static final DeferredBlock<FenceGateBlock> LULLWOOD_FENCE_GATE = BLOCKS.registerBlock("lullwood_fence_gate", p -> new FenceGateBlock(ModWoodTypes.LULLWOOD, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_LIGHT_GRAY));
    public static final DeferredBlock<DoorBlock> LULLWOOD_DOOR = BLOCKS.registerBlock("lullwood_door", p -> new DoorBlock(ModWoodTypes.LULLWOOD_SET, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_LIGHT_GRAY).noOcclusion());
    public static final DeferredBlock<TrapDoorBlock> LULLWOOD_TRAPDOOR = BLOCKS.registerBlock("lullwood_trapdoor", p -> new TrapDoorBlock(ModWoodTypes.LULLWOOD_SET, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_LIGHT_GRAY).noOcclusion());
    public static final DeferredBlock<ButtonBlock> LULLWOOD_BUTTON = BLOCKS.registerBlock("lullwood_button", p -> new ButtonBlock(ModWoodTypes.LULLWOOD_SET, 30, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_BUTTON));
    public static final DeferredBlock<PressurePlateBlock> LULLWOOD_PRESSURE_PLATE = BLOCKS.registerBlock("lullwood_pressure_plate", p -> new PressurePlateBlock(ModWoodTypes.LULLWOOD_SET, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PRESSURE_PLATE));
    public static final DeferredBlock<SiftLeavesBlock> LULLWOOD_LEAVES = BLOCKS.registerBlock("lullwood_leaves", p -> new SiftLeavesBlock(0.03F, () -> ModParticles.LULLWOOD_LEAF.get(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.PALE_OAK_LEAVES).mapColor(MapColor.SNOW));
    public static final DeferredBlock<SiftSaplingBlock> LULLWOOD_SAPLING = BLOCKS.registerBlock("lullwood_sapling", p -> new SiftSaplingBlock(ModTreeGrowers.LULLWOOD, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SAPLING));
    public static final DeferredBlock<FlowerPotBlock> POTTED_LULLWOOD_SAPLING = BLOCKS.registerBlock("potted_lullwood_sapling", p -> new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, LULLWOOD_SAPLING, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POTTED_OAK_SAPLING));
    public static final DeferredBlock<RotatedPillarBlock> WISHWOOD_LOG = BLOCKS.registerBlock("wishwood_log", RotatedPillarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<RotatedPillarBlock> WISHWOOD_WOOD = BLOCKS.registerBlock("wishwood_wood", RotatedPillarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<RotatedPillarBlock> STRIPPED_WISHWOOD_LOG = BLOCKS.registerBlock("stripped_wishwood_log", RotatedPillarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<RotatedPillarBlock> STRIPPED_WISHWOOD_WOOD = BLOCKS.registerBlock("stripped_wishwood_wood", RotatedPillarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<Block> WISHWOOD_PLANKS = BLOCKS.registerBlock("wishwood_planks", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<StairBlock> WISHWOOD_STAIRS = BLOCKS.registerBlock("wishwood_stairs", p -> new StairBlock(WISHWOOD_PLANKS.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<SlabBlock> WISHWOOD_SLAB = BLOCKS.registerBlock("wishwood_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<FenceBlock> WISHWOOD_FENCE = BLOCKS.registerBlock("wishwood_fence", FenceBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<FenceGateBlock> WISHWOOD_FENCE_GATE = BLOCKS.registerBlock("wishwood_fence_gate", p -> new FenceGateBlock(ModWoodTypes.WISHWOOD, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<DoorBlock> WISHWOOD_DOOR = BLOCKS.registerBlock("wishwood_door", p -> new DoorBlock(ModWoodTypes.WISHWOOD_SET, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_PINK).noOcclusion());
    public static final DeferredBlock<TrapDoorBlock> WISHWOOD_TRAPDOOR = BLOCKS.registerBlock("wishwood_trapdoor", p -> new TrapDoorBlock(ModWoodTypes.WISHWOOD_SET, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_PINK).noOcclusion());
    public static final DeferredBlock<ButtonBlock> WISHWOOD_BUTTON = BLOCKS.registerBlock("wishwood_button", p -> new ButtonBlock(ModWoodTypes.WISHWOOD_SET, 30, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_BUTTON));
    public static final DeferredBlock<PressurePlateBlock> WISHWOOD_PRESSURE_PLATE = BLOCKS.registerBlock("wishwood_pressure_plate", p -> new PressurePlateBlock(ModWoodTypes.WISHWOOD_SET, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PRESSURE_PLATE));
    public static final DeferredBlock<SiftLeavesBlock> WISHWOOD_LEAVES = BLOCKS.registerBlock("wishwood_leaves", p -> new SiftLeavesBlock(0.02F, () -> ModParticles.WISHWOOD_LEAF.get(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.CHERRY_LEAVES).mapColor(MapColor.COLOR_LIGHT_BLUE));
    public static final DeferredBlock<SiftSaplingBlock> WISHWOOD_SAPLING = BLOCKS.registerBlock("wishwood_sapling", p -> new SiftSaplingBlock(ModTreeGrowers.WISHWOOD, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SAPLING));
    public static final DeferredBlock<FlowerPotBlock> POTTED_WISHWOOD_SAPLING = BLOCKS.registerBlock("potted_wishwood_sapling", p -> new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, WISHWOOD_SAPLING, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POTTED_OAK_SAPLING));
    public static final DeferredBlock<RotatedPillarBlock> BLIGHTWOOD_LOG = BLOCKS.registerBlock("blightwood_log", RotatedPillarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG).mapColor(MapColor.COLOR_BLACK));
    public static final DeferredBlock<RotatedPillarBlock> BLIGHTWOOD_WOOD = BLOCKS.registerBlock("blightwood_wood", RotatedPillarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG).mapColor(MapColor.COLOR_BLACK));
    public static final DeferredBlock<RotatedPillarBlock> STRIPPED_BLIGHTWOOD_LOG = BLOCKS.registerBlock("stripped_blightwood_log", RotatedPillarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG).mapColor(MapColor.COLOR_BLACK));
    public static final DeferredBlock<RotatedPillarBlock> STRIPPED_BLIGHTWOOD_WOOD = BLOCKS.registerBlock("stripped_blightwood_wood", RotatedPillarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG).mapColor(MapColor.COLOR_BLACK));
    public static final DeferredBlock<Block> BLIGHTWOOD_PLANKS = BLOCKS.registerBlock("blightwood_planks", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<StairBlock> BLIGHTWOOD_STAIRS = BLOCKS.registerBlock("blightwood_stairs", p -> new StairBlock(BLIGHTWOOD_PLANKS.get().defaultBlockState(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<SlabBlock> BLIGHTWOOD_SLAB = BLOCKS.registerBlock("blightwood_slab", SlabBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<FenceBlock> BLIGHTWOOD_FENCE = BLOCKS.registerBlock("blightwood_fence", FenceBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<FenceGateBlock> BLIGHTWOOD_FENCE_GATE = BLOCKS.registerBlock("blightwood_fence_gate", p -> new FenceGateBlock(ModWoodTypes.BLIGHTWOOD, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<DoorBlock> BLIGHTWOOD_DOOR = BLOCKS.registerBlock("blightwood_door", p -> new DoorBlock(ModWoodTypes.BLIGHTWOOD_SET, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_CYAN).noOcclusion());
    public static final DeferredBlock<TrapDoorBlock> BLIGHTWOOD_TRAPDOOR = BLOCKS.registerBlock("blightwood_trapdoor", p -> new TrapDoorBlock(ModWoodTypes.BLIGHTWOOD_SET, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS).mapColor(MapColor.COLOR_CYAN).noOcclusion());
    public static final DeferredBlock<ButtonBlock> BLIGHTWOOD_BUTTON = BLOCKS.registerBlock("blightwood_button", p -> new ButtonBlock(ModWoodTypes.BLIGHTWOOD_SET, 30, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_BUTTON));
    public static final DeferredBlock<PressurePlateBlock> BLIGHTWOOD_PRESSURE_PLATE = BLOCKS.registerBlock("blightwood_pressure_plate", p -> new PressurePlateBlock(ModWoodTypes.BLIGHTWOOD_SET, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PRESSURE_PLATE));
    public static final DeferredBlock<SiftLeavesBlock> BLIGHTWOOD_LEAVES = BLOCKS.registerBlock("blightwood_leaves", p -> new SiftLeavesBlock(0.025F, () -> ModParticles.GLOW_DUST.get(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DARK_OAK_LEAVES).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<SiftSaplingBlock> BLIGHTWOOD_SAPLING = BLOCKS.registerBlock("blightwood_sapling", p -> new SiftSaplingBlock(ModTreeGrowers.BLIGHTWOOD, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SAPLING));
    public static final DeferredBlock<FlowerPotBlock> POTTED_BLIGHTWOOD_SAPLING = BLOCKS.registerBlock("potted_blightwood_sapling", p -> new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, BLIGHTWOOD_SAPLING, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POTTED_OAK_SAPLING));
    public static final DeferredBlock<HangingLullwoodLeavesBlock> HANGING_LULLWOOD_LEAVES = BLOCKS.registerBlock("hanging_lullwood_leaves", HangingLullwoodLeavesBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.PALE_HANGING_MOSS).mapColor(MapColor.SNOW));
    public static final DeferredBlock<BlushgrassBlock> BLUSHGRASS = BLOCKS.registerBlock("blushgrass", BlushgrassBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SHORT_GRASS).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<SiftDoublePlantBlock> TALL_BLUSHGRASS = BLOCKS.registerBlock("tall_blushgrass", SiftDoublePlantBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SHORT_GRASS).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<SiftPlantBlock> CORAL_BUSH = BLOCKS.registerBlock("coral_bush", SiftPlantBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SHORT_GRASS).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<SiftDoublePlantBlock> CORAL_THICKET = BLOCKS.registerBlock("coral_thicket", SiftDoublePlantBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SHORT_GRASS).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<SiftPlantBlock> GLIMMER_SPROUTS = BLOCKS.registerBlock("glimmer_sprouts", SiftPlantBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SHORT_GRASS).mapColor(MapColor.COLOR_PINK).lightLevel(s -> 5));
    public static final DeferredBlock<SiftFlowerBlock> LULLABY_BELL = BLOCKS.registerBlock("lullaby_bell", p -> new SiftFlowerBlock(MobEffects.REGENERATION, 4.0F, 0, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POPPY));
    public static final DeferredBlock<FlowerPotBlock> POTTED_LULLABY_BELL = BLOCKS.registerBlock("potted_lullaby_bell", p -> new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, LULLABY_BELL, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POTTED_POPPY));
    public static final DeferredBlock<SiftFlowerBlock> DREAMBLOOM = BLOCKS.registerBlock("dreambloom", p -> new SiftFlowerBlock(MobEffects.JUMP_BOOST, 6.0F, 0, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POPPY));
    public static final DeferredBlock<FlowerPotBlock> POTTED_DREAMBLOOM = BLOCKS.registerBlock("potted_dreambloom", p -> new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, DREAMBLOOM, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POTTED_POPPY));
    public static final DeferredBlock<SiftFlowerBlock> SOULPETAL = BLOCKS.registerBlock("soulpetal", p -> new SiftFlowerBlock(MobEffects.NIGHT_VISION, 5.0F, 7, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POPPY));
    public static final DeferredBlock<FlowerPotBlock> POTTED_SOULPETAL = BLOCKS.registerBlock("potted_soulpetal", p -> new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, SOULPETAL, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POTTED_POPPY).lightLevel(s -> 7));
    public static final DeferredBlock<SiftFlowerBlock> NEBULA_IRIS = BLOCKS.registerBlock("nebula_iris", p -> new SiftFlowerBlock(MobEffects.SLOW_FALLING, 6.0F, 0, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POPPY));
    public static final DeferredBlock<FlowerPotBlock> POTTED_NEBULA_IRIS = BLOCKS.registerBlock("potted_nebula_iris", p -> new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, NEBULA_IRIS, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POTTED_POPPY));
    public static final DeferredBlock<SiftFlowerBlock> HUMMINGBLOOM = BLOCKS.registerBlock("hummingbloom", p -> new SiftFlowerBlock(MobEffects.SPEED, 5.0F, 0, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POPPY));
    public static final DeferredBlock<EchoOrchidBlock> ECHO_ORCHID = BLOCKS.registerBlock("echo_orchid", EchoOrchidBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POPPY).lightLevel(s -> 9));
    public static final DeferredBlock<EchoOrchidCropBlock> ECHO_ORCHID_CROP = BLOCKS.registerBlock("echo_orchid_crop", EchoOrchidCropBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.TORCHFLOWER_CROP));
    public static final DeferredBlock<ChromeReedsBlock> CHROME_REEDS = BLOCKS.registerBlock("chrome_reeds", ChromeReedsBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SUGAR_CANE).mapColor(MapColor.COLOR_LIGHT_BLUE));
    public static final DeferredBlock<GlowcapBlock> GLOWCAP = BLOCKS.registerBlock("glowcap", GlowcapBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BROWN_MUSHROOM).mapColor(MapColor.COLOR_CYAN).lightLevel(s -> 10));
    public static final DeferredBlock<GlowbellVineBlock> GLOWBELL_VINE = BLOCKS.registerBlock("glowbell_vine", GlowbellVineBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.CAVE_VINES).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<GlowbellVinePlantBlock> GLOWBELL_VINE_PLANT = BLOCKS.registerBlock("glowbell_vine_plant", GlowbellVinePlantBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.CAVE_VINES_PLANT).mapColor(MapColor.COLOR_CYAN));
    public static final DeferredBlock<SiftDrumBlock> SIFT_DRUM = BLOCKS.registerBlock("sift_drum", SiftDrumBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.NOTE_BLOCK).mapColor(MapColor.WOOD).noOcclusion());
    public static final DeferredBlock<SiftGateFrameBlock> SIFT_GATE_FRAME = BLOCKS.registerBlock("sift_gate_frame", SiftGateFrameBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN).strength(30.0F, 1200.0F).requiresCorrectToolForDrops().lightLevel(s -> 3));
    public static final DeferredBlock<SiftPortalBlock> SIFT_PORTAL = BLOCKS.registerBlock("sift_portal", SiftPortalBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.NETHER_PORTAL).lightLevel(s -> 12));
    public static final DeferredBlock<ConductorsPodiumBlock> CONDUCTORS_PODIUM = BLOCKS.registerBlock("conductors_podium", ConductorsPodiumBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN).strength(-1.0F, 3600000.0F).lightLevel(s -> 7));
    public static final DeferredBlock<EncoreSigilBlock> ENCORE_SIGIL = BLOCKS.registerBlock("encore_sigil", EncoreSigilBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_PURPLE).strength(-1.0F, 3600000.0F).lightLevel(s -> 6));
    public static final DeferredBlock<InstrumentAltarBlock> INSTRUMENT_ALTAR = BLOCKS.registerBlock("instrument_altar", InstrumentAltarBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN).strength(-1.0F, 3600000.0F).lightLevel(s -> 8).noOcclusion());
    public static final DeferredBlock<GlyphStoneBlock> GLYPH_STONE = BLOCKS.registerBlock("glyph_stone", GlyphStoneBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND));
    public static final DeferredBlock<AncientCannonBlock> ANCIENT_CANNON = BLOCKS.registerBlock("ancient_cannon", AncientCannonBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK).mapColor(MapColor.COLOR_ORANGE).strength(5.0F, 6.0F).noOcclusion());
    public static final DeferredBlock<CrumblingDreamstoneBlock> CRUMBLING_DREAMSTONE = BLOCKS.registerBlock("crumbling_dreamstone", CrumblingDreamstoneBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.SAND).strength(0.8F));
    public static final DeferredBlock<SiftCakeBlock> SIFT_CAKE = BLOCKS.registerBlock("sift_cake", SiftCakeBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.CAKE).lightLevel(s -> 6));
    public static final DeferredBlock<BulbLanternBlock> BULB_LANTERN = BLOCKS.registerBlock("bulb_lantern", BulbLanternBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.LANTERN).lightLevel(s -> 15));
    public static final DeferredBlock<GlowingSlimeBlock> GLOWING_SLIME_BLOCK = BLOCKS.registerBlock("glowing_slime_block", GlowingSlimeBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SLIME_BLOCK).mapColor(MapColor.COLOR_LIGHT_BLUE).lightLevel(s -> 12));
    public static final DeferredBlock<SoulChimeBlock> SOUL_CHIME = BLOCKS.registerBlock("soul_chime", SoulChimeBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_CHAIN).mapColor(MapColor.COLOR_LIGHT_BLUE).lightLevel(s -> 6).noOcclusion());
    public static final DeferredBlock<MusicalCobwebBlock> MUSICAL_COBWEB = BLOCKS.registerBlock("musical_cobweb", MusicalCobwebBlock::new,
            () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_CYAN).sound(net.minecraft.world.level.block.SoundType.COBWEB).noCollision().strength(1.0F).pushReaction(net.minecraft.world.level.material.PushReaction.POPPED).lightLevel(s -> s.getValue(com.thesift.block.MusicalCobwebBlock.RINGING) ? 12 : 6));
    public static final DeferredBlock<LingeringGlowBlock> LINGERING_GLOW = BLOCKS.registerBlock("lingering_glow", LingeringGlowBlock::new,
            () -> BlockBehaviour.Properties.of().replaceable().noCollision().noLootTable().noOcclusion().instabreak().lightLevel(s -> 15).pushReaction(net.minecraft.world.level.material.PushReaction.POPPED));
    public static final DeferredBlock<ChromeLiquidBlock> CHROME = BLOCKS.registerBlock("chrome", ChromeLiquidBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).mapColor(MapColor.COLOR_LIGHT_BLUE).lightLevel(s -> 8));
    public static final DeferredBlock<BandTableBlock> BAND_TABLE = BLOCKS.registerBlock("band_table", BandTableBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.NOTE_BLOCK).mapColor(MapColor.WOOD).strength(2.5F).lightLevel(s -> 6).noOcclusion());
    public static final DeferredBlock<PitcherPlanterBlock> PITCHER_PLANTER = BLOCKS.registerBlock("pitcher_planter", PitcherPlanterBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DECORATED_POT).mapColor(MapColor.TERRACOTTA_PINK).strength(1.0F).lightLevel(s -> s.getValue(com.thesift.block.PitcherPlanterBlock.STAGE) == 4 ? 6 : 0).noOcclusion());
    public static final DeferredBlock<DropExperienceBlock> PRISM_ORE = BLOCKS.registerBlock("prism_ore", p -> new DropExperienceBlock(UniformInt.of(1, 4), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.COLOR_MAGENTA).strength(3.0F, 3.0F).requiresCorrectToolForDrops());
    public static final DeferredBlock<DropExperienceBlock> DEEP_PRISM_ORE = BLOCKS.registerBlock("deep_prism_ore", p -> new DropExperienceBlock(UniformInt.of(1, 4), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.COLOR_MAGENTA).strength(4.5F, 3.0F).requiresCorrectToolForDrops());
    public static final DeferredBlock<Block> PRISM_BLOCK = BLOCKS.registerBlock("prism_block", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_BLOCK).mapColor(MapColor.COLOR_MAGENTA).lightLevel(s -> 4));
    public static final DeferredBlock<MusicCrystalBlock> MUSIC_CRYSTAL = BLOCKS.registerBlock("music_crystal", MusicCrystalBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.AMETHYST_CLUSTER).mapColor(MapColor.COLOR_PURPLE).strength(1.5F).lightLevel(s -> s.getValue(com.thesift.block.MusicCrystalBlock.FROZEN) ? 10 : 7).noOcclusion());
    public static final DeferredBlock<EggLadenOreBlock> EGG_LADEN_ORE = BLOCKS.registerBlock("egg_laden_ore", EggLadenOreBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.COLOR_ORANGE).strength(3.0F, 3.0F).requiresCorrectToolForDrops().lightLevel(s -> 3));
    public static final DeferredBlock<EggLadenOreBlock> DEEP_EGG_LADEN_ORE = BLOCKS.registerBlock("deep_egg_laden_ore", EggLadenOreBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.COLOR_ORANGE).strength(4.5F, 3.0F).requiresCorrectToolForDrops().lightLevel(s -> 3));
    public static final DeferredBlock<ColoredFallingBlock> CORAL_SAND = BLOCKS.registerBlock("coral_sand", p -> new ColoredFallingBlock(new ColorRGBA(0xF58A9C), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SAND).mapColor(MapColor.COLOR_PINK));
    public static final DeferredBlock<GlowKelpBlock> ROSE_GLOWKELP = BLOCKS.registerBlock("rose_glowkelp", GlowKelpBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.KELP_PLANT).mapColor(MapColor.COLOR_PINK).lightLevel(s -> s.getValue(com.thesift.block.GlowKelpBlock.TIP) ? 12 : 7));
    public static final DeferredBlock<GlowKelpBlock> AZURE_GLOWKELP = BLOCKS.registerBlock("azure_glowkelp", GlowKelpBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.KELP_PLANT).mapColor(MapColor.COLOR_LIGHT_BLUE).lightLevel(s -> s.getValue(com.thesift.block.GlowKelpBlock.TIP) ? 12 : 7));
    public static final DeferredBlock<GlowKelpBlock> AMBER_GLOWKELP = BLOCKS.registerBlock("amber_glowkelp", GlowKelpBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.KELP_PLANT).mapColor(MapColor.COLOR_ORANGE).lightLevel(s -> s.getValue(com.thesift.block.GlowKelpBlock.TIP) ? 12 : 7));
    public static final DeferredBlock<WaterPlantBlock> ABYSS_ANEMONE = BLOCKS.registerBlock("abyss_anemone", WaterPlantBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SEAGRASS).mapColor(MapColor.COLOR_CYAN).lightLevel(s -> 9).replaceable());
    public static final DeferredBlock<CloudBlock> CLOUD_BLOCK = BLOCKS.registerBlock("cloud_block", CloudBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS).mapColor(MapColor.SNOW).strength(0.2F).sound(SoundType.WOOL).isValidSpawn(com.thesift.block.CloudBlock::spawnable));
    public static final DeferredBlock<ChimeBellBlock> CHIME_BELL = BLOCKS.registerBlock("chime_bell", ChimeBellBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POPPY).mapColor(MapColor.COLOR_LIGHT_BLUE).lightLevel(s -> 6));
    public static final DeferredBlock<OrganReedBlock> ORGAN_REED = BLOCKS.registerBlock("organ_reed", OrganReedBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.PEONY).mapColor(MapColor.COLOR_PURPLE).lightLevel(s -> 4));
    public static final DeferredBlock<EchoerDeviceBlock> ECHOER_DEVICE = BLOCKS.registerBlock("echoer_device", EchoerDeviceBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN).strength(3.5F, 6.0F).requiresCorrectToolForDrops().lightLevel(s -> s.getValue(com.thesift.block.EchoerDeviceBlock.CHARGING) ? 11 : 4));
    public static final DeferredBlock<EchoerHutHeartBlock> ECHOER_HUT_HEART = BLOCKS.registerBlock("echoer_hut_heart", EchoerHutHeartBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS).mapColor(MapColor.COLOR_CYAN).strength(-1.0F, 3600000.0F).noLootTable().lightLevel(s -> 9));
    public static final DeferredBlock<SculkBloomBlock> SCULK_BLOOM = BLOCKS.registerBlock("sculk_bloom", p -> new SculkBloomBlock(MobEffects.DARKNESS, 4.0F, 3, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POPPY).mapColor(MapColor.COLOR_CYAN).sound(SoundType.SCULK));
    public static final DeferredBlock<PottedSculkBloomBlock> POTTED_SCULK_BLOOM = BLOCKS.registerBlock("potted_sculk_bloom", p -> new PottedSculkBloomBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, SCULK_BLOOM, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POTTED_POPPY).lightLevel(s -> 3));
    public static final DeferredBlock<SiftGrassBlock> WHITE_TURF = BLOCKS.registerBlock("white_turf", SiftGrassBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.GRASS_BLOCK).mapColor(MapColor.SNOW));
    public static final DeferredBlock<SiftLeavesBlock> WHITE_LULLWOOD_LEAVES = BLOCKS.registerBlock("white_lullwood_leaves", p -> new SiftLeavesBlock(0.04F, () -> ModSwifter.WHITE_FLUFF.get(), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.PALE_OAK_LEAVES).mapColor(MapColor.SNOW));
    public static final DeferredBlock<SiftSaplingBlock> WHITE_LULLWOOD_SAPLING = BLOCKS.registerBlock("white_lullwood_sapling", p -> new SiftSaplingBlock(ModSwifter.WHITE_LULLWOOD, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SAPLING));
    public static final DeferredBlock<FlowerPotBlock> POTTED_WHITE_LULLWOOD_SAPLING = BLOCKS.registerBlock("potted_white_lullwood_sapling", p -> new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, WHITE_LULLWOOD_SAPLING, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POTTED_OAK_SAPLING));
    public static final DeferredBlock<SiftFlowerBlock> PUFFBLOOM = BLOCKS.registerBlock("puffbloom", p -> new SiftFlowerBlock(MobEffects.SLOW_FALLING, 6.0F, 0, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POPPY));
    public static final DeferredBlock<FlowerPotBlock> POTTED_PUFFBLOOM = BLOCKS.registerBlock("potted_puffbloom", p -> new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, PUFFBLOOM, p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.POTTED_POPPY));
    public static final DeferredBlock<SwifterDenBlock> SWIFTER_DEN = BLOCKS.registerBlock("swifter_den", SwifterDenBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.HAY_BLOCK).mapColor(MapColor.SNOW).strength(0.8F).sound(SoundType.WOOL).noOcclusion());
    public static final DeferredBlock<SiftSnifferEggBlock> SIFT_SNIFFER_EGG = BLOCKS.registerBlock("sift_sniffer_egg", SiftSnifferEggBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SNIFFER_EGG).mapColor(MapColor.COLOR_PINK).noOcclusion());
    public static final DeferredBlock<ChimeSandBlock> CHIME_SAND = BLOCKS.registerBlock("chime_sand", ChimeSandBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SAND).mapColor(MapColor.QUARTZ));
    public static final DeferredBlock<ChimeGlassBlock> CHIME_GLASS = BLOCKS.registerBlock("chime_glass", ChimeGlassBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS).sound(com.thesift.block.ChimeGlassBlock.SOUND));
    public static final DeferredBlock<ChimeGlassPaneBlock> CHIME_GLASS_PANE = BLOCKS.registerBlock("chime_glass_pane", ChimeGlassPaneBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS_PANE).sound(com.thesift.block.ChimeGlassBlock.SOUND));
    public static final DeferredBlock<SculkMudBlock> SCULK_MUD = BLOCKS.registerBlock("sculk_mud", SculkMudBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.MUD).mapColor(MapColor.COLOR_CYAN).speedFactor(0.65F));
    public static final DeferredBlock<SculkWaterBlock> SCULK_WATER = BLOCKS.registerBlock("sculk_water", SculkWaterBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).mapColor(MapColor.COLOR_CYAN).lightLevel(s -> 2));
    public static final DeferredBlock<Block> SCULK_CORAL_BLOCK = BLOCKS.registerBlock("sculk_coral_block", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.TUBE_CORAL_BLOCK).mapColor(MapColor.COLOR_CYAN).lightLevel(s -> 3));
    public static final DeferredBlock<BaseCoralPlantBlock> SCULK_CORAL = BLOCKS.registerBlock("sculk_coral", BaseCoralPlantBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.TUBE_CORAL).mapColor(MapColor.COLOR_CYAN).lightLevel(s -> 4));
    public static final DeferredBlock<BaseCoralFanBlock> SCULK_CORAL_FAN = BLOCKS.registerBlock("sculk_coral_fan", BaseCoralFanBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.TUBE_CORAL).mapColor(MapColor.COLOR_CYAN).lightLevel(s -> 4));
    public static final DeferredBlock<BaseCoralWallFanBlock> SCULK_CORAL_WALL_FAN = BLOCKS.registerBlock("sculk_coral_wall_fan", BaseCoralWallFanBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.TUBE_CORAL).mapColor(MapColor.COLOR_CYAN).lightLevel(s -> 4));
    public static final DeferredBlock<DropExperienceBlock> SCULKITE_ORE = BLOCKS.registerBlock("sculkite_ore", p -> new DropExperienceBlock(UniformInt.of(1, 4), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.COLOR_CYAN).sound(SoundType.SCULK).strength(4.0F, 6.0F).requiresCorrectToolForDrops().lightLevel(s -> 3));
    public static final DeferredBlock<Block> SCULKITE_BLOCK = BLOCKS.registerBlock("sculkite_block", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.AMETHYST_BLOCK).mapColor(MapColor.COLOR_CYAN).strength(5.0F, 6.0F).requiresCorrectToolForDrops().lightLevel(s -> 5));
    public static final DeferredBlock<BauxiteOreBlock> BAUXITE_ORE = BLOCKS.registerBlock("bauxite_ore", BauxiteOreBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.TERRACOTTA_ORANGE).strength(3.0F, 3.0F).requiresCorrectToolForDrops());
    public static final DeferredBlock<BauxiteOreBlock> DEEP_BAUXITE_ORE = BLOCKS.registerBlock("deep_bauxite_ore", BauxiteOreBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.TERRACOTTA_ORANGE).strength(3.0F, 3.0F).requiresCorrectToolForDrops());
    public static final DeferredBlock<Block> MAGNESITE = BLOCKS.registerBlock("magnesite", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).strength(1.5F, 6.0F).requiresCorrectToolForDrops());
    public static final DeferredBlock<DropExperienceBlock> GALENA_ORE = BLOCKS.registerBlock("galena_ore", p -> new DropExperienceBlock(UniformInt.of(1, 4), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.COLOR_GRAY).strength(3.0F, 3.0F).requiresCorrectToolForDrops());
    public static final DeferredBlock<DropExperienceBlock> DEEP_GALENA_ORE = BLOCKS.registerBlock("deep_galena_ore", p -> new DropExperienceBlock(UniformInt.of(1, 4), p),
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE).mapColor(MapColor.COLOR_GRAY).strength(3.0F, 3.0F).requiresCorrectToolForDrops());
    public static final DeferredBlock<Block> PURE_SOUL_BLOCK = BLOCKS.registerBlock("pure_soul_block", Block::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SEA_LANTERN).mapColor(MapColor.COLOR_BLUE).strength(2.0F, 6.0F).lightLevel(s -> 12));
    public static final DeferredBlock<EurophyTableBlock> EUROPHY_TABLE = BLOCKS.registerBlock("europhy_table", EurophyTableBlock::new,
            () -> BlockBehaviour.Properties.ofFullCopy(Blocks.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).strength(3.0F, 6.0F).requiresCorrectToolForDrops().lightLevel(s -> 6).noOcclusion());

    private ModBlocks() {}
}
