"""Generates ModBlocks.java / ModItems.java / ModCreativeTabs content lists from tools/spec.py."""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from spec import BLOCKS, ITEMS, WOODS  # noqa: E402

ROOT = os.path.join(os.path.dirname(__file__), "..", "src", "main", "java", "com", "thesift", "registry")


def const(id):
    return id.upper()


def block_ctor(b):
    k = b["kind"]
    p = "p"
    w = b.get("wood")
    if k in ("cube", "ore_plain"):
        return "Block::new"
    if k in ("sandstone", "sandstone_cut", "sandstone_chiseled"):
        return "Block::new"
    if k == "ore":
        return "p -> new DropExperienceBlock(UniformInt.of(1, 4), p)"
    if k in ("pillar", "log", "wood"):
        return "RotatedPillarBlock::new"
    if k == "stairs":
        return f"p -> new StairBlock({const(b['basis'])}.get().defaultBlockState(), p)"
    if k == "slab":
        return "SlabBlock::new"
    if k == "wall":
        return "WallBlock::new"
    if k == "fence":
        return "FenceBlock::new"
    if k == "fence_gate":
        return f"p -> new FenceGateBlock(ModWoodTypes.{w.upper()}, p)"
    if k == "door":
        return f"p -> new DoorBlock(ModWoodTypes.{w.upper()}_SET, p)"
    if k == "trapdoor":
        return f"p -> new TrapDoorBlock(ModWoodTypes.{w.upper()}_SET, p)"
    if k == "button":
        return f"p -> new ButtonBlock(ModWoodTypes.{w.upper()}_SET, 30, p)"
    if k == "pressure_plate":
        return f"p -> new PressurePlateBlock(ModWoodTypes.{w.upper()}_SET, p)"
    if k == "leaves":
        return f"p -> new SiftLeavesBlock({b['chance']}, () -> {b['particle']}.get(), p)"
    if k == "sapling":
        return f"p -> new SiftSaplingBlock({b['grower']}, p)"
    if k == "flower":
        cls = b.get("cls", "FlowerBlock")
        return f"p -> new {cls}({b['effect']}, {b['secs']}, {b.get('light', 0)}, p)"
    if k == "pot":  # cls: a FlowerPotBlock subclass (A1: the potted Sculk Bloom)
        return f"p -> new {b.get('cls', 'FlowerPotBlock')}(() -> (FlowerPotBlock) Blocks.FLOWER_POT, {const(b['plant'])}, p)"
    if k == "falling":
        return f"p -> new ColoredFallingBlock(new ColorRGBA({b['dust']}), p)"
    if k == "carpet":
        return "CarpetBlock::new"
    if k == "glass":
        return "TransparentBlock::new"
    if k == "custom":
        return f"{b['cls']}::new"
    raise ValueError(k)


def block_type(b):
    k = b["kind"]
    return {
        "cube": "Block", "sandstone": "Block", "sandstone_cut": "Block", "sandstone_chiseled": "Block", "ore": "DropExperienceBlock",
        "pillar": "RotatedPillarBlock", "log": "RotatedPillarBlock", "wood": "RotatedPillarBlock", "stairs": "StairBlock", "slab": "SlabBlock",
        "wall": "WallBlock", "fence": "FenceBlock", "fence_gate": "FenceGateBlock", "door": "DoorBlock", "trapdoor": "TrapDoorBlock",
        "button": "ButtonBlock", "pressure_plate": "PressurePlateBlock", "leaves": "SiftLeavesBlock", "sapling": "SiftSaplingBlock",
        "flower": b.get("cls", "FlowerBlock"), "pot": b.get("cls", "FlowerPotBlock"), "falling": "ColoredFallingBlock", "carpet": "CarpetBlock",
        "glass": "TransparentBlock", "custom": b.get("cls"),
    }[k]


def gen_blocks():
    out = []
    out.append("// GENERATED by tools/gen_java.py from tools/spec.py - do not edit by hand.")
    out.append("package com.thesift.registry;\n")
    out.append("""import com.thesift.TheSift;
import com.thesift.block.*;
import net.minecraft.util.ColorRGBA;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredRegister;

public final class ModBlocks {
    public static final DeferredRegister.Blocks BLOCKS = DeferredRegister.createBlocks(TheSift.MODID);
""")
    for b in BLOCKS:
        t = block_type(b)
        props = b["props"]
        out.append(f"    public static final DeferredBlock<{t}> {const(b['id'])} = BLOCKS.registerBlock(\"{b['id']}\", {block_ctor(b)},\n"
                   f"            () -> {props});")
    out.append("\n    private ModBlocks() {}\n}\n")
    open(os.path.join(ROOT, "ModBlocks.java"), "w").write("\n".join(out))


def item_entry(i):
    cls = i.get("cls")
    props = i.get("props", "new Item.Properties()")
    id = i["id"]
    if cls is None:
        return "Item", f"ITEMS.registerItem(\"{id}\", Item::new, () -> {props})"
    if cls.startswith("BlockItem:"):
        blk = const(cls.split(":")[1])
        return "BlockItem", f"ITEMS.registerItem(\"{id}\", p -> new BlockItem(ModBlocks.{blk}.get(), p), () -> {props})"
    if cls.startswith("tool:"):
        t = cls.split(":")[1]
        spec = {
            "sword": "sword(ModMaterials.SIFTITE_TOOL, 3.0F, -2.4F)",
            "pickaxe": "pickaxe(ModMaterials.SIFTITE_TOOL, 1.0F, -2.8F)",
            "axe": "axe(ModMaterials.SIFTITE_TOOL, 5.5F, -3.0F)",
            "shovel": "shovel(ModMaterials.SIFTITE_TOOL, 1.5F, -3.0F)",
            "hoe": "hoe(ModMaterials.SIFTITE_TOOL, -3.0F, 0.0F)",
            "spear": "spear(ModMaterials.SIFTITE_TOOL, 0.8F, 0.9F, 0.6F, 4.5F, 11.0F, 8.5F, 4.9F, 13.0F, 4.4F)",
        }[t]
        ctor = "Item::new"
        return "Item", f"ITEMS.registerItem(\"{id}\", {ctor}, () -> new Item.Properties().{spec})"
    if cls.startswith("armor:"):
        a = cls.split(":")[1].upper()
        return "Item", f"ITEMS.registerItem(\"{id}\", Item::new, () -> new Item.Properties().humanoidArmor(ModMaterials.SIFTITE_ARMOR, ArmorType.{a}))"
    if cls.startswith("egg:"):
        m = const(cls.split(":")[1])
        return "SpawnEggItem", f"ITEMS.registerItem(\"{id}\", SpawnEggItem::new, () -> new Item.Properties().spawnEgg(ModEntities.{m}.get()))"
    if i.get("factory"):  # A3 Chrome: items built by a lambda (the Chrome fish buckets)
        return cls, f"ITEMS.registerItem(\"{id}\", {i['factory']}, () -> {props})"
    return cls, f"ITEMS.registerItem(\"{id}\", {cls}::new, () -> {props})"


def gen_items():
    out = []
    out.append("// GENERATED by tools/gen_java.py from tools/spec.py - do not edit by hand.")
    out.append("package com.thesift.registry;\n")
    out.append("""import com.thesift.TheSift;
import com.thesift.item.*;
import net.minecraft.world.item.*;
import net.minecraft.world.item.equipment.ArmorType;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

public final class ModItems {
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(TheSift.MODID);

    // ---- block items
""")
    for b in BLOCKS:
        if not b.get("item", True):
            continue
        ik = b.get("item_kind", "block")
        c = const(b["id"])
        if b["kind"] == "door" or ik == "double":
            out.append(f"    public static final DeferredItem<DoubleHighBlockItem> {c} = ITEMS.registerItem(\"{b['id']}\", p -> new DoubleHighBlockItem(ModBlocks.{c}.get(), p), () -> new Item.Properties().useBlockDescriptionPrefix());")
        elif ik == "stack1":
            out.append(f"    public static final DeferredItem<BlockItem> {c} = ITEMS.registerSimpleBlockItem(\"{b['id']}\", ModBlocks.{c}, p -> p.stacksTo(1));")
        else:
            out.append(f"    public static final DeferredItem<BlockItem> {c} = ITEMS.registerSimpleBlockItem(ModBlocks.{c});")
    out.append("\n    // ---- items")
    for i in ITEMS:
        t, e = item_entry(i)
        out.append(f"    public static final DeferredItem<{t}> {const(i['id'])} = {e};")
    out.append("\n    private ModItems() {}\n}\n")
    open(os.path.join(ROOT, "ModItems.java"), "w").write("\n".join(out))


def gen_tabs():
    tabs = {"blocks": [], "nature": [], "functional": [], "items": [], "tools": [], "combat": [], "eggs": []}
    nature_kinds = {"leaves", "sapling", "flower", "log"}
    for b in BLOCKS:
        if not b.get("item", True):
            continue
        tab = b.get("tab", "blocks")
        if tab == "blocks" and (b["kind"] in nature_kinds or b.get("cls") in (
                "BlushgrassBlock", "SiftDoublePlantBlock", "SiftPlantBlock", "DriftPetalsBlock", "EchoOrchidBlock",  # W1: ChoirLilyBlock removed
                "ChromeReedsBlock", "GlowcapBlock", "GlowbellVineBlock", "HangingLullwoodLeavesBlock", "SiftGrassBlock", "LumenMossBlock")
                or b["id"] in ("sift_soil", "dreamsand", "serbim_ore", "deep_serbim_ore", "hushslate", "dreamstone", "lumen_moss_carpet")):
            tab = "nature"
        tabs.setdefault(tab, []).append(const(b["id"]))
    for i in ITEMS:
        tabs.setdefault(i.get("tab", "items"), []).append(const(i["id"]))
    out = ["// GENERATED by tools/gen_java.py from tools/spec.py - do not edit by hand.", "package com.thesift.registry;\n",
           "import java.util.List;", "import java.util.function.Supplier;", "import net.minecraft.world.item.Item;\n",
           "public final class ModTabContents {"]
    for tab, entries in tabs.items():
        out.append(f"    public static List<Supplier<? extends Item>> {tab}() {{")
        out.append("        return List.of(" + ", ".join(f"ModItems.{e}" for e in entries) + ");")
        out.append("    }\n")
    out.append("    private ModTabContents() {}\n}\n")
    open(os.path.join(ROOT, "ModTabContents.java"), "w").write("\n".join(out))


def main():
    os.makedirs(ROOT, exist_ok=True)
    gen_blocks()
    gen_items()
    gen_tabs()
    print(f"generated {len(BLOCKS)} blocks, {len(ITEMS)} items")


if __name__ == "__main__":
    main()
