"""Generates mob model geometry (Java), textures and preview renders from tools/mobs.py."""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from modelkit import Pose, preview, render_textures  # noqa: E402
import mobs  # noqa: E402

ROOT = os.path.join(os.path.dirname(__file__), '..')
JAVA = os.path.join(ROOT, 'src/main/java/com/thesift/client/model/ModelGeometry.java')
TEX = os.path.join(ROOT, 'src/main/resources/assets/thesift/textures/entity')
PREVIEW = os.path.join(ROOT, 'build/previews')

POSES = {
    'bulb': {'rest': Pose(), 'jump': Pose(body={'scale': (0.85, 1.3, 0.85)}, left_ear={'rot': (0.6, 0, 0)}, right_ear={'rot': (0.6, 0, 0)},
                                                 left_ear_tip={'rot': (0.5, 0, 0)}, right_ear_tip={'rot': (0.4, 0, 0)}),
             'land': Pose(body={'scale': (1.25, 0.7, 1.25)}, left_ear={'rot': (-0.5, 0, 0.3)}, right_ear={'rot': (-0.5, 0, -0.3)})},
    'slumbler': {'rest': Pose(), 'yawn': Pose(head={'rot': (-0.35, 0, 0)}, jaw={'rot': (0.9, 0, 0)})},
    'sifter': {'rest': Pose(), 'chomp': Pose(lid={'rot': (-0.9, 0, 0)}), 'walk': Pose(left_leg={'rot': (0.5, 0, 0)}, right_leg={'rot': (-0.5, 0, 0)})},
    'enchoer': {'rest': Pose(), 'ponder': Pose(right_arm={'rot': (-1.25, 0.45, 0)}, right_forearm={'rot': (-1.3, 0, 0)}, head={'rot': (0.15, 0, 0.12)}),
                'sing': Pose(left_arm={'rot': (0, 0, -1.1)}, right_arm={'rot': (0, 0, 1.1)}, left_forearm={'rot': (0, 0, -0.5)},
                             right_forearm={'rot': (0, 0, 0.5)}, head={'rot': (-0.45, 0, 0)})},
    'riveter': {'rest': Pose(),
                'hang': Pose(body={'rot': (0, 0, 3.14159), 'pos': (0, -30, 0)}, left_wing={'rot': (3.0, 0, 0.1)}, right_wing={'rot': (3.0, 0, -0.1)},
                             head={'rot': (-0.5, 0, 0)}),
                'scream': Pose(left_wing={'rot': (0, 0, -1.3)}, right_wing={'rot': (0, 0, 1.3)}, jaw={'rot': (0.8, 0, 0)}, head={'rot': (-0.2, 0, 0)},
                               **{f'{s}_claw_{i}': {'rot': (0, 0, (i - 1.5) * 0.25 * (1 if s == 'left' else -1))} for s in ('left', 'right') for i in range(4)})},
    'harmoner': {'rest': Pose(), 'fly': Pose(left_wing={'rot': (0, 0, -1.3)}, right_wing={'rot': (0, 0, 1.3)}, left_leg={'rot': (0.9, 0, 0)},
                                              right_leg={'rot': (0.9, 0, 0)}),
                 'sing': Pose(head={'rot': (-0.5, 0, 0)}, jaw={'rot': (0.6, 0, 0)}, crest={'rot': (0.4, 0, 0)}, plume_0={'rot': (0, 0, -0.3)},
                              plume_2={'rot': (0, 0, 0.3)})},
}


def main(previews=True):
    methods = []
    for name, fn in mobs.ALL.items():
        m = fn()
        m.pack()
        methods.append(m.java_method(name))
        texs = render_textures(m)
        os.makedirs(os.path.join(TEX, name), exist_ok=True)
        for vname, (img, glow) in texs.items():
            img.save(os.path.join(TEX, name, f'{vname}.png'))
            # emissive layers stay the same whatever the face is doing
            if glow is not None and vname in m.variants:
                glow.save(os.path.join(TEX, name, f'{vname}_glow.png'))
        if previews:
            os.makedirs(PREVIEW, exist_ok=True)
            first = next(iter(texs.values()))[0]
            for pname, pose in POSES.get(name, {'rest': Pose()}).items():
                for lid in ('eyelids', 'left_eyelid', 'right_eyelid'):
                    pose.parts.setdefault(lid, {'visible': False})
                for yaw in (35, 150):
                    img = preview(m, first, pose, yaw=yaw, scale=7 if name in ('enchoer', 'slumbler', 'enforcer', 'howler', 'resonator') else 5 if name == 'dictator' else 14 if name == 'harmoner' else 9)
                    img.save(os.path.join(PREVIEW, f'{name}_{pname}_{yaw}.png'))
    src = ['// GENERATED by tools/gen_models.py from tools/mobs.py - do not edit by hand.',
           'package com.thesift.client.model;', '',
           'import net.minecraft.client.model.geom.PartPose;',
           'import net.minecraft.client.model.geom.builders.CubeDeformation;',
           'import net.minecraft.client.model.geom.builders.CubeListBuilder;',
           'import net.minecraft.client.model.geom.builders.LayerDefinition;',
           'import net.minecraft.client.model.geom.builders.MeshDefinition;',
           'import net.minecraft.client.model.geom.builders.PartDefinition;', '',
           'public final class ModelGeometry {',
           '    private ModelGeometry() {', '    }', '']
    src.append('\n\n'.join(methods))
    src.append('}')
    os.makedirs(os.path.dirname(JAVA), exist_ok=True)
    with open(JAVA, 'w') as f:
        f.write('\n'.join(src) + '\n')
    print('models ok')


if __name__ == '__main__':
    main('--no-preview' not in sys.argv)
