"""Hand-drawn 16x16 pixel sprites (ASCII) for The Sift's plants and items.

'.' is transparent; every other character maps to a colour in the sprite's key table.
"""

# ============================================================================ PLANTS

LULLABY_BELL = ([
    '................',
    '.......gg.......',
    '......g..g......',
    '.....g....g.....',
    '....g......s....',
    '...cC.....cCc...',
    '..cCCc...cCWCc..',
    '..cCWc...cCCCc..',
    '..cCCc....cdc...',
    '...cd......s....',
    '....s......s....',
    '....s.....ls....',
    '.....s...ls.....',
    '......s.s.......',
    '......ss........',
    '.......s........',
], {'g': '#4fae8a', 's': '#3c9a78', 'l': '#6cc79a', 'c': '#55c9e8', 'C': '#8ae6f7', 'W': '#e8fdff', 'd': '#2f8fb8'})

DREAMBLOOM = ([
    '................',
    '.....pP..Pp.....',
    '....pPPPPPPp....',
    '...pPPWPPWPPp...',
    '...PPPyyyyPPP...',
    '...pPPyYYyPPp...',
    '....pPPyyPPp....',
    '.....pPPPPp.....',
    '.......ss.......',
    '....ll.s........',
    '...lLLls........',
    '....lls..ll.....',
    '.......sLLl.....',
    '.......sll......',
    '.......s........',
    '.......s........',
], {'p': '#e472a8', 'P': '#f7a2cb', 'W': '#ffe4f1', 'y': '#ffd66b', 'Y': '#fff2b0', 's': '#3f9d80', 'l': '#4fb58f', 'L': '#78d4a8'})

SOULPETAL = ([
    '................',
    '......w..w......',
    '.....wWw.wWw....',
    '......wWWWw.....',
    '....wwWbbBWww...',
    '...wWWbBBBbWWw..',
    '....wwWbBbWww...',
    '......wWWWw.....',
    '.....wWw.wWw....',
    '......w.s.w.....',
    '........s.......',
    '.....l..s.......',
    '....lLl.s..l....',
    '.....l.ss.lLl...',
    '........s..l....',
    '........s.......',
], {'w': '#cfe3ff', 'W': '#f4f9ff', 'b': '#57c6ff', 'B': '#a6f0ff', 's': '#4d9a8d', 'l': '#5aaf98', 'L': '#8ad8bd'})

NEBULA_IRIS = ([
    '................',
    '.......vV.......',
    '......vVVv......',
    '...v..vVSv..v...',
    '..vVv.vVVv.vVv..',
    '..vVVvvVVvvVVv..',
    '...vVVyVVyVVv...',
    '....vvVyyVvv....',
    '......vvvv......',
    '.......ss.......',
    '.......s........',
    '.....l.s..l.....',
    '.....lls.ll.....',
    '......lsll......',
    '.......s........',
    '.......s........',
], {'v': '#7b4fcf', 'V': '#a98af0', 'S': '#fff6c8', 'y': '#ffd66b', 's': '#3f8f86', 'l': '#56b3a0'})

ECHO_ORCHID = ([
    '................',
    '................',
    '.....b.....b....',
    '....bBb...bBb...',
    '....bBBb.bBBb...',
    '.....bBBGBBb....',
    '......bGWGb.....',
    '.....bBBGBBb....',
    '....bBb.s.bBb...',
    '....bb..s..bb...',
    '........s.......',
    '.....ll.s.......',
    '....lLLls.ll....',
    '.....ll.slLLl...',
    '........s.ll....',
    '........s.......',
], {'b': '#3b7fe0', 'B': '#79b7ff', 'G': '#b8fbff', 'W': '#ffffff', 's': '#3d8a8a', 'l': '#4fa6a0', 'L': '#7fd0c4'})

GLOWCAP = ([
    '................',
    '................',
    '.....cCCc.......',
    '....cCWCCc......',
    '...cCCCCCCc.....',
    '...ddcddcdd.....',
    '.....ss....cCc..',
    '.....ss...cCWCc.',
    '.....ss...ddddd.',
    '..cc.ss....ss...',
    '.cCCcss....ss...',
    '.dddd.s....ss...',
    '..ss..ss...ss...',
    '..ss..ss...ss...',
    '.ssss.sss.ssss..',
    '................',
], {'c': '#37c9d6', 'C': '#8ff3f0', 'W': '#e8fffb', 'd': '#1f8f9e', 's': '#d8e8f0'})

BLUSHGRASS = ([
    '................',
    '................',
    '.......p........',
    '..p....p.....p..',
    '..p...pP....p...',
    '..pP..pP...pP...',
    '...p..pP...p..p.',
    '...pP.pP..pP.pP.',
    '.p.pP.pP..p..p..',
    '.pP.p.p...p.pP..',
    '..p.pPp..pP.p...',
    '..pP.pp..p..p...',
    '...p.pP.pP.pP...',
    '...pP.p.p..p....',
    '....p.pPp.pP....',
    '....p..p..p.....',
], {'p': '#d9709c', 'P': '#f59cc0'})

GLIMMER_SPROUTS = ([
    '................',
    '................',
    '................',
    '....y.......y...',
    '....s...y...s...',
    '....s...s...s...',
    '..y.ss..s..ss.y.',
    '..s..s.ss..s..s.',
    '..ss.s.s..ss.ss.',
    '...s.ss.s.s..s..',
    '...ss.s.s.s.ss..',
    '....s.s.sss.s...',
    '....sssss.sss...',
    '.....sss..ss....',
    '......s...s.....',
    '................',
], {'s': '#57c7a2', 'y': '#fff4a8'})

TALL_BLUSHGRASS_TOP = ([
    '................',
    '................',
    '......p.........',
    '......p.....p...',
    '..p...pP...pP...',
    '..pP..pP...p....',
    '...p..pP..pP....',
    '...pP.pP..p...p.',
    '....p.pP..p..pP.',
    '....pP.p.pP..p..',
    '.p...p.p.p..pP..',
    '.pP..p.ppP..p...',
    '..p..pP.p..pP...',
    '..pP..p.p..p....',
    '...p..pPp.pP....',
    '...pP..pp.p.....',
], {'p': '#d9709c', 'P': '#f59cc0'})

TALL_BLUSHGRASS_BOTTOM = ([
    '...p..pPp.pP....',
    '...pP.pP..p...p.',
    '....p.pP..p..pP.',
    '..p.pP.p.pP..p..',
    '..pP.p.p.p..pP..',
    '...p.p.ppP..p...',
    '...pPpP.p..pP...',
    '....p.p.p..p....',
    '....pPpPp.pP....',
    '.....p.pp.p.....',
    '.....pPpp.p.....',
    '......p.ppP.....',
    '......pPpp......',
    '.......pp.......',
    '.......pp.......',
    '.......p........',
], {'p': '#c75f8c', 'P': '#e98bb2'})

LULLWOOD_SAPLING = ([
    '................',
    '................',
    '.....cCCc.......',
    '....cCWCCc......',
    '...cCCCCCCc.....',
    '...ccCCCCcc.....',
    '....cccccc..cc..',
    '......b....cCCc.',
    '......b...ccCCc.',
    '......bb...ccc..',
    '.......b..b.....',
    '.......bbb......',
    '.......b........',
    '.......b........',
    '......bb........',
    '.......b........',
], {'c': '#4fd1d0', 'C': '#93efe6', 'W': '#e0fffb', 'b': '#8a84ad'})

WISHWOOD_SAPLING = ([
    '................',
    '.......y........',
    '.....pPPp.......',
    '....pPWPPp......',
    '...pPPPyPPp.....',
    '...ppPPPPpp.....',
    '....pppppp..pp..',
    '......b....pPPp.',
    '......b...ppyPp.',
    '......bb...ppp..',
    '.......b..b.....',
    '.......bbb......',
    '.......b........',
    '.......b........',
    '......bb........',
    '.......b........',
], {'p': '#ef8fc0', 'P': '#fbc0dc', 'W': '#fff0f7', 'y': '#ffe89a', 'b': '#8f4c70'})

CHROME_REEDS = ([
    '..c.......c.....',
    '..C.....c.C.....',
    '..c.....C.c..c..',
    '..c..c..c.c..C..',
    '..C..C..c.C..c..',
    '..c..c..C.c..c..',
    '..c..c..c.c..c..',
    '..w..c..w.w..C..',
    '..c..w..c.c..c..',
    '..C..c..c.C..w..',
    '..c..C..C.c..c..',
    '..c..c..c.c..c..',
    '..w..c..c.w..C..',
    '..c..w..w.c..c..',
    '..C..c..c.C..c..',
    '..c..c..c.c..c..',
], {'c': '#69c9d9', 'C': '#b5f0f7', 'w': '#f2a7d8'})

GLOWBELL_VINE = ([
    '......vv........',
    '.......v........',
    '......vv........',
    '......v..l......',
    '.....vv.lL......',
    '......v.l.......',
    '......vv........',
    '.......v........',
    '...l...vv.......',
    '..lL...v........',
    '...l..vv........',
    '......v.........',
    '......vv........',
    '.......v........',
    '.......v........',
    '.......v........',
], {'v': '#3aa39a', 'l': '#4dbbb0', 'L': '#7fe0d4'})

GLOWBELL_BELL = {'b': '#ffe27a', 'B': '#fff7c8', 'd': '#e0a73c'}

GLOWBELL_VINE_LIT_EXTRA = [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '........bb......',
    '.......bBBb.....',
    '.......bBBb.....',
    '........dd......',
    '................',
    '................',
    '................',
    '................',
    '................',
]

HANGING_LEAVES = ([
    '.Cd..cd..cd.cd..',
    '.cd..cd..Cd.cd..',
    '.cdcccd..cdccd..',
    '.cd..cd..cd.cd..',
    '.cd..Cd..cd.cd..',
    '.cd..cd..cd.Cd..',
    '.cd..cd..cd.cd..',
    'cCd..cdcccd.cdc.',
    '.cd..cd..Cd.cd..',
    '.cd..cd..cd.cd..',
    '.cd..cd..cd.cd..',
    '.cd..Cd..cd.cd..',
    '.cdcccd..cdcCd..',
    '.cd..cd..cd.cd..',
    '.Cd..cd..cd.cd..',
    '.c...c...C..c...',
], {'c': '#c6d8e0', 'C': '#eaf3f6', 'd': '#94adbb', 'w': '#ffffff'})

HANGING_LEAVES_TIP = ([
    '.Cd..cd..cd.cd..',
    '.cd..cd..Cd.cd..',
    '.cdcccd..cdccd..',
    '.cd..cd..cd.cd..',
    '.cd..Cd..cd.cd..',
    '.cd..cd..cd.Cd..',
    '.cd..cd..cd.cd..',
    'cCd..cdcccd.cdc.',
    '.cd..cd..Cd.cd..',
    '.cd..cd..cd.cd..',
    '.cd..cd..cd.cd..',
    '.cd..w...w..cd..',
    '.w..........w...',
    '................',
    '................',
    '................',
], {'c': '#c6d8e0', 'C': '#eaf3f6', 'd': '#94adbb', 'w': '#ffffff'})


# ============================================================================ ITEMS


SOUL_CHIME_ITEM = [
    '.......dd.......',
    '.......d........',
    '....wwwwwwww....',
    '....wddddddw....',
    '.....t.t..t.....',
    '.....t.t..t.....',
    '.....t.t..t.....',
    '.....t.tc.t.....',
    '.....t.cCct.....',
    '.....t.cCc......',
    '.......tc.......',
    '.......t........',
    '................',
    '................',
    '................',
    '................',
]


# ---- reference-biome coral: chunky flame-like branching in four salmon tones (L light, p base, d dark, D deepest)
CORAL_PAL = {'L': '#ffa9aa', 'p': '#f37d84', 'd': '#e0606c', 'D': '#c44a5a'}
CORAL_BUSH = ([
    '................',
    '..L.......L.....',
    '..LL...L..LL..L.',
    '.LpL..LL.LpL.LL.',
    '.LppL.LpLLpp.Lp.',
    '..pppLppLppd.pp.',
    'L.ppdpppppdp.pd.',
    'LLpdppdppppdppd.',
    '.LppdppdppdpppdL',
    '.ppdpppppdppdppL',
    '..pdppdppppdpp..',
    '..ddpddpdpdppd..',
    '...dpdDdpdDdd...',
    '....dDdDddDd....',
    '.....DdDDdD.....',
    '......DDDD......',
], CORAL_PAL)
CORAL_THICKET_TOP = ([
    '....L......L....',
    '...LL..L..LL..L.',
    '.L.Lp..LL.Lp.LL.',
    '.LLpp.LpL.pp.Lp.',
    '..Lpp.Lpp.ppLpp.',
    'L.ppp.ppd.pp.pd.',
    'LLppdLppp.pdLpd.',
    '.Lpdp.ppdLppppd.',
    '.ppdpLpppppdppd.',
    '..pdpppdppdpppd.',
    'L.ppdppdpdppdpL.',
    'LLpdppdpdpppdppL',
    '.ppdpdppdppdpp..',
    '..pdppdpdpppdp..',
    '..dpppdpppdpdd..',
    '..ddpdppdpdpd...',
], CORAL_PAL)
CORAL_THICKET_BOTTOM = ([
    '.Lpd.Ldpp.Lpd.p.',
    '.pdp.dppL.pdp.pd',
    '..pdpdpp.Lpdppd.',
    'L.dpppdp.pdpdpL.',
    'Lp.dpdpdppdppd..',
    '.pd.ddpdppdpdd..',
    '..dp.dpdpddpd.p.',
    '...DddpdpdDd.pd.',
    '....DdDdddD.dd..',
    '.....DDdDDDdD...',
    '......DdDDD.....',
    '......DDDD......',
    '......DdD.......',
    '.......DDD......',
    '.......DD.......',
    '.......DD.......',
], CORAL_PAL)
